### ISSUE TITLE
Check VPN credential file exists when required

### ISSUE THREAD

**Issue by davestephens** [davestephens/ansible-nas#1]
If `transmission_with_openvpn_enabled` is set to true, we should check `vpn_credentials.yml` exists at the start of the playbook.

**Comment by animeai** [comment]
Been working on this in https://github.com/animeai/ansible-nas/tree/Fixes-and-new-containers and am pretty sure I've got it right now. Just need to do some proper testing of the modified containers and make sure I didn't completely break traefik or anything silly like that. Should be able to test with a proper domain in the next few days I hope. Would welcome any tests and feedback from others in the meantime though.

**Comment by davestephens** [comment]
No longer an issue since #193
