### ISSUE TITLE
Feature suggestion: Addition of ctop

### ISSUE THREAD

**Issue by animeai** [davestephens/ansible-nas#108]
I've found that when working with a lot of containers [ctop](https://github.com/bcicen/ctop) can be an invaluable tool when something is going wrong. It makes it very simple to see exactly which container is eating cpu/ram or causing the whole box to lag. While top and htop are useful here they don't quite come as close as ctop since you can use the features such as exec shell and view container logs straight from the top-style overview. 

While it can be implemented as a container, I find it much easier to place it into /usr/local/bin/ on the host.

**Comment by tekbuddha** [comment]
Hi there! I'd consider adding `ctop` to list of extra packages via `ansible_nas_extra_packages` in you `group_vars/all.yml`. It's an available package in Ubuntu 18.x so it can get installed without having to add any more Ansible tasks. Hope that helps!

**Comment by davestephens** [comment]
Good shout @tekbuddha, have added it.

I'd also like to add https://github.com/jesseduffield/lazydocker at some point....

**Comment by koenvervloesem** [comment]
@davestephens It seems like the ctop you have added (https://github.com/yadutaf/ctop) is another one than the one @animeai wanted to have (https://github.com/bcicen/ctop). I have no experience with either of them, so I don't know which one would be best to add.

Lazydocker or dockui (https://github.com/skanehira/docui) seems to be better indeed. There's too much choice :-)

**Comment by davestephens** [comment]
https://github.com/jesseduffield/lazydocker is probably worth adding. The current `ctop` is the wrong one!

**Comment by davestephens** [comment]
Closing on favour of #122
