### ISSUE TITLE
Feature request: Hass.io

### ISSUE THREAD

**Issue by sammaes** [davestephens/ansible-nas#110]
I have been searching for an easy method to integrate hass.io but unfortunately my docker and ansible knowledge is not sufficient enough.

During my investigation I found following script that might make it easier:
https://github.com/home-assistant/hassio-installer/blob/master/hassio_install.sh

**Comment by animeai** [comment]
Looking at it, hass.io is actually just an application that installs a set of docker containers - very much like ansible-nas itself. It is optimised for SOC devices (like raspberry pi) so while it would work on a full x86 nas server it may not be completely appropriate. Any of the services hass.io installs could be easily added to ansible-nas as new container images I think unless I'm missing something? I think trying to add a second manager to ansible-nas that uses its own series of docker images might cause more problems than it would solve in the long run as we're likely to hit compatibility issues...

**Comment by davestephens** [comment]
Yes, I don't think I'm understanding the point of using hass.io? Also, it
only appears to be provided for ARM architectures....

**Comment by davestephens** [comment]
OK, I'm gonna close this. Feel free to re-open if you feel this is really something we should consider including....

**Comment by ipenovich** [comment]
@davestephens 

I agree there's no need to use hass.io but home-assistant by itself would make a good addition.  I installed it manually on my ansible-nas box but I don't know enough about ansible or git to create a PR.

Manual installation is: docker run --init -d --name="home-assistant" -e "TZ=America/New_York" -v /PATH_TO_YOUR_CONFIG:/config --net=host homeassistant/home-assistant
