### ISSUE TITLE
Docker Unable to start

### ISSUE THREAD

**Issue by Micim987** [davestephens/ansible-nas#115]
**Short problem description**

I keep getting an error while trying to install docker using the playbook. I am running in a virtual machine to test until I can get it stable to deploy on my server. In the all.yml I have my docker home directory set to /tank/docker on my zfs tank and zfs is set the storage driver

**Environment**
- Ansible-NAS revision (`git rev-parse --short HEAD`): 867441e
- Ansible version (paste the entire output of `ansible --version` on the machine you run the playbook from): 2.5.1
- Ansible-NAS operating system (`cat /etc/lsb-release` on the Ansible-NAS box) - _If this is anything other than Ubuntu 18.04 help will be limited_: Ubuntu 18.04.2
- Ansible-NAS kernel (`cat /etc/lsb-release` on the Ansible-NAS box): Not listed
- Ansible-NAS Python version (`python --version` on the Ansible-NAS box): 2.7.15
- Ansible-NAS Docker version (`docker --version` on the Ansible-NAS box): 19.03.1 Build 74ble89
- Latest Docker logs (`journalctl -u docker.service` on the Ansible-NAS box): posted below
- Are you running the playbook from a remote box or the Ansible-NAS box itself? The NAS
- Vagrant version, if testing (`vagrant --version`)

**Expected behavior**

Playbook should run successfully 

**Actual behavior**

Playbook errors out at TASK [geerlingguy.docker : Ensure Docker is started and enabled at boot.]

**Steps to reproduce**

What does someone need to do to reproduce this?

Attempt to install on a clean install of Ubuntu 18.04.2 LTS 

Paste the output of the playbook at the problematic point.

```
TASK [geerlingguy.docker : Reload systemd daemon if template is changed.] ***********************************************************************************************************************************
task path: /root/.ansible/roles/geerlingguy.docker/tasks/docker-1809-shim.yml:13
skipping: [localhost] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}

TASK [geerlingguy.docker : Ensure Docker is started and enabled at boot.] ***********************************************************************************************************************************
task path: /root/.ansible/roles/geerlingguy.docker/tasks/main.yml:18
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/system/systemd.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1566747879.76-34933015883010 `" && echo ansible-tmp-1566747879.76-34933015883010="` echo /root/.ansible/tmp/ansible-tmp-1566747879.76-34933015883010 `" ) && sleep 0'
<localhost> PUT /root/.ansible/tmp/ansible-local-22197oGN7Pr/tmp8o7BaX TO /root/.ansible/tmp/ansible-tmp-1566747879.76-34933015883010/systemd.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1566747879.76-34933015883010/ /root/.ansible/tmp/ansible-tmp-1566747879.76-34933015883010/systemd.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1566747879.76-34933015883010/systemd.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1566747879.76-34933015883010/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "daemon_reload": false,
            "enabled": true,
            "masked": null,
            "name": "docker",
            "no_block": false,
            "state": "started",
            "user": false
        }
    },
    "msg": "Unable to start service docker: Job for docker.service failed because the control process exited with error code.\nSee \"systemctl status docker.service\" and \"journalctl -xe\" for details.\n"
}

PLAY RECAP **************************************************************************************************************************************************************************************************
localhost                  : ok=24   changed=0    unreachable=0    failed=1
```

Output of `systemctl status docker.service`

```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2019-08-25 11:44:46 EDT; 7min ago
     Docs: https://docs.docker.com
  Process: 23469 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
 Main PID: 23469 (code=exited, status=1/FAILURE)

Aug 25 11:44:46 ansible-nas systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Aug 25 11:44:46 ansible-nas systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
Aug 25 11:44:46 ansible-nas systemd[1]: Stopped Docker Application Container Engine.
Aug 25 11:44:46 ansible-nas systemd[1]: docker.service: Start request repeated too quickly.
Aug 25 11:44:46 ansible-nas systemd[1]: docker.service: Failed with result 'exit-code'.
Aug 25 11:44:46 ansible-nas systemd[1]: Failed to start Docker Application Container Engine.
```

output of `journalctl -xe`

```
-- the configured Restart= setting for the unit.
Aug 25 11:44:46 ansible-nas systemd[1]: Stopped Docker Application Container Engine.
-- Subject: Unit docker.service has finished shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit docker.service has finished shutting down.
Aug 25 11:44:46 ansible-nas systemd[1]: Closed Docker Socket for the API.
-- Subject: Unit docker.socket has finished shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit docker.socket has finished shutting down.
Aug 25 11:44:46 ansible-nas systemd[1]: Stopping Docker Socket for the API.
-- Subject: Unit docker.socket has begun shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit docker.socket has begun shutting down.
Aug 25 11:44:46 ansible-nas systemd[1]: Starting Docker Socket for the API.
-- Subject: Unit docker.socket has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit docker.socket has begun starting up.
Aug 25 11:44:46 ansible-nas systemd[1]: Listening on Docker Socket for the API.
-- Subject: Unit docker.socket has finished start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit docker.socket has finished starting up.
--
-- The start-up result is RESULT.
Aug 25 11:44:46 ansible-nas systemd[1]: docker.service: Start request repeated too quickly.
Aug 25 11:44:46 ansible-nas systemd[1]: docker.service: Failed with result 'exit-code'.
Aug 25 11:44:46 ansible-nas systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit docker.service has failed.
--
-- The result is RESULT.
Aug 25 11:44:46 ansible-nas systemd[1]: docker.socket: Failed with result 'service-start-limit-hit'.
```

If anymore info is needed I will do my best to provide.

**Comment by FPMilan** [comment]
In my case (Plain Ubuntu 18.04 LTS in a Virtual Box VM) I did not run into this for several times. Try to start a plain new VM.

**Comment by davestephens** [comment]
Given that Ansible-NAS works out of the box with an Ubuntu Server 18.04.x VM, I'm inclined to think this is some dodgy config you've given Docker, perhaps your zpool isn't set up correctly or isn't writeable? It's a little strange Docker is continually trying to restart.

What happens if you set the Docker storage driver back to `overlay2`?

**Comment by animeai** [comment]
You'll need to share the docker daemon logs (look in the /var/logs directory) to give us an idea why the docker service is failing.

**Comment by Micim987** [comment]
I have figured out its some kind of zfs issue. I moved to real hardware and tried to install on the root drive and the installation was successful but when I reinstalled Ubuntu and changed the docker home directory to my zfs pool it is unable to install and throws the errors listed above. Also there are no logs from docker in /var/log

**Comment by Micim987** [comment]
Sorry I guess my comment yesterday disappeared. I was unable to get docker to install the contianers on the zfs pool so I upgraded to a larger disk and just saved the docker containers there. I'm having an issue with samba but I will probably ask on that project. This probably isnt the right solution but its the best one I could come up with. I guess the issue is closed

**Comment by davestephens** [comment]
You didn't answer my question about what Docker storage driver you were using - that will be what is causing your issues.

If your `docker_home` points at a ZFS pool, then `docker_storage_driver` needs to be set to `zfs` accordingly. If `docker_home` points at a ext4 location, then it needs to be set to `overlay2`.

This is documented in the `all.yml.dist` file, along with a link to the official Docker docs of how to set this stuff up. 

Try running Docker on the shell and see what it drops to stdout:

```
sudo /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
```

**Comment by Micim987** [comment]
The driver is set to zfs and I had tried with overlay2 but got the exact same issue
```
INFO[2019-08-28T18:24:51.030083634-04:00] Starting up                                                                      
failed to load listeners: no sockets found via socket activation: make sure the                                            service was started by systemd
```

**Comment by dongennl** [comment]
I have exactly the same problem on a fresh 18.04 (real hardware), with ZFS and either storagedriver 'zfs' (comment says ZFS btw) or 'overlay2'.
Just to be sure the docker folder on zfs has 777 permissions, and I can see it has created the 'data' directory.
I have to move it to a non-ZFS drive to work as well. 
*VERY* frustrated.

**Comment by davestephens** [comment]
Hi @dongennl - please create a new issue and fill in the template provided.
