### ISSUE TITLE
Firefly III - No response

### ISSUE THREAD

**Issue by FPMilan** [davestephens/ansible-nas#120]
**Short problem description**

After installing firefly 3 by enabling it in the playbook (all.yml) it get this when trying to connect via port 8066:
This page isn’t working xxx.xxx.xxx.x is currently unable to handle this request.
HTTP ERROR 500

I've tried it both in a VM locally with several additional services enabled, as well as on aws where I only enabled firefly itself - in both cases the result is the same.

**Environment**
- Ansible-NAS revision (`git rev-parse --short HEAD`): 867441e
- Ansible version (paste the entire output of `ansible --version` on the machine you run the playbook from):

ansible 2.5.1
  config file = /home/ubuntu/ansible-nas/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]

- Ansible-NAS operating system (`cat /etc/lsb-release` on the Ansible-NAS box) - _If this is anything other than Ubuntu 18.04 help will be limited_: DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

- Ansible-NAS kernel (`cat /etc/lsb-release` on the Ansible-NAS box):

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

- Ansible-NAS Python version (`python --version` on the Ansible-NAS box):
Python 2.7.15+
- Ansible-NAS Docker version (`docker --version` on the Ansible-NAS box):

Docker version 19.03.1, build 74b1e89

- Latest Docker logs (`journalctl -u docker.service` on the Ansible-NAS box): on request
- Are you running the playbook from a remote box or the Ansible-NAS box itself?: localhost
- Vagrant version, if testing (`vagrant --version`): no vagrant

**Expected behavior**

see above

**Actual behavior**

see above

**Steps to reproduce**

This happened to me on any fresh install 

**Playbook Output**

na

**Comment by davestephens** [comment]
An HTTP 500 is a server error, IE it's thrown by Firefly rather than
Ansible-NAS, so could be literally anything.

What does the firefly log contain, and what does `docker logs firefly` say?

**Comment by davestephens** [comment]
A PR has been merged that should fix this - please pull master and rerun, and let me know if you still have issues.
