### ISSUE TITLE
Add Calibre-Web

### ISSUE THREAD

**Issue by FPMilan** [davestephens/ansible-nas#124]
This: https://github.com/janeczku/calibre-web

**Comment by wolffstarr** [comment]
Second this. Note there are two "official/supported" Dockers for this as well; Linuxserver.io and Technosoft2000. LSIO supports multiple arches, TS2k does not - it only supports x86-64 - but it defaults to including an ebook conversion library from Calibre, and it will actively pull the latest calibre-web release on container restart.

Probably best to use LSIO for compatibility, but TS2k has its good sides as well.

**Comment by FPMilan** [comment]
That is correct, I would also go for the LSIO Version as you can opt in or out of the conversion.

**Comment by davestephens** [comment]
Looks cool, not something I've seen before!

So... who's gonna do the PR? :-D

**Comment by FPMilan** [comment]
Guess I have to do it  :-D

**Comment by davestephens** [comment]
Closing now #129 is merged. Thanks for the PR :+1:
