### ISSUE TITLE
LDAP Authentication or single logon

### ISSUE THREAD

**Issue by FPMilan** [davestephens/ansible-nas#125]
This is probably on a whole new level but think it would be nice to have (at some point) - especially if the number of services keeps growing. So maybe in Version 2 or something :D

This could be a starting point:
https://spring.io/guides/gs/authenticating-ldap/

I imagine it like this:
A user can create a central account (LDAP) and gets access to all application that the LDAP admin unlocked for him/her.

Or am I the only one who is seeing it?? :P

**Comment by FPMilan** [comment]
I have to give this a bit more thought

**Comment by koenvervloesem** [comment]
Couldn't Traefik be used to add authentication with client certificates? It's far from LDAP authentication, but it's a start...

**Comment by FPMilan** [comment]
I think your right. Maybe like this!? https://docs.traefik.io/v2.0/middlewares/basicauth/

**Comment by koenvervloesem** [comment]
That's for HTTP Basic authentication, which is also an option indeed. Traefik also supports TLS client certificates for authentication: https://docs.traefik.io/v2.0/https/tls/#client-authentication-mtls

And then there's the possibility to forward authentication requests to an external service: https://docs.traefik.io/v2.0/middlewares/forwardauth/

Note that the configuration Ansible-NAS uses is still for Traefik 1.7: https://github.com/davestephens/ansible-nas/pull/132
