### ISSUE TITLE
How to use ansible-nas with zfs on Ubuntu 18

### ISSUE THREAD

**Issue by tetrar124** [davestephens/ansible-nas#127]
I want to use this amazing tool. 

I used zfs on Ubuntu 18 for making shared folders, but ansible-nas overwrote the shared zfs folders after running.
Therefore, I mounted shared zfs folders, secondly, I used ansible-nas.

But when I unmounted the zfs folders, I could not mount the zfs folders because of the directories was not empty with folders generated by ansible-nas.

```
zfs
/tank
/tank/video/
/tank/music/

ansible nas
/tank/video/
/tank/music/
/tank/docker/
/tank/download/
```

What should I do the case of combining zfs and ansible-nas on the same folders?

**Comment by davestephens** [comment]
Ansible-NAS won't "overwrite" anything, it will simply create the directories you've specified in your all.yml if they don't already exist. 

Ansible-NAS also doesn't care if you use zfs, xfs, ext4 etc - it will just use (and create) the paths you configure it to.

Therefore, you need to have your zfs config in place and mounted *before* you run Ansible-NAS, then your created zfs mounts will be used. 

My guess is you ran Ansible-NAS when your zfs pool wasn't mounted, then when you've tried to mount it you can't as zfs expects an empty directory to mount to.

To fix it, clear the directories, mount your zfs pool, then run Ansible-NAS again.

**Comment by tetrar124** [comment]
Dear davestephens,

I restarted my ubuntu machine and zfs folders were mounted automatically.
But it needed the command of "zfs mount" and/or "zpool import" before reboot
(The not empty error occurred during this command, but mount commands become effective after reboot).

Thank you for your cooperations.
 
Sincerely,

**Comment by davestephens** [comment]
Glad you got it sorted :+1:
