### ISSUE TITLE
Option to use Traefik with self-signed wildcard certificate

### ISSUE THREAD

**Issue by koenvervloesem** [davestephens/ansible-nas#128]
**Is your feature request related to a problem? Please describe.**

I need to configure Ansible-NAS to use Traefik with a self-signed wildcard certificate for local domain names instead of a Let's Encrypt certificate.

See **Additional context** for why I need this (access restricted to my local network) and how I implemented this.

**Describe the solution you'd like**

Currently, when you have `traefik_enabled: true` in `group_vars/all.yml`, Traefik is configured to use Let's Encrypt. I want to separate these two services so I can use Traefik with my own self-signed certificate.

For the sake of backwards compatibility, the default behaviour can stay like it is now: `traefik_enabled: true` enables Traefik and configures it with Let's Encrypt. If you want to use your own certificates, then that should be possible with extra options in the Traefik section in `group_vars/all.yml`, like:

```
###
### Traefik
###
traefik_docker_image: traefik:latest
traefik_data_directory: "{{ docker_home }}/traefik"
traefik_debug: "true"
traefik_tls_certificate: "{{ traefik_data_directory }}/cert.pem"
traefik_tls_key: "{{ traefik_data_directory }}/key.pem"
```

When these options are defined, the Traefik task in `tasks/traefik.yml` should install another `traefik.toml`than the current one, without the `[acme]` section and with the certificate and key files from `group_vars/all.yml` set up for the `https` entry point, like this:

```
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    [entryPoints.httpSSL.tls.defaultCertificate]
      certFile = "/etc/traefik/cert.pem"
      keyFile = "/etc/traefik/key.pem"
```

I can probably create a PR for this if you're OK with this approach. I can also document my setup (in **Additional context**) for anyone who wants to do the same.

**Describe alternatives you've considered**

I haven't considered any other alternatives. This solution looks like the most natural way.

**Additional context**

Traefik is awesome so I can use a subdomain for all my services, but I don't want to expose them to the internet. So I'd like to get the same experience that Traefik and Cloudflare DDNS give, but with access restricted to my local network.

The solution that I implemented recently and that has been working fine now for more than a few weeks, is the following:

- My local DNS server (Unbound) gives every host on my local network a `foobar.home` hostname, so e.g. `ansible-nas.home` for my Ubuntu Server machine running Ansible-NAS.
- In my DNS server I configured a 'host override' that resolves every possible subdomain `*.ansible-nas.home` to the IP address of `ansible-nas.home`. This essentially mimics Cloudflare's wildcard DNS entries, but for my local domain.
- In my router operating system (OPNsense) I created my own certificate authority (which I import in my web browsers that I use to access the services), and created a wildcard certificate `*.ansible-nas.home` (with `subjectAltName=DNS:*.ansible-nas.home,DNS:*.ansible-nas`).
- With these preparatory steps, to my surprise the only thing I had to do to make Traefik work with my own certificates, was deleting the `[acme]` section in `traefik.toml` and adding the certificate and key file in the `https` entry point.

So now I can visit https://heimdall.ansible-nas.home, https://bitwarden.ansible-nas.home and so on on my local network with a TLS encrypted connection, with a certificate signed by my own trusted CA. Pretty cool :-)

**Comment by bcurran3** [comment]
I have an alternative method that works for me and should work well for others accomplishing the same goal. It involves Traefik's whitelisting capability. To use it requires adding new labels to all the programs so I'm waiting until PRs get caught up before submitting it.

Here's the basic implementation:
define a WAN variable as 0.0.0.0/0
define a LAN variable with the CIDR scope of your LAN plus the Le'ts Encrypt domain IP. 
add whitelist as the LAN
enable external true to for all apps than use whitelist with the variable for LAN or WAN

End result is (almost) all apps available via subdomain on your LAN with Let's Encrypt certs and the ones you define as WAN accessible can be used from anywhere on the Internet.

I've been using this for a couple months and am very happy with it. Itching to get the PR in....

**Comment by koenvervloesem** [comment]
Yes, but that's still using Let's Encrypt, which I wanted to avoid. Anyway, after this issue I implemented an alternative in https://github.com/davestephens/ansible-nas/pull/162 with a self-hosted CA and ACME server (so still without using Let's Encrypt), which I find much more flexible. But even after my efforts to make this work with Ansible-NAS and tidy up the PR after David's comments, it hasn't been merged yet. And because the Ansible-NAS code has changed a lot since then, merging it now will require more efforts that I probably won't going to make anymore.

So yes, your PR will be a nice addition, but not for the same goal, as my goal was to avoid using Let's Encrypt.

**Comment by davestephens** [comment]
Closing as LetsEncrypt works fine - if there's demand for using a self-signed CA I'd happily look at a PR if someone wants to integrate with Traefik2.
