### ISSUE TITLE
Firefly / Traefik external port incorrect

### ISSUE THREAD

**Issue by martinfiers** [davestephens/ansible-nas#131]
The firefly application doesn't seem to work out of the box.

After some playing around I made a bit of progress, but not yet working. 

1. Using default configuration: I get an empty page when browsing to the URL. The logs mention something about a

> RuntimeException: No application encryption key has been specified.

2. I noticed the configuration file in tasks/firefly.yml uses FF_ prefixes for the environment variables. But that won't work, right? When I remove the FF_ prefix, the behavior is different. Now instead of a blank page I get a page mentioning 'whoops, there was a fatal error, please check logs' (I would think: progress :)). The log is now mentioning this: 

> In PDOConnection.php line 27:
>  SQLSTATE[HY000] [1045] Access denied for user ''@'172.17.0.10' (using password: YES)                                                                    

So question, has firefly already worked out-of-the box? Or are there some extra steps to be taken? (the documentation is not mentioning something specifically).

Thanks!

**Comment by martinfiers** [comment]
Some more issues I found: 
* by default a postgresql database is used for firefly (https://docs.firefly-iii.org/en/latest/installation/docker.html). I would think it's maybe easiest (configuration-wise) to also use a postgresql docker container? When I try this I get some other errors (so still not working though)
* Also, the traefik.port is wrong I think, but I'm not yet sure what should be the correct one (still experimenting)

**Comment by davestephens** [comment]
> So question, has firefly already worked out-of-the box? Or are there some extra steps to be taken? (the documentation is not mentioning something specifically).
Yes, it works fine - I wouldn't have committed it otherwise ;-)

The environment variables were changed a month or so back - I think you need to pull the latest from master. See https://github.com/davestephens/ansible-nas/blob/master/tasks/firefly.yml.

**Comment by martinfiers** [comment]
I think I have it working now. I did use a postgresql docker container. Summary of changes that made it work for me:

* change to pgsql container (postgres:10). 
* changed env for the firefly container: I use DB_HOST (db), DB_CONNECTION (pgsql), DB_DATABASE (firefly), DB_USERNAME (firefly), DB_PASSWORD (same password as set in the postgres container), DB_PORT (5432), and I also set TRUSTED_PROXIES (in case you want reverse proxy to work).

**Comment by davestephens** [comment]
I'm not sure these changes are required, did you test with the latest code from master?

**Comment by martinfiers** [comment]
Ah; no I didn't. Ok, I will test with the latest changes, thanks for notifying. I'll let you know if that works.

**Comment by martinfiers** [comment]
Ok, with the latest code from master I can run firefly locally! Not from external yet. some traefik config issue still.

**Comment by martinfiers** [comment]
Agreed that you don't want this to be exposed (except maybe for some testing/experimenting remotely). In that case I'd put a warning / hint in the group_vars/all.yml file, sth like "don't expose this port unless you really want to, this is your personal financing, after all".
