### ISSUE TITLE
Jellyfin(Emby Open Source Clone) plugin request

### ISSUE THREAD

**Issue by ThoreauHenry** [davestephens/ansible-nas#134]
A simple request, when you can get around to it.  Could you take a look at Jellyfin and see if it's in a mature enough state to import as a plugin.  Thank you.

https://github.com/jellyfin/jellyfin

Some background on it.

https://youtu.be/QuNLbAtMFsk

**Comment by CherryKitten** [comment]
There already is a pull request for this at #123

**Comment by bcurran3** [comment]
@ThoreauHenry - see https://github.com/davestephens/ansible-nas/issues/70. You might want to upvote that one and close this one as a duplicate. :)

**Comment by davestephens** [comment]
Closing, dupe of #70
