### ISSUE TITLE
(docker) docker-ce vs docker.io and package vs snap install

### ISSUE THREAD

**Issue by bcurran3** [davestephens/ansible-nas#143]
I keep getting this error when I run the playbook.

> TASK [geerlingguy.docker : Install Docker.] ************************************
> fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'docker-ce' is available"}

It could be because I'm running/testing on Ubuntu Server 19.10 “Eoan Ermine” ~ a week before release... and I'm new to playing with docker. I'm confused if it should be docker.io installed instaled of docker-ce or not. Some looking around shows that I guess it SHOULD be docker-ce (https://docs.docker.com/install/linux/docker-ce/ubuntu/) but US 19.10 has docker.io instead. Maybe there should be some logic to try docker.io if docker-ce fails? Maybe this will become null and void after Thursday when the official release of Ubuntu Server 19.10 is out. Dunno.

> docker.io/eoan,now 19.03.2-0ubuntu1 amd64 [installed,automatic]
>   Linux container runtime

Of course Ubuntu also has docker as a snap, and that is how I've installed it.

Any thoughts about if docker is better as a snap or as a normally installed program in relation to Ansible-NAS?

All thoughts and comments welcome as I'm hoping to go live with my Ansible-NAS this coming weekend.

**Comment by koenvervloesem** [comment]
The [requirements](https://github.com/davestephens/ansible-nas#requirements) of Ansible-NAS say:

> Ansible NAS targets the latest Ubuntu LTS release, which is currently Ubuntu Server 18.04.2 LTS.

So if you proceed with Ubuntu Server 19.10, you will likely bump into some other problems.

**Comment by davestephens** [comment]
Yep, @koenvervloesem is right, you should be using 18.04 LTS. We'll switch to 20.04 LTS next year. Interim releases are only supported by Canonical for 9 months, whereas LTS releases are supported for 5 years. 

Interim releases aren't (and won't) be supported due to the large amount of work required for niggly issues such as this one.

**Comment by bcurran3** [comment]
Got it.

**Comment by bcurran3** [comment]
Good news is I re-imaged to 18.04 LTS and after using the alternate install got it working fine. Yeah me!
