### ISSUE TITLE
Add netbootxyz PXE server

### ISSUE THREAD

**Issue by bcurran3** [davestephens/ansible-nas#146]
I have no idea which docker is best, but a PXE server would be a worthwhile addition to Ansible-NAS.

https://hub.docker.com/search?q=pxe&type=image

**Comment by davestephens** [comment]
Interesting suggestion, what are the use cases?

**Comment by bcurran3** [comment]
Imaging computers!

Also fun stuff like booting Chromium, Androidx86, and various Linux live CDs over the network, AV boot CDs, PiNG, and etc.

**Comment by bcurran3** [comment]
This popped up in my reading list the other day and thought I'd cross reference it back here:
https://blog.linuxserver.io/2019/12/16/netboot-xyz-docker-network-boot-server-pxe/

I'm planning on doing an PR and adding one of these PXE servers in the future. I want to get one other possibly simpler task done first.

**Comment by bcurran3** [comment]
I've had netbootxyz added to my ansible-nas for awhile. I'll do a PR hopefully soon.
