### ISSUE TITLE
Add Ubooquity (comic book server) docker container support

### ISSUE THREAD

**Issue by bcurran3** [davestephens/ansible-nas#148]
Ubooquity is a cool comic book server I've been using for years. Time for me to get it off my Windows app server and onto my forthcoming Ansible-NAS server. :) I think this is another worthwhile program container to add support for.

https://hub.docker.com/search?q=UBOOQUITY&type=image

**Comment by FPMilan** [comment]
Hi @bcurran3 - you might want to give this a look https://github.com/janeczku/calibre-web it is quite similar to your suggestion and truly open-source

**Comment by bcurran3** [comment]
@FPMilan - Thanks. I'm pretty sure I looked at that in the past. Fact is though, I'm just not a Calibre fan. 

From a couple previous comments here I'm starting to feel that there is a strong preference on FOSS here. I love FOSS. I have nothing against FOSS. I just don't have a requirement of FOSS. I'll just use the best tool to do the job. Sometimes that "best" is subjective. Ubooquity is best for me (at least without doing a 3-4 year follow up on Calibre). I'm also always for freedom of choice and actually having choices. Ansible-NAS isn't my project of course, but IMHO I think every category of program should have two choices to use; the first being whatever is most popular of course. Sometimes there's just comfort in using what you're used to. :)

**Comment by davestephens** [comment]
Hi @bcurran3 - not at all, but if there are two almost-identical products (eg as is the case in #151) where one is OS, the OS one will be picked. 

I think @FPMilan pointed out Calibre as he recently contributed #129. nothing more :)

**Comment by FPMilan** [comment]
@bcurran3 Totally understand your approach! 
Me personally am trying to use software that not necessarily is OS but that is actively maintained to reduce security concerns when exposing them to the internet.

**Comment by jesse-troy** [comment]
I've been running this in a container for about a year now and it's pretty great. I'll try and add this to the project this week if I get some time.

**Comment by bcurran3** [comment]
I believe this issue is now done and can be closed.
