### ISSUE TITLE
Add pyTiVo docker container support

### ISSUE THREAD

**Issue by bcurran3** [davestephens/ansible-nas#149]
I have not tried any of the pytivo dockers but will investigate and report back in the future. It is a program I use semi-regularly (Plex has started to replace it in my environment.) on my Windows app server and would like to move to my Ansible-NAS.

https://hub.docker.com/search?q=pytivo&type=image

**Comment by davestephens** [comment]
Looks interesting! 

Looks like there's no official Docker image though, and the x64 image was last built ~3 years ago. Would need someone to work out that issue first, perhaps by petitioning the devs to maintain a Dockerfile / build process...

**Comment by bcurran3** [comment]
I don't have any hope of that. Original developer abandoned 13 years ago:
https://github.com/armooo/pytivo

Forked and popularized by William McBrine:
https://github.com/wmcbrine/pytivo
and not updated in a year and a half. It's pretty stable and probably not much that can be done to improve it.

Another fork from William McBrine's fork that I used for years but hasn't been updated for about three years:
https://github.com/lucasnz/pytivo

Currently I use this all-in-one package (has Python etc included in the installer):
http://www.pytivodesktop.com/

This container states it's using William McBrine's fork and two years old so it's a little older that WMB's last release. What throws me is it says "built on Fedora 25."
https://hub.docker.com/r/acathrow/aic-pytivo

I actually maintain all three packages for Chocolatey. :)

I will test these out and report back my findings in the "near" future. 

Unless you feel strongly that this has to be an official docker image from the developer, please leave this open for my findings and still consideration in the future.

**Comment by davestephens** [comment]
Doesn't *need* to be official, but a maintained Docker image with some
users would be preferable. Eg we use a lot of the Linuxserver ones, they're
looked after by the Linuxserver guys and have a lot of users.

**Comment by bcurran3** [comment]
The PR for this has been submitted.

I'm now happily using it at home.
