### ISSUE TITLE
Add openHAB (home automation) docker container support

### ISSUE THREAD

**Issue by bcurran3** [davestephens/ansible-nas#150]
openHAB is a vendor and technology agnostic open source automation software for your home. This is an alternative (or vice-versa) to Home Assistant that recently got added to Ansible-NAS.

https://hub.docker.com/search?q=openhab&type=image

**Comment by davestephens** [comment]
Covered in #112, just not tested/merged yet.

**Comment by davestephens** [comment]
Fixed by #112
