### ISSUE TITLE
ENHANCEMENT: Add ownCloud (self-hosted file sync and share platform) docker container support

### ISSUE THREAD

**Issue by bcurran3** [davestephens/ansible-nas#151]
With NextCloud already on the list, it seems that ownCloud should be a choice as well.

https://hub.docker.com/search?q=owncloud&type=image

**Comment by davestephens** [comment]
I chose Nextcloud over Owncloud as there is proprietary code in Owncloud, and you have to pay for features in Owncloud that you get for free in Nextcloud. 

Additionally Nextcloud is a fork of the Open Source code of Owncloud by the original Owncloud developer, so there seems to be no good reason to require Owncloud, or both Nextcloud and Owncloud. 

Feel free to re-open this if there's a good reason I've missed...
