### ISSUE TITLE
Add  Cockpit (web-based system management)

### ISSUE THREAD

**Issue by bcurran3** [davestephens/ansible-nas#152]
REF: https://cockpit-project.org/

I'd like to suggest adding this to the base # System Management install along with:
```
heimdall_enabled: true
portainer_enabled: true
glances_enabled: false
stats_enabled: false
guacamole_enabled: false
netdata_enabled: false
watchtower_enabled: false
cloudflare_ddns_enabled: false
```

I tested it over the last few days in my AN pre-run and like it.

If adopted and liked, POSSIBLY could be used as the basis for documentation on setting up drives and partitions.

This write up led me to it:
https://www.how2shout.com/tools/ubuntu-server-web-gui.html

Haven't tried it, but VestaCP might be worth checking out too.
Webmin used to be good, but I believe it's fallen in disfavor these days over the v1.890 security issue. I'm sure lots of people still use it.

**Comment by davestephens** [comment]
I have to be honest, installing something like this that sticks it fingers into all of the proverbial pies whilst running as root doesn't exactly fill me with joy. 

The idea of Ansible-NAS is that it's modular through Docker containers, with only the absolute essentials installed through the system package manager. (IE samba, docker, NFS etc). 

There are a few reasons for this:
- Ubuntu upgrades are trivial
- Adding/removing software is trivial (start/stop container)
- We're not at the mercy of package maintainers to keep stuff running
- Everything can be managed through Portainer

Ansible-NAS is a tinkerers project - if a user doesn't have at least a base level of system knowledge, then it's likely not the project for them to use. Therefore, I'd question the worth of installing a web interface for system management? 

If people want to install it themselves then I really don't have a problem with that (and it's not something I can control!), but I'd argue that having it installed OOTB is out of scope of Ansible-NAS.

**Comment by bcurran3** [comment]
I understand your thinking, BUT aren't

heimdall_enabled: true
portainer_enabled: true
glances_enabled: false
stats_enabled: false
guacamole_enabled: false
netdata_enabled: false
watchtower_enabled: false
cloudflare_ddns_enabled: false

installed via apt? 

This could be just another apt install OOTB and defaulting to false.

And yes, I completely agree it is a very simple install but think it's a worthwhile addition to AN.

It CAN be containerized. (For whatever reason, I just have this personal gut feeling that I don't want it in docker for me - but that could completely change after using it via docker.)
https://hub.docker.com/search?q=cockpit&type=image

**Comment by davestephens** [comment]
No, they're all Docker containers - as above everything is a Docker container except the bare essentials  - do a search in the codebase for any of the parameters you've mentioned above and you'll see how it works. 

There is a `ansible_nas_extra_packages` parameter in `all.yml` where you can add stuff you want installed via apt.

**Comment by davestephens** [comment]
Closing unless the cockpit people produce a usable Docker container.
