### ISSUE TITLE
Add FileBot docker support

### ISSUE THREAD

**Issue by bcurran3** [davestephens/ansible-nas#154]
https://hub.docker.com/r/rednoah/filebot
https://www.filebot.net/

This is "must have app" for all Plex Media Server users. I use the normal install-able program on a regular basis. I have not experienced it as a docker image yet, but I shall soon...

NOTE: the program recently became trialware after v4.7.9 (v4.8.2 I believe) so v4.7.9 would probably be the preferred version for most people. Personally I have a license as the author will give a free 1 year renewable license to open source developers.

**Comment by davestephens** [comment]
Isn't this a GUI app? Or am I missing something?

**Comment by bcurran3** [comment]
All I know at the moment is

> filebot-node
> FileBot Node allows you to call the amc script via a simple web interface.
> 
> docker run --rm -it -v $PWD:/volume1 -v data:/data -p 5452:5452 rednoah/filebot:node
> Once the FileBot Node Service is running, you can access the web interface via http://localhost:5452/filebot/. You can create prepared tasks via Execute ➔ Schedule and then execute them remotely via curl http://localhost:5452/task?id=${TASK_ID}.
> 
> You may secure the FileBot Node Service by using HTTPS and BASIC authentication:
> 
> docker run --rm -it -v $PWD:/volume1 -v data:/data -p 5452:5452 -e FILEBOT_NODE_AUTH=BASIC -e FILEBOT_NODE_AUTH_USER=alice -e FILEBOT_NODE_AUTH_PASS=wxy87rFb -p 5453:5453 -v /etc/ssl:/etc/ssl:ro -e FILEBOT_NODE_HTTPS=YES -e FILEBOT_NODE_HTTPS_PORT=5453 -e FILEBOT_NODE_HTTPS_KEY=/etc/ssl/private/server.key -e FILEBOT_NODE_HTTPS_CRT=/etc/ssl/certs/server.crt rednoah/filebot:node
> filebot-watcher
> The filebot-watcher command-line tool watches a given folder and executes the amc script on newly added files.
> 
> docker run --rm -it -v $P

It was an accident and complete surprise that I found it in docker and from the actual developer (alias RedNoah). This web interface version of it is brand new news to me. I'll be tested it "soon"; i..e after I setup AN with all the normal supported production stuff.

**Comment by davestephens** [comment]
Isn't renaming handled by pretty much every library processor already? eg Coachpotato will download, rename, get subs etc. I mean I don't have a problem with including this if someone wants to do a PR for it, but I'm pretty sure most functionality is already covered elsewhere.

**Comment by bcurran3** [comment]
Not really sure, I don't use any of those. :)

**Comment by bcurran3** [comment]
I've got this 99% done. I just need to add an option to handle the license key.
