### ISSUE TITLE
Docker configuration

### ISSUE THREAD

**Issue by jcouser** [davestephens/ansible-nas#160]
OS: Ubuntu Server 18.04.3 LTS

I must be missing something.

After running the playbook everything appears to be running as expected.  After a reboot,  Services were still running and accessible via their ports, but `sudo docker ps/images` was empty post-reboot as if the host machine is unawre of the docker images that are currently running.

ps aux shows a `docker-proxy` running for each service with it's respective container-ip and container-port, but I'm not quite sure how to access the containers.  I have portainer running as well setup for local mode, but after the reboot it's unable to see any running containers.  Everything appears to be running, but it's unclear how I can access the running docker images.  So it appears things are running, but in some docker proxy configuration that I'm unaware of with portainer unable to manage the running containers.  Any insight into this would be helpful.

Thanks.

**Comment by davestephens** [comment]
`docker ps` will show you what's running, I'm not sure where you got the extra `/images` from? If you didn't set your username in `all.yml` then your user won't have been added to the `docker` group and you'll need to prefix the command with sudo. 

Maybe have a read of [this]https://dzone.com/articles/top-docker-commands-itsyndicate) and, do some research into how Docker and chrooted environments work.
