### ISSUE TITLE
Install failure- Docker issue

### ISSUE THREAD

**Issue by nedWilliams** [davestephens/ansible-nas#166]
I have been running into a issue when executing the playbook for setup.  I get the following:

TASK [geerlingguy.docker : Ensure Docker is started and enabled at boot.] *************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to start service docker: Job for docker.service failed because the control process exited with error code.\nSee \"systemctl status docker.service\" and \"journalctl -xe\" for details.\n"}

PLAY RECAP ****************************************************************************************************
localhost                  : ok=24   changed=0    unreachable=0    failed=1    skipped=16   rescued=0    ignored=0   

running the following: systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2019-11-30 05:16:54 UTC; 6s ago
     Docs: https://docs.docker.com
  Process: 5163 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, 
 Main PID: 5163 (code=exited, status=1/FAILURE)

Nov 30 05:16:54 XXX-nas systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Nov 30 05:16:54 XXX-nas systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
Nov 30 05:16:54 XXX-nas systemd[1]: Stopped Docker Application Container Engine.
Nov 30 05:16:54 XXX-nas systemd[1]: docker.service: Start request repeated too quickly.
Nov 30 05:16:54 XXX-nas systemd[1]: docker.service: Failed with result 'exit-code'.
Nov 30 05:16:54 XXX-nas systemd[1]: Failed to start Docker Application Container Engine.

Suggestions?

**Comment by davestephens** [comment]
Please fill out the template in the bug report, there's a lot of info I need to know to be able to help you. This will also help the next person that runs into this. 

It sounds like a Docker config issue. I'm guessing there's some permutation of storage driver and paths that doesn't work that we're not catching.

**Comment by nedWilliams** [comment]
Sorry about the lack of info before.  Running  on the Ansible-NAS box itself. Latest LTS Ubuntu, with all updates. Storage drive is formatted btrfs

Docker version 19.03.5, build 633a0ea838

XXX-nas systemd[1]: Failed to start Docker Application Container Engine.
Dec 01 05:22:36 XXX-nas systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Dec 01 05:22:36 XXX-nas systemd[1]: docker.service: Scheduled restart job, restart counter is at 2.
Dec 01 05:22:36 XXX-nas systemd[1]: Stopped Docker Application Container Engine.
Dec 01 05:22:36 XXX-nas systemd[1]: Starting Docker Application Container Engine...
Dec 01 05:22:36 XXX-nas dockerd[19486]: time="2019-12-01T05:22:36.322207303Z" level=info msg="Starting up"
Dec 01 05:22:36 XXX-nas dockerd[19486]: time="2019-12-01T05:22:36.322797618Z" level=info msg="detected 127.0.0.53 nameserver, assuming systemd-resolved, so using resolv.c
Dec 01 05:22:36 XXX-nas dockerd[19486]: time="2019-12-01T05:22:36.324355156Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Dec 01 05:22:36 XXX-nas dockerd[19486]: time="2019-12-01T05:22:36.324428263Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Dec 01 05:22:36 XXX-nas dockerd[19486]: time="2019-12-01T05:22:36.324479118Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/container
Dec 01 05:22:36 XXX-nas dockerd[19486]: time="2019-12-01T05:22:36.324507421Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Dec 01 05:22:36 XXX-nas dockerd[19486]: time="2019-12-01T05:22:36.327571442Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Dec 01 05:22:36 XXX-nas dockerd[19486]: time="2019-12-01T05:22:36.327623309Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Dec 01 05:22:36 XXX-nas dockerd[19486]: time="2019-12-01T05:22:36.327658224Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/container
Dec 01 05:22:36 XXX-nas dockerd[19486]: time="2019-12-01T05:22:36.327689022Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Dec 01 05:22:36 XXX-nas dockerd[19486]: failed to start daemon: error initializing graphdriver: prerequisites for driver not satisfied (wrong filesystem?)
Dec 01 05:22:36 XXX-nas systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Dec 01 05:22:36 XXX-nas systemd[1]: docker.service: Failed with result 'exit-code'.
Dec 01 05:22:36 XXX-nas systemd[1]: Failed to start Docker Application Container Engine.
Dec 01 05:22:38 XXX-nas systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Dec 01 05:22:38 XXX-nas systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
Dec 01 05:22:38 XXX-nas systemd[1]: Stopped Docker Application Container Engine.
Dec 01 05:22:38 XXX-nas systemd[1]: docker.service: Start request repeated too quickly.
Dec 01 05:22:38 XXX-nas systemd[1]: docker.service: Failed with result 'exit-code'.
Dec 01 05:22:38 XXX-nas systemd[1]: Failed to start Docker Application Container Engine.

Filesystem      Size  Used Avail Use% Mounted on
udev            6.8G     0  6.8G   0% /dev
tmpfs           1.4G  3.1M  1.4G   1% /run
/dev/nvme0n1p2  234G  9.0G  213G   5% /
tmpfs           6.9G   51M  6.8G   1% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           6.9G     0  6.9G   0% /sys/fs/cgroup
/dev/nvme0n1p3  502M  6.1M  496M   2% /boot/efi
tmpfs           1.4G   48K  1.4G   1% /run/user/1000
/dev/sda2       977G   17M  975G   1% /media/XXX/173b403b-c928-4142-86f4-081062f87f94

all.yml vars:
docker_image_directory: "{{ docker_home }}/data"
docker_home: /mnt/Volume2/docker
docker_storage_driver: overlay2
samba_shares_root: /mnt/Volume3

**Comment by davestephens** [comment]
Is all of your storage btrfs?

[Each Docker storage driver has different compatibility with different filesystems](https://docs.docker.com/storage/storagedriver/select-storage-driver/#supported-backing-filesystems). The output of `df -hT` and `mount` would help to know for sure, but I'm guessing that's your issue based on the log:

```
Dec 01 05:22:36 XXX-nas dockerd[19486]: failed to start daemon: error initializing graphdriver: prerequisites for driver not satisfied (wrong filesystem?)
```

Read the doc linked above and select the storage driver relevant to the underlying filesystem and you should be good to go. I'm guessing for you that's `btrfs`.

Out of interest, why btrfs over ZFS? You will likely find ZFS better performing and using less space overall (lz4 by default) than btrfs.

**Comment by davestephens** [comment]
Going to close this, feel free to re-open if required :+1:
