### ISSUE TITLE
Grafana container execution errors

### ISSUE THREAD

**Issue by C-J1** [davestephens/ansible-nas#17]
The Grafana gets created, but fails to fully launch. Container logs shows:

```
GF_PATHS_DATA='/var/lib/grafana' is not writable.,
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later,
mkdir: cannot create directory '/var/lib/grafana/plugins': Permission denied
```

The referenced URL mentions some major changes to how storage is handled from grafana version 5.1 and above. The recommended solution is to use a docker volume instead of bind mountpoints. Seeing as the whole docker directory has been moved over a custom location, it probably isn't a big deal to use a volume.

I'll work up a fix and raise a PR.

Regards,

CJ

**Comment by C-J1** [comment]
Using a volume fixed the start issue, but looks like there is still a permissions issue on the provisioning directory.

`t=2018-11-12T06:36:42+0000 lvl=eror msg="can't read dashboard provisioning files from directory" logger=provisioning.dashboard path=/etc/grafana/provisioning/dashboards`

Is it worth creating the grafana user on the host (with id 472) and chown'ing the relevant folders?

**Comment by davestephens** [comment]
The issue is that the container now runs as user 472, so can't read the local filesystem. My latest commit permissions the filesystem to the right user and Grafana starts cleanly. 

Let me know if this is still an issue for you!
