### ISSUE TITLE
Port conflict when enabling `portainer` and `thelounge`

### ISSUE THREAD

**Issue by JoyceBabu** [davestephens/ansible-nas#177]
Portainer and The Lounge both listens on port `9000`, causing the task `The Lounge Docker Container` to fail.

Can you add a new variable for changing the port of `The Lounge`?

**Comment by animeai** [comment]
Fixed with #178

**Comment by bcurran3** [comment]
The same is true for Logitech Media Server.

I propose ports for all containers should be defined as variables in all.yaml as a standard.

See my comment in https://github.com/davestephens/ansible-nas/issues/145

**Comment by animeai** [comment]
188 should be good to merge as soon as I test it on a vm now I've made the changes needed to the PR for the new style config files.

**Comment by davestephens** [comment]
Fixed by #188, all ports are now user-configurable. 🎉🎉
