### ISSUE TITLE
RFC: all.yml Application Categories

### ISSUE THREAD

**Issue by davestephens** [davestephens/ansible-nas#179]
The categories for applications in `all.yml` have got a bit out of whack, resulting in them either not being used, or people simply naming them the same as the application underneath them.

eg:
```
# Media Sourcing
sonarr_enabled: false
sickchill_enabled: false

# IRC
znc_enabled: false
thelounge_enabled: false

# Jellyfin
jellyfin_enabled: false

# minidlna
minidlna_enabled: false
```

I'd want to tidy this up but would like to receive some ideas of how we can best categories applications that already exist, and may be added in the future.

To get started:

- Media Sourcing
- Media Streaming
- System Management
- Software Development
- Backup and Restore
- Home Automation
- Downloading

Any thoughts or suggestions?

**Comment by bcurran3** [comment]
I upvote this and planned on doing same.

SUGGESTIONS:
Change Media Streaming to **Media Servers** due to PyTivo serves media to copy to TiVos and Ubooquity serves comics and e-books for reading in a browser. Both are servers but do not offer streaming.

**Media Management** might be a small but useful category in the future when I add FileBot (99% done - needs testing) and possibly for Mylaar (haven't looked at it yet).

**Blogging** or **Publishing** should be a category as since WordPress is most likely going to get added soon. I'm sure other self publishing programs will show up as people will want to host their own website on their NAS.

**Comment by animeai** [comment]
This is from my testing version, thre are a few containers I'm working on here that aren't in the main repo yet:
```

### Backup & Restore
duplicati_enabled: "false"
nextcloud_enabled: "false"
timemachine_enabled: "false"

### Content Management Systems, Wiki, Git and Blogs
joomla_enabled: "false"
dokuwiki_enabled: "false"
gitea_enabled: "false"

### Downloading
# If you plan to use Transmission with OpenVPN, you'll need to copy group_vars/vpn_credentials.yml.dist
# to group_vars/vpn_credentials.yml, then update it with your own settings.
nzbget_enabled: "false"
pyload_enabled: "false"
transmission_enabled: "false"
transmission_with_openvpn_enabled: "false"

### EBooks
calibre_enabled: "false"

### IRC
znc_enabled: "false"
thelounge_enabled: "false"

### Finance
firefly_enabled: "false"

### Games
minetest_enabled: "false"

### Home Automation
homeassistant_enabled: "false"
mosquitto_enabled: "false"
homebridge_enabled: "false"
openhab_enabled: "false"

### Media Management and Distribution
emby_enabled: "false"
htpcmanager_enabled: "false"
jellyfin_enabled: "false"
minidlna_enabled: "false"
plex_enabled: "false"
tautulli_enabled: "false"

### Media Sourcing
bazarr_enabled: "false"
couchpotato_enabled: "false"
get_iplayer_enabled: "false"
jackett_enabled: "false"
radarr_enabled: "false"
sickchill_enabled: "false"
sonarr_enabled: "false"

### Music
airsonic_enabled: "false"
beets_enabled: "false"
mymediaforalexa_enabled: "false"

### News
miniflux_enabled: "false"

### Password Management
bitwarden_enabled: "false"

### System Management
cloudcmd_enabled: "false"
cloudflare_ddns_enabled: "false"
docker-autoheal_enabled: "false"
glances_enabled: "false"
guacamole_enabled: "false"
heimdall_enabled: true
netdata_enabled: "false"
portainer_enabled: true
stats_enabled: "false"
watchtower_enabled: "false"

### Webtools
wallabag_enabled: "false"
```
That's how I cleaned it up a bit, but there are still quite a few categories there

**Comment by bcurran3** [comment]
I know this has been worked on a bit.... but it could still use some more work.

Some notable things that bring out the OCD in me:
- "Media Serving" IMHO really should be "Media Servers"
- Tautulli is not a media server, it's an management add-on for Plex - maybe should be classified as "Media Server Utilities"
- minidlna is a media server, not for media sourcing
- jelyfin is a media server, not for sourcing
- emby is a media srever, not for sourcing
- ombi is not technically for media sourcing, it's more for a media server utility
- airsonic and mymediaforalexa, I THINK (don't use), are both media servers...yes, related to music (but so is Plex!...and forthcoming LMS)
- NextCloud is not backup and restore, it's cloud storage
- Ubooquity is media server
- Joomla and SEO probably should have a catagory such as "Web Hosting" especially once WordPress hits ansible-nas. Though I'm not really sure what serposcope actually does...
- "Books" - well I'd argue that Calibre is not in ansible-nas, Calibre-web is... it would be a media server

I'm willing to implement if the general consensus is a thumbs up.

**Comment by davestephens** [comment]
Not relevant now that tasks are being moved into roles, and the playbook being structured more sensibly.
