### ISSUE TITLE
NOT AN ISSUE: (FYI) a curated comprehensive reference list of self hosted possibilities

### ISSUE THREAD

**Issue by bcurran3** [davestephens/ansible-nas#206]
From project awesome, a curated list of self hosted applications.

ansible-nas is even on the list under Self-hosting Solutions.

https://project-awesome.org/Kickball/awesome-selfhosted

Gentleman, start your PRs. 

![](https://i.kym-cdn.com/photos/images/newsfeed/001/193/375/5f7.jpeg)

**Comment by davestephens** [comment]
Useful info. Ansible-NAS is actually already listed on there under "complete solutions".

**Comment by bcurran3** [comment]
Reading comprehension error #1 - you missed that I stated that ansible-nas was listed and where.
Reading comprehension error #2 - ansible-nas is not listed where you state it is.

**Comment by davestephens** [comment]
There is one of me, 604 of you (as I type - it's going up daily) - therefore it is entirely possible that I misread issues, especially ones prefixed "NOT AN ISSUE".

**Comment by bcurran3** [comment]
Three sentences with <30 cumulative words. 

So the PURPOSE of the issue was to share the list of POSSIBILITIES for ansible-nas in the future with to the masses. Could help people make the decision to go with ansible-nas even if an app they wanted wasn't already available the list shows that it could easily be added and become available.

It was posted for discussion.

There's no other place for long term discussion. (I've meaning to suggest a Google Group.)

But the discussion got squashed fast... before there even was a discussion!

**Comment by davestephens** [comment]
It can still be discussed and reviewed, but it's not an open issue.

What I don't want is an endless list of discussion points that stay open
forever, issues are not the right place for that. Granted there is no
better place right now, but that's not to say we can't change that :-)

**Comment by bcurran3** [comment]
Agreed with the philosophy. Let's fix the problem: 
https://www.wikihow.com/Create-a-Google-Group

I'm actually NOT a fan of Google Groups... it's just the first thing I thought of since the other FOSS stuff I contribute uses it.

Personally I think you should be running phpBB and say "Welcome to Dave Stephens' Ansible-NAS discussion forum running on MY Ansible-NAS."
