### ISSUE TITLE
Future issue with letsencrypt, 100 subdomain per certificate limit.

### ISSUE THREAD

**Issue by animeai** [davestephens/ansible-nas#209]
As per https://letsencrypt.org/docs/rate-limits/ - The current limits on letsencrypt allows for a maximum of 100 subdomains per certificate. Currently we are well below this, but as we add new containers we will soon reach this limit. At current expansion, this will be within 12 months.

We'll need to plan how best to manage multiple letsencrypt certificates before this becomes an actual issue.

**Comment by davestephens** [comment]
I'm gonna close this for now - we're about 50 containers away so not a concern. 

Happy to reopen once we get closer.
