### ISSUE TITLE
Heimdall on port 80/443 by default

### ISSUE THREAD

**Issue by Vinibo** [davestephens/ansible-nas#215]
**Is your feature request related to a problem? Please describe.**
Hello

As I'm understanding the purpose of Heimdall, it is to provide a rich integration of supported applications running on the server, and proposing an easy way to access without having to remember all the ports. In this vision, I find it strange that I have to remind myself the correct port to access the dashboard and ofter have to peek in the ansible files to figure it out.

**Describe the solution you'd like**
I wonder if Heimdall should be available on 80/443 ports by default. I'm sure there are reasons why it hasn't been done (is it security? port conflict?) but can't think of one that would be a major blocker. I'm certainly missing something!

With mDNS support activated, it makes it really conveniant to head to `https://my-ansible-nas` and get served by the Heimdall dashboard.

Thank you!

**Comment by davestephens** [comment]
There are a few reasons (scraping the memory banks a bit here so bear with me!);

- Traefik is configured to use host-mode networking so we can use it to forward traffic to other host-mode networking containers, and Traefik grabs 80/443 by default. Changing this now would require everyone that uses it to reconfigure their router. I'm not totally adverse to this, but it would need a sensible migration path from how things are now, to running traffic http/https on different ports without totally screwing everyone up.  See #126 

- If you ran Heimdall on 80/443 - where would the SSL cert come from?

In theory your idea could work - but what's to say that this should win over something like AdGuard or PiHole (which have also been requested before)?

I think the best path forward would be to allow Traefik to be configurable (and I've raised #216 for the Traefik work), then people can stick whatever they want on whatever port.

**Comment by Vinibo** [comment]
Thanks for the quick reply!

Okay, so Traefik (or parts of it) act like a proxy in front of all apps on the server? So could the 'issue' be resolved by redirecting the captured 80/443 to Heimdall behind the scene? (That might be what you proposed).

As of Heimdall winning over PiHole, I think this is a decent choice, as Heimdall propose a rich integration with PiHole (Not for AdGuard however). Worst case scenario would be to access unsupported applications through their button in the dashboard.

But lean towards the ability of configuring the whole thing more!

**Comment by davestephens** [comment]
Traefik *is* a proxy, but for external traffic *into* your Ansible-NAS. IE if you want to access transmission whilst you're at work - that's what it'd do. 

Right now no internal traffic is routed through Traefik, and it's not something I've tried. I guess it would work

**Comment by davestephens** [comment]
@Vinibo I'm interested in your mDNS setup, is that something you're already using or was your comment more a "we could do this"?

**Comment by animeai** [comment]
Once #188 is merged, it'll be simple to map your default app to port 80 and 443 if you don't use traefik by adding the two port variables to your nas.yml.

**Comment by Vinibo** [comment]
> @Vinibo I'm interested in your mDNS setup, is that something you're already using or was your comment more a "we could do this"?

I've done it in the past, but more recently (this morning), I Integrated it into ansible-nas. I still need to modify the documentation but I will submit a pull request this evening.

And I'm fine with the configuration option, as it enables choice from the user!

Thanks again for your time!

**Comment by animeai** [comment]
Traefik is now also editable via your nas.yml in #188

**Comment by Vinibo** [comment]
I'm confirming that #188 let me put Heimdall on port 80/443!

Thank you all for your work!
