### ISSUE TITLE
Docker containers you would like to see?

### ISSUE THREAD

**Issue by animeai** [davestephens/ansible-nas#219]
Over the next few weeks, once #188, #201 and #203 are merged I'm going to make a start on adding some new containers to ansible-nas. I'm going to leave a list here of the potential ones I might be working on and would like other suggestions (if you don't want to raise your own issue for it) or shout outs so I can prioritise if you see something you want done sooner than others.

I'm well aware that a lot of these images I'll potentially be adding are either quite similar softwares (several wiki type images, photo gallery images, etc.) or alternatives for images we already have (like adding qbitorrent even though we have transmission). I feel that ansible-nas would have more global appeal if the software stack were more flexible for first time users. 

For reference, I've marked the ones I intend to work on sooner as "(high priority)". If there are requests for particular images I'll try to prioritise those too. Once completed and submitted as a PR, I'll edit this and strikethrough the entry.

**Linuxserver Images**: These are some of the best tested, easiest to use and most stable images on dockerhub. I'll be aiming to add the majority of them:

- https://hub.docker.com/r/linuxserver/photoshow
- https://hub.docker.com/r/linuxserver/hydra2
- https://hub.docker.com/r/linuxserver/syncthing
- https://hub.docker.com/r/linuxserver/organizr
- https://hub.docker.com/r/linuxserver/piwigo
- https://hub.docker.com/r/linuxserver/qbittorrent
- https://hub.docker.com/r/linuxserver/bookstack
- https://hub.docker.com/r/linuxserver/pydio-cells
- https://hub.docker.com/r/linuxserver/muximux
- https://hub.docker.com/r/linuxserver/rutorrent
- https://hub.docker.com/r/linuxserver/lazylibrarian
- https://hub.docker.com/r/linuxserver/dokuwiki
- https://hub.docker.com/r/linuxserver/freshrss
- https://hub.docker.com/r/linuxserver/lychee
- https://hub.docker.com/r/linuxserver/grocy
- https://hub.docker.com/r/linuxserver/sabnzbd
- https://hub.docker.com/r/linuxserver/beets
- https://hub.docker.com/r/linuxserver/diskover
- https://hub.docker.com/r/linuxserver/habridge
- https://hub.docker.com/r/linuxserver/smokeping
- https://hub.docker.com/r/linuxserver/healthchecks
- https://hub.docker.com/r/linuxserver/medusa
- https://hub.docker.com/r/linuxserver/mstream
- https://hub.docker.com/r/linuxserver/cops
- https://hub.docker.com/r/linuxserver/ddclient
-  ttps://hub.docker.com/r/linuxserver/mylar
- https://hub.docker.com/r/linuxserver/domoticz
- https://hub.docker.com/r/linuxserver/duckdns
- https://hub.docker.com/r/linuxserver/taisun
- https://hub.docker.com/r/linuxserver/minetest
- https://hub.docker.com/r/linuxserver/davos
- https://hub.docker.com/r/linuxserver/raneto
- https://hub.docker.com/r/linuxserver/pylon
- https://hub.docker.com/r/linuxserver/resilio-sync
-  https://hub.docker.com/r/linuxserver/ngircd
- https://hub.docker.com/r/linuxserver/headphones (high priority)
- https://hub.docker.com/r/linuxserver/booksonic (high priority)
- https://hub.docker.com/r/linuxserver/htpcmanager
- https://hub.docker.com/r/linuxserver/kanzi
- https://hub.docker.com/r/linuxserver/code-server
- https://hub.docker.com/r/linuxserver/deluge
- https://hub.docker.com/r/linuxserver/musicbrainz

**Other Docker images I'm wanting to work on integrating**:
- https://hub.docker.com/r/willfarrell/autoheal (high priority)
- https://hub.docker.com/r/hwdsl2/ipsec-vpn-server
- https://hub.docker.com/r/gogs/gogs
- https://hub.docker.com/r/binhex/arch-delugevpn (would require testing with additional VPN providers)
- https://hub.docker.com/r/sameersbn/gitlab
- https://hub.docker.com/r/itzg/minecraft-server
- https://hub.docker.com/r/rocketchat/rocket.chat
- https://hub.docker.com/r/mazzolino/shepherd
- https://hub.docker.com/_/ghost
- https://hub.docker.com/_/vault
- https://hub.docker.com/_/drupal
- https://hub.docker.com/r/owncloud/server/
- https://hub.docker.com/_/teamspeak
- https://hub.docker.com/_/redmine
- https://hub.docker.com/_/xwiki
- https://hub.docker.com/_/mediawiki
- https://hub.docker.com/_/yourls
- https://hub.docker.com/_/plone
- https://hub.docker.com/_/eggdrop
- https://hub.docker.com/_/discourse
- https://hub.docker.com/r/kylemanna/openvpn
- https://hub.docker.com/r/pihole/pihole (see #147 for issues around this container and adding it - will take some work!)
- https://hub.docker.com/r/pyouroboros/ouroboros
- https://hub.docker.com/_/wordpress
- https://hub.docker.com/r/searx/searx (high priority)
- https://hub.docker.com/r/filebrowser/filebrowser
- https://hub.docker.com/r/bitnami/phpbb (I want to avoid bitnami wherever possible as they use a github hosted yml file you curl rather than letting you set up the containers the way you actually want. To use their images, their hosted yml would need to be replicated, customised and monitored for key changes - this means the images are less stable as a big update from them could break the install. Having said that, they have the only reliable looking phpbb docker image!)
- https://hub.docker.com/r/bitnami/moodle (as above)
- https://hub.docker.com/r/filebrowser/filebrowser
- https://hub.docker.com/r/thomseddon/traefik-forward-auth (high priority, suggested by Malpractis on gitter - they may provide a PR with this)
- https://hub.docker.com/r/solidnerd/bookstack
- https://hub.docker.com/r/pomerium/pomerium
- https://hub.docker.com/r/cachethq/docker
- https://hub.docker.com/r/diameter/rtorrent-rutorrent
- https://hub.docker.com/r/fredboat/fredboat
- https://hub.docker.com/r/hunterlong/statping
- https://hub.docker.com/r/blacklabelops/logrotate
- https://mailcow.github.io/mailcow-dockerized-docs/i_u_m_install/ (this one might need some thought!)
- https://github.com/Mailu/Mailu (as per mailcow, will need some thought!)
- https://hub.docker.com/r/analogic/poste.io (simpler than the above two as it is a single container)
- https://hub.docker.com/r/monitorr/monitorr/
- https://hub.docker.com/r/binhex/arch-rtorrentvpn
- https://hub.docker.com/r/requarks/wiki
- https://hub.docker.com/r/rlister/hastebin
- https://hub.docker.com/r/hotio/trackarr
- https://hub.docker.com/r/monicahq/monicahq

OK, so this is my current list of what I think is useful software that's available in mostly popular (therefore well tested) images. I can't guarantee that just because I listed it, I can make it work. Some of these are reliant at the moment on docker-compose (which slightly defeats the object of ansible) and I'm unsure whether I'm happier to rewrite the docker-compose files into ansible and attempt to maintain them against the upstream versions or whether it would be simpler to use an ansible task to envoke the docker-compose. There may also be configuration issues, stability issues, or other unforeseen issues with any of these images... So no promises!

**Comment by ither** [comment]
_traefik-forward-auth_ seems really nice

**Comment by davestephens** [comment]
A few things that come to mind: 
- I like the premise behind this, but I'm not sure a single issue is a good way to track who wants what.
- @animeai - your comment of "I'll be aiming to add the majority of them" - is that because you genuinely want to use all of the applications, or just because you'd like all of the linuxserver applications available in the Ansible-NAS in case someone might want to see them?
- I'd like to point out that every application comes with a maintenance overhead, and thus adding every-single-application-we-can-find-everywhere-on-the-whole-internet-just-because is probably not a great idea. :smile: Very recent examples of this - #211, #217, #202. If people are using the apps then that's cool as there's generally interest in getting things fixed, but if we have an app that nobody uses, it'll get stale quickly and is pointless adding it. 

I'd like to propose that the list is cut down to applications that people would actually like to see added *right now*. We then raise individual issues for the shorter list that people can then vote on :+1: should they want it (and nobody has worked on it yet). These are also `good first issue` issues that beginner contributors can get stuck into. 

Additionally I'll add a new issue template for "new application request".

Thoughts?

**Comment by animeai** [comment]
@davestephens There are quite a few in there I want to play around with :) If I add one, I do however intend to support it. This is one of the reasons I like the linuxserver images - they tend to be very stable and I've personally not experienced one breaking on me after install and initial testing. I've put together this list mostly to try and gauge whether there is interest in some of these packages... Hopefully with the "new application request" template we could probably lose this issue soon as that might have been offputting for some users wanting something specific.

**Comment by Vinibo** [comment]
@animeai The list is pretty complete!
On my side, my plan was to add 2/3 more services on this project:
- https://hub.docker.com/r/linuxserver/syncthing
- https://hub.docker.com/r/linuxserver/beets
- Maybe Wireguard, more research needed

I already opened 2 pull requests, Syncthing the next thing on my list!

**Comment by andrewboie** [comment]
Two that immediately come to mind

- rclone for synchronizing Google Drive. I have a fairly large google drive and would like my nas to have the entire thing available on it, so my other machines can get at it without needing individual copies. If there's an existing container we support that does this please point me to it. looks like it has docker/ansible support https://github.com/rclone/rclone/blob/master/docs/content/install.md

- folding@home - my NAS has a GPU folding proteins in the background, in the future I may add up to 2 more of them. NAS performance seems decent if I just use the GPU and not the CPU for folding.

**Comment by DLLarson** [comment]
I would like to see `sabnzbd` even though `Nzbget` is already offered. The reason is to support migration from FreeNAS which provided a `sabnzbd` jail for those that used that service (me ;) ).

https://hub.docker.com/r/linuxserver/sabnzbd

-Dale

**Comment by DLLarson** [comment]
> I would like to see sabnzbd...

Added:

https://github.com/davestephens/ansible-nas/pull/229

-Dale

**Comment by Vinibo** [comment]
Synching will be available with MR #228

**Comment by davestephens** [comment]
I'm gonna close this one out as it's not an issue and is not really closable unless we add every application ever written to Ansible-NAS. 

Please feel free to use the new application request issue template for things you'd like to get added, that way they can be tracked and assigned as individual items 👍
