### ISSUE TITLE
add notes about claiming plex server to documentation

### ISSUE THREAD

**Issue by andrewboie** [davestephens/ansible-nas#222]
**Is your feature request related to a problem? Please describe.**
When I enabled the plex docker image, for a long time I was mystified why my server was invisible to plex clients, even when connecting to the server on port 32400

Turns out you need to issue some commands to register your server with plex itself. This is summarized here https://forums.plex.tv/t/plex-cant-find-my-server-help/274370/7 and someone provided a script to do this.

For me the sequence of commands (run inside the plex container using Portainer) worked and now my plex server is working beautifully:

```
# download the script
curl -L -o plex-claim-server.sh https://github.com/uglymagoo/plex-claim-server/raw/master/plex-claim-server.sh
# make the script executable
chmod +x plex-claim-server.sh
# go to https://www.plex.tv/claim/ in your browser and get the claim token and replace PLEX_CLAIM with this token in the next command, please use use the double quotes around your claim token
./plex-claim-server.sh "PLEX_CLAIM"
```

**Describe the solution you'd like**
Some kind of note in the documentation that this needs to be done else the plex server won't be functional.

**Describe alternatives you've considered**
None so far, but I'm a plex newbie.

**Comment by Malpractis** [comment]
You can also do it by going to: https://www.plex.tv/claim

And adding an environment variable to the plex container (must be done within 3min I think) with the token.
PLEX_CLAIM=token here

**Comment by Malpractis** [comment]
This is from the plex container documentation:

> PLEX_CLAIM The claim token for the server to obtain a real server token. If not provided, server will not be automatically logged in. If server is already logged in, this parameter is ignored. You can obtain a claim token to login your server to your plex account by visiting https://www.plex.tv/claim

**Comment by nough** [comment]
I believe it's possible to claim the plex server just by logging in to it with your plex account.
