### ISSUE TITLE
files/folders in roles/ directory causing problems in GitKraken

### ISSUE THREAD

**Issue by C-J1** [davestephens/ansible-nas#23]
The roles/samba and roles/docker directories are causing me some issues. GitKraken (on Windows) thinks they are supposed to be submodules, but I can't see a .git directory in there at all.

Regards,

CJ

**Comment by davestephens** [comment]
Doh, I see what's happened here. I used to load in the roles via git submodules but changed it a while back  to use ansible-galaxy instead. Looks like my last commit accidentally added part of the submodule config back in :man_facepalming:

**Comment by davestephens** [comment]
Should be sorted.
