### ISSUE TITLE
Comment variables and reorganise all.yml

### ISSUE THREAD

**Issue by animeai** [davestephens/ansible-nas#234]
To help new users it would be useful to:

- Place the containers in all.yml in alphabetical order to help find what needs editing
- Comment the variables in all.yml so there is no confusion about what any of them do
- Add the options that will always need editing to the sample nas.yml.

When I have some time I will probably make a start on this, but if anybody else wants to do something with it first I'm more than happy.

**Comment by bcurran3** [comment]
+1/thumbs up/etc - I'm VERY MUCH in favor of alphabetizing (almost) everything. It makes it soooooooooooo much easier to read. PLUS when running updates you have a better understanding of how far along you are in the process.

Alternative would be to do things categories and put it a debug msg saying the category that's starting to be processed (and then apps in alphabetical order within the category). Throwing it out there, but I think I still prefer global alphabetical.

**Comment by davestephens** [comment]
100% agree with this, and it is being done as part of the move to roles.

all.yml will be very slim once complete, vars docced where necessary, and roles are alphabetical.
