### ISSUE TITLE
Application Request: Full email stack

### ISSUE THREAD

**Issue by animeai** [davestephens/ansible-nas#237]
**Application you'd like to add:**
A full email stack.

**Link to Docker image:**
Unknown. I would like feedback from users who have implemented full emails stacks via docker in the past on containers that are very simple to set up, rock solid, integrate features such as ClamAV, SpamAssassin etc. 

**Why you'd like this application added:**
Currently I need to run the email server for my ansible-nas mapped domain on an alternative machine. As the email volume is very low (friends and family, no subscriptions etc) I would like it to run on the NAS. 

I am happy to implement this as a feature if I can get some recommendations on a good docker stack or set of containers that play nicely together.

**Comment by ckoehler** [comment]
Check out mailcow.

**Comment by jesse-troy** [comment]
i am tinkering around with mailu which seems like it might work well with this setup

**Comment by bcurran3** [comment]
@jesse-troy - any updates?

I too am investigating this; mailu, mailcow, and rainloop are all on my list of possibilities. 
On the TDL but low priority due to complexity and time.

**Comment by bcurran3** [comment]
I keep looking at the docker-compose.yml file for mailcow, it's big and complex. I WANT to make it work with Ansible-NAS. I really do. Once the PR queue catches up and the Ansible-NAS ball starts rolling again I'll be willing to put in the time. In the meantime, I sure hope someone else does it. :)

**Comment by davestephens** [comment]
Demand for this seems pretty low. Happy to look at PRs if someone wants to implement something.
