### ISSUE TITLE
Grafana datasource access needs to be `proxy`

### ISSUE THREAD

**Issue by ckoehler** [davestephens/ansible-nas#241]
In [templates/grafana/provisioning/datasources/ansible-nas.yml#L12](https://github.com/davestephens/ansible-nas/blob/b72198406feeee1d4e11761c28d8071cbc8aa53d/templates/grafana/provisioning/datasources/ansible-nas.yml#L12), access should be proxy instead of direct. With direct, when you use Grafana with a domain from outside your network, your browser will reference your internal IP address, so you get no data. With proxy, Grafana grabs the data internally, not through the browser, so everything works.

**Comment by davestephens** [comment]
Fixed in https://github.com/davestephens/ansible-nas/commit/692dfea2e95657f67d01e23cace313071fa20ba5
