### ISSUE TITLE
Typo on https://davidstephens.uk/ansible-nas/

### ISSUE THREAD

**Issue by Iruberiam** [davestephens/ansible-nas#242]
Install Ansible:
sudo apt update
sudo apt install software-properties-common
**sudo apt-add-repository --yes --update ppa:ansible/ansible**
sudo apt install ansible

Should read:

Install Ansible:
sudo apt update
sudo apt install software-properties-common
**sudo add-apt-repository --yes --update ppa:ansible/ansible**
sudo apt install ansible

**Comment by animeai** [comment]
This is symlinked already in 18.04 so actually doesn't make a difference. Unless Ubuntu have decided to depreciate this symlink (which I would be very surprised about) there isn't an issue. With the symlink, "apt-add-repository" and "add-apt-repository" are completely interchangeable.

**Comment by Iruberiam** [comment]
You are correct, thank you for the confirmation.
