### ISSUE TITLE
Upstream Bug: cloudflare-ddns no longer working

### ISSUE THREAD

**Issue by animeai** [davestephens/ansible-nas#243]
The Cloudflare DDNS image joshava/cloudflare-ddns has not been updated in over a year - I'm unsure if it is abandonware or not. Cloudflare have depreciated global API calls, instead you now issue an API key for individual domains and actions. You can no longer issue the global API key the docker image needs. This leaves the docker image no longer working for new installs and if it still works for existing installs, it won't do for much longer.

As a sidenote, we are also not using cloudflare effectivelyas we simply issue a wildcard subdomain pointing to our install. On free plans this means we cannot proxy the subdomains without either manual setup or paying cloudflare silly monry to upgrade the plan.

**Comment by davestephens** [comment]
Any suggestions of what we can replace it with? The container is
essentially a wrapper around a batch script, so shouldn't be difficult to
fix if there are.no alternatives...

**Comment by animeai** [comment]
I did have a look but found no drop in replacement yet. There are a lot of containers modified within the past few weeks surrounding the cloudflare api but I've not had a chance to test them yet.

**Comment by anthonymobile** [comment]
short-term fix, what 
what about a container with ddclient? this ddclient.conf works for me with the Global API key. am running it alongside ansible-nas on the host.

`# Configuration file for ddclient

##
## Global Config
##
daemon=300
ssl=yes

##
## sub.domain.tld - Cloudflare ## Update Me
##
protocol=cloudflare
use=web
login=accountemail@someplace.com
password=redacted_global_api_key
zone=somedomain.org
*.somedomain.org
`
re prev comment: i created a new account and received a global API key... so not sure.
also, have not looked into using ddclient with the new API mechanism. will probably wait until this breaks for good. ;)

**Comment by anthonymobile** [comment]
looks like a dead end for now, ddclient support for the new API token mechanism has been open for lose to a year https://github.com/ddclient/ddclient/issues/73

**Comment by anthonymobile** [comment]
have moved ddclient over to a container in portainer and its running nicely.

placed my custom ddclient.conf in /mnt/Volume2/docker/ddclient (create dir first manually)
not sure if this is right.

i believe this is the docker command used (change the TZ below)

```
docker create \
  --name=ddclient \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=America/New_York \
  -v /mnt/Volume2/docker/ddclient:/config \
  --restart unless-stopped \
  linuxserver/ddclient
```

not sure how to contribute this as a pull to the project if its a good fix.

**Comment by Northbadge** [comment]
Just visiting, and thought I might add that there's https://github.com/ddclient/ddclient/pull/102

**Comment by bcurran3** [comment]
https://hub.docker.com/r/qmcgaw/ddns-updater

I've been communicating with the developer of ddns-updater to support my requirements. He's very friendly, willing, and active.

Specifically picked his project because I like the chart report it creates:
![](https://raw.githubusercontent.com/qdm12/ddns-updater/master/readme/webui.png)

I've had it installed and setup in Ansible-Nas for awhile. I just need to get back to testing if it works with dyndns or not.  https://github.com/qdm12/ddns-updater/issues/55

My vote is for this and I plan to submit it once it is working for me. :)

**Comment by ryanolf** [comment]
Hey all, I just posted a PR that should fix this issue without anyone needing to change their existing configs. You can also easily change from the global API key to access token. The underlying container was updated last month, and these changes take advantage of that.
