### ISSUE TITLE
Pending Merge requests #232 #212 & #220

### ISSUE THREAD

**Issue by Vinibo** [davestephens/ansible-nas#244]
**Is your feature request related to a problem? Please describe.**
I have a vision/a need that I saw fit into your ansible project. My vision was to build an awesome and automated music repository.
In this vision, I had:
- A script that copy every music files coming from Transmission into an 'import folder'.
- Beets that run every 15 minutes to see changes or new files into that import folder. Beets is cleaning, tagging and organizing the music in a uniform fashion. Once that's done, it moved the cleaned version into the 'music' folder. (I'm working on this, it is 85% done).
- Syncthing monitor the folder 'music' and once changes are detected, it sync everything on connected devices (done and MR in WIP).
- I'm also working on an ansible-role to automatically rip audio CD and putting files in the 'import' folder.

Most of this works, but since the MR #232 is not merged, Beets cannot save the music files under the 'ansible-nas' user/group. If it copies under root (UID/GID 0), then Syncthing complains and it creates problems on connected devices.

I see that you are active on some pull requests, by tagging and commenting. I understand that you do this on your free time (like most of us doing Open Source world) and I also understand that you work on what interest/motivate you. Am I doing something wrong in my pull requests? Just tell me and I'll do the appropriate fixes. 
Thank you for your time, and this awesome project!

**Describe the solution you'd like**
Pull requests to be reviewed and/or merged into master.

**Describe alternatives you've considered**
I've considered stop proposing merge requests and only commit in my forked repository.

**Comment by davestephens** [comment]
All PRs merged/closed 👍
