### ISSUE TITLE
what is the correct/default way to enable & reach grafana dashboard?

### ISSUE THREAD

**Issue by xerosanyam** [davestephens/ansible-nas#245]
I did `grafana_enabled : true` & also `grafana_available_externally: true`, but still unable to reach grafan dashboard at IP:3000
What am I doing wrong?

**Comment by davestephens** [comment]
Not sure. It works fine for me.

What do you logs of the docker container say? Might be worth you filling
out the full issue temolate so I can help you.

**Comment by bcurran3** [comment]
Some suggestions:
1> make sure you're trying to access it over the LAN
2> make sure the container is running (check portainer)

**Comment by davestephens** [comment]
Closing due to not receiving any more info.
