### ISSUE TITLE
What triggers traefik to update the LetEncrypt certificate?

### ISSUE THREAD

**Issue by DLLarson** [davestephens/ansible-nas#248]
What triggers traefik to update the LetEncrypt certificate?

I just got an email from LetsEncrypt warning:

> Your certificate (or certificates) for the names listed below will expire in 20 days (on 02 May 20 20:43 +0000). Please make sure to renew your certificate before then, or visitors to your website will encounter errors. ....

It may be automatic and just hasn't happened yet but how can I be sure?

Thanks!
-Dale

**Comment by davestephens** [comment]
I've never had an active certificate expire - the expiry notices I've had have been for "old" certificates. i.e. ones with lists of SANs that aren't current. Bear in mind if the list of hosts change (when a new application is added this will happen), Traefik will request a new certificate. Also, if you change your domain (`ansible_nas_domain`), that'll trigger a new certificate too.

There's a bit more info [here](https://docs.traefik.io/https/acme/). 

I'm going to close this as the behaviour isn't controlled by Ansible-NAS :+1:

**Comment by DLLarson** [comment]
Thanks for the link!
-Dale
