### ISSUE TITLE
Make memory: in all tasks a variable in all.yml

### ISSUE THREAD

**Issue by bcurran3** [davestephens/ansible-nas#253]
**Describe the solution you'd like**

Convert memory: statements in tasks to use a variable defined in all.yml. Why? Why not, everything else is. No, really I like to give some containers some more breathing room as my server has plenty of RAM. Plex's pseudo recommendation is 2g even though it works in 1g. I like to give it 8g. (Yeah, overkill.) I give more RAM to Transmission too for better caching.

**Describe alternatives you've considered**

Continue to manually update the task files myself.

**Additional context**

None.

I'm willing to do the PR, but it would be awhile. I'm many many many commits behind and have other container apps I want to submit first.

**Comment by PurpleNinja225** [comment]
I think a great way to acomplish this would be to edit the `roles/ansible-nas-docker/templates/daemon.json`  to look a little somthing like this:

```json
{
  "data-root": "{{ docker_image_directory }}",
  "storage-driver": "{{ docker_storage_driver }}",
  "memory": "{{ docker_default_memory }}"
}
````
add the variable to roles/example_app/defaults/main.yml
```yml
example_app_memory: "{{ docker_default_memory }}" 

and update the ../tasks/main.yml

```yml
memory: "{{ example_app_memory }}"
```

This creates a configurable default memory for containers through the docker daemon and if users want a specific app to have more mem, such as plex, or nextcloud, or jellyfin, etc. it can be configured through it respective role folder.

**Comment by davestephens** [comment]
This is actually being implemented with the move to roles, which I like, so I'll close this. If someone wants to tackle any outstanding I'll happily merge!

**Comment by bcurran3** [comment]
I just spot checked four roles, only one had it. At very least bitwarden, cloudmd, and duplicati still have hardcoded memory limits.

**Comment by davestephens** [comment]
@bcurran3 you were right, nowhere near the coverage I had thought it was. Fixed now!
