### ISSUE TITLE
Application Request: Organizr

### ISSUE THREAD

**Issue by TimGeerts** [davestephens/ansible-nas#256]
**Application you'd like to add:**
Organizr

**Link to Docker image:**
https://hub.docker.com/r/organizrtools/organizr-v2

**Why you'd like this application added:**
Even though Heimdall serves a similar purpose, I personally prefer Organizr on a media server as it provides quite a lot more features on the "dashboard".

I have no experience with the code of Ansible-nas, but if needed I could try and create the task and variables for it myself with a pull request (is there any information around "how to add applications to ansible-nas" perhaps?)

**Comment by bcurran3** [comment]
Makes perfect sense to me to have a Heimdall alternative.

I'll play with it in the future to see if I like it. :)

Looks REALLY easy to add to ansible-nas.

**Comment by bcurran3** [comment]
OCD and Mountain Dw zero sugar Baja Blast got the better of me and I just made configs for Organizr in my ansible-nas. Will submit a PR in the near future.

**Comment by TimGeerts** [comment]
Lovely! Will keep an eye out for that!

**Comment by bcurran3** [comment]
I played with it...

I'm sporting a big bonified love for it. I like the IFrame integration. Not as intuitive to setup as Heimdall, but also has more features.

I'll go work the PR now....

**Comment by bcurran3** [comment]
PR done:
https://github.com/davestephens/ansible-nas/pull/273

**Comment by bcurran3** [comment]
This has been merged into the master build with commit https://github.com/davestephens/ansible-nas/commit/349b5efbf0d344df325c250735819ca13a44ac36, issue can be closed.
