### ISSUE TITLE
Allow configurable external hostnames

### ISSUE THREAD

**Issue by bcurran3** [davestephens/ansible-nas#263]
**Is your feature request related to a problem? Please describe.**

Yes. Traefik (really Let'sEncrypt) will fail to create certs in non-wildcard situations where ansible-nas created a traefik.toml config file with FQDN's that don't exist.

**Describe the solution you'd like**

Use Ansible's File module to create a traefik.toml file with only FQDNs that are needed.

**Describe alternatives you've considered**

Only real alternative now is to manually edit the template to remove unnecessary FQDNs and back it up before doing a pull of the latest ansible-nas files.

**Additional context**

I'll probably take this on if no one else steps up. I'm not going to address it until we switch to Traefik 2.0 which I haven't event looked at it.

**Comment by davestephens** [comment]
The reason it was done the way (and the associated required DNS setup), was
to prevent users getting rate-limited by Letsencrypt. It looks like their
rate limits have changed though so this is probably worth revisiting.

It may be worth considering a cert per application (Letsencrypt allow 50
per domain), or as you say, generating the traefik.toml based on what's
enabled.

I wouldn't use the file module for that FWIW, I'd probably use Jinja
templates with conditional blocks around each app hostname.

**Comment by bcurran3** [comment]
Glad your in agreement. I'm not familiar with Jinja, but can look into it. After Traefik 2.0 lands in ansible-nas I'd still be willing to look into it. Perfectly fine and happy if someone else does it though. :)

**Comment by bcurran3** [comment]
Related/Unrelated - if possible, it would be nice to populate Organizr and Heimdall with settings for enabled apps. I haven't looked into it yet, but if we create a list (array) of enabled apps for the traefik.toml that same list MIGHT also be usable to populate Organizr and Heimdall.

**Comment by StopMotionCuber** [comment]
I implemented this together with custom subdomains on #324

**Comment by davestephens** [comment]
I've nearly got a branch ready with Traefik 2.3 on, which uses a wildcard cert, which means no cert rate limits, which means - configurable hostnames.

**Comment by PurpleNinja225** [comment]
This can be closed
