### ISSUE TITLE
RFC: Standard naming for host access via volume mounts

### ISSUE THREAD

**Issue by bcurran3** [davestephens/ansible-nas#266]
**Is your feature request related to a problem? Please describe.**

FEATURE REQUEST: A standardized naming convention for host access from containers. My suggestion.... wait for it, yeah, "/host." This is targeted at apps that interactively let you use the host filesystem, not ones that you just set and forget. I understand these apps are added via disparate contributors and generally mount volumes as the disparate container creators show as examples, but I'd like to suggest we tweak them a bit, ansible-nasize them, to make them more templated so  people don't have to remember all the different places to find what they want depending on what app they are using. I'd like to see the mount points standardized to make it intuitive. 

Some current examples:
Cloud Commander mounts / via /mnt/fs
Duplicati mounts shares and Docker data via /source/shares and /source/docker
Virtual Desktop mounts shares via /samba and Docker data via /docker

Obviously this would be something to mention in the contributing docs.

**Describe the solution you'd like**

Mount all host data to /host or /mnt/host

**Describe alternatives you've considered**

**Additional context**

**Comment by davestephens** [comment]
Happy to accept a PR if people think this is worthwhile....
