### ISSUE TITLE
Documentation for latest Ubuntu LTS

### ISSUE THREAD

**Issue by martinjh99** [davestephens/ansible-nas#272]
More of a docs bug report...

Installing on the latest Ubuntu 20.04 server edition.

You don't need to add the Ansible repo any more as Ansible is now part of the Ubuntu repos.

**Comment by davestephens** [comment]
It always has been - but we add the Ansible PPA to ensure we get the latest
version. Ubuntu's repos are usually a little behind.

**Comment by StopMotionCuber** [comment]
Actually, there is no ansible ppa repository for focal (yet).
I would also vote in favor of removing that section, as ansible should be recent enough from ubuntu repositories to get the job done and security patches should also get applied as long as we have an ubuntu that still receives support.

**Comment by bcurran3** [comment]
Related reading: https://github.com/davestephens/ansible-nas/issues/200

**Comment by davestephens** [comment]
Closing as 20.04 tested successfully and docs updated 👍
