### ISSUE TITLE
add Calibre proper

### ISSUE THREAD

**Issue by bcurran3** [davestephens/ansible-nas#297]
(SORRY I used the wrong template!)

**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

We have Calibre-web, seems we should have Calibre proper to go with it!
(There, I spoke British!)

**Describe alternatives you've considered**

I'm a fan of Ubooquity...

**Additional context**

https://hub.docker.com/r/linuxserver/calibre

If no one else does it, I probably will even though I don't use it.

**Comment by bcurran3** [comment]
I month, no response. @davestephens?

**Comment by davestephens** [comment]
Yes. I have a life other than Ansible-NAS, believe it or not. I will get to
this around my job, kids at home, paid projects etc, as time allows...

**Comment by bcurran3** [comment]
![image](https://user-images.githubusercontent.com/14026600/85933329-ad41f500-b88a-11ea-8ffc-08e3ad6e9e60.png)
