### ISSUE TITLE
nginx_enabled error

### ISSUE THREAD

**Issue by patricker** [davestephens/ansible-nas#31]
I saw you recently removed nginx_enabled, and replaced nginx with Traefik. Looks like maybe you missed a spot? I can't get the ansible to go all the way through.

I worked around it by adding a line that says `nginx_enabled: false`, and then it moved past that point.

TASK [Create Nginx Directories] **************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'nginx_enabled == true' failed. The error was: error while evaluating conditional (nginx_enabled == true): 'nginx_enabled' is undefined\n\nThe error appears to have been in '/home/peter/ansible-nas/tasks/nginx.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Create Nginx Directories\n  ^ here\n"}

PLAY RECAP ***********************************************************************************************************************************************************
localhost

**Comment by davestephens** [comment]
Thanks for reporting this, should now be sorted.

This weekend's job - CI!
