### ISSUE TITLE
Gitea: fail to create database

### ISSUE THREAD

**Issue by juliotux** [davestephens/ansible-nas#334]
**Describe the bug**
I tried to install ansible-nas multiple times and use gitea service, I always get an error in the first registry of `The database settings are invalid: Error 1005: Can't create table 'user' (errno: 13)`. I didn't touch the db configuration of the default gitea installation.

![Screenshot](https://user-images.githubusercontent.com/497246/82763521-be589b80-9dde-11ea-8a60-2cd07dbd6969.png)

**Environment**
- Ansible-NAS revision (`git rev-parse --short HEAD`): `a61ecb9`
- Ansible version (paste the entire output of `ansible --version` on the machine you run the playbook from): `2.9.9`
- Ansib..le-NAS operating system (`cat /etc/lsb-release` on the Ansible-NAS box) - _If this is anything other than Ubuntu 18.04 help will be limited_: `Ubuntu 20.04`
- Ansible-NAS kernel (`uname -a` on the Ansible-NAS box): `Linux nas 5.4.0-31-generic`
- Ansible-NAS Python version (`python --version` on the Ansible-NAS box): `3.8.2`
- Ansible-NAS Docker version (`docker --version` on the Ansible-NAS box): `19.03.9`
- Latest Docker logs (`journalctl -u docker.service` on the Ansible-NAS box): ``
- Are you running the playbook from a remote box or the Ansible-NAS box itself?  `remote`
- Vagrant version, if testing (`vagrant --version`): ``
- Ansible-NAS filesystems (`df -hT` on the Ansible-NAS box): ``
- Mounted filesystems (`mount` on the Ansible-NAS box) ``

**Expected behavior**
The error shouldn't appear.

**Actual behavior**
Error reported.

**Steps to reproduce**
Install gitea via ansible-nas and try to access gitea service.

**Comment by StopMotionCuber** [comment]
I just tested this and couldn't reproduce your error, also with Ubuntu 20.04.
This is probably an issue with your `gitea_data_directory`, where you get a permission denied for whatever reason within the mysql container.

**Comment by davestephens** [comment]
I've just tried on a fresh install and can't reproduce this either. Feel free to reopen, providing steps to reproduce and/or a demo VM.

**Comment by slaytostay** [comment]
@davestephens I think I just had this happen while running multiple mysql instances (for example, nextcloud-mysql and gitea-mysql). I was able to create the database after shutting down nextcloud.
