### ISSUE TITLE
nginx.yml is not imported into nas.yml 

### ISSUE THREAD

**Issue by ShadowOfThePenguin** [davestephens/ansible-nas#339]
**Describe the bug**
In nas.yml, there is no import of the tasks for nginx

**all.yml Variables**
nginx_enabled: true

**Expected behavior**
add Nginx container and Letsencrypt Container

**Actual behavior**
never listed

**Steps to reproduce**
download current ansible-nas, set nginx_enabled: true

**Comment by davestephens** [comment]
It's actually not supposed to be - this was a hangover from prior to using Traefik as a reverse proxy. `nginx.yml` has now been removed.
