### ISSUE TITLE
Ubuntu LTS 20.04 - Playbook still failing at Add Docker Repository on geerlingguy.docker role 2.8.0

### ISSUE THREAD

**Issue by jumarc** [davestephens/ansible-nas#340]
Trying to install Ansible NAS on new Ubuntu 20.04 LTS install. Updated requirements.yaml to point to geerlingguy.docker version 2.8.0 as per Pull Request - Ubuntu 20.04 support #335, and reinstalled roles successfully.

Playbook still fails at adding docker repository.

**Environment**
- Ansible-NAS revision (`git rev-parse --short HEAD`): a61ecb9
- Ansible version (paste the entire output of `ansible --version` on the machine you run the playbook from):
```
ansible 2.9.6
  config file = /ansible-nas/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]
```
- Ansible-NAS operating system (`cat /etc/lsb-release` on the Ansible-NAS box) - _If this is anything other than Ubuntu 18.04 help will be limited_:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
- Ansible-NAS kernel (`uname -a` on the Ansible-NAS box):
Linux cutlernas 5.4.0-33-generic #37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Ansible-NAS Python version (`python --version` on the Ansible-NAS box): Python 3.8.2
- Ansible-NAS Docker version (`docker --version` on the Ansible-NAS box):
- Latest Docker logs (`journalctl -u docker.service` on the Ansible-NAS box):
- Are you running the playbook from a remote box or the Ansible-NAS box itself? On NAS
- Vagrant version, if testing (`vagrant --version`):
- Ansible-NAS filesystems (`df -hT` on the Ansible-NAS box):
Filesystem     Type      Size  Used Avail Use% Mounted on
udev           devtmpfs   12G     0   12G   0% /dev
tmpfs          tmpfs     2.4G  2.8M  2.4G   1% /run
/dev/sda2      ext4      110G  6.8G   98G   7% /
tmpfs          tmpfs      12G     0   12G   0% /dev/shm
tmpfs          tmpfs     5.0M     0  5.0M   0% /run/lock
tmpfs          tmpfs      12G     0   12G   0% /sys/fs/cgroup
/dev/loop1     squashfs   55M   55M     0 100% /snap/core18/1705
/dev/loop2     squashfs   69M   69M     0 100% /snap/lxd/14804
/dev/loop0     squashfs   55M   55M     0 100% /snap/core18/1754
/dev/loop3     squashfs   28M   28M     0 100% /snap/snapd/7264
/dev/loop4     squashfs   70M   70M     0 100% /snap/lxd/15223
tmpfs          tmpfs     2.4G     0  2.4G   0% /run/user/1000
morpheus       zfs        15T  256K   15T   1% /morpheus
- Mounted filesystems (`mount` on the Ansible-NAS box)

**Expected behavior**
Playbook should continue and complete without error

**Actual behavior**
Fails at Add Docker epository

**Steps to reproduce**
Fresh install of ubuntu 20.04, then ansible-nas install steps as per documentation (plus updating requirements'yaml to point to geerlinguy.docker 2.8.0)

**Playbook Output**
```
TASK [geerlingguy.docker : Add Docker repository.] ****************************************************************************************************************************************************************************************************************************
task path: /root/.ansible/roles/geerlingguy.docker/tasks/setup-Debian.yml:36
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1591047642.9766803-91500709718613 `" && echo ansible-tmp-1591047642.9766803-91500709718613="` echo /root/.ansible/tmp/ansible-tmp-1591047642.9766803-91500709718613 `" ) && sleep 0'
Using module file /usr/lib/python3/dist-packages/ansible/modules/packaging/os/apt_repository.py
<localhost> PUT /root/.ansible/tmp/ansible-local-13201eshskvl9/tmp30j6hbpr TO /root/.ansible/tmp/ansible-tmp-1591047642.9766803-91500709718613/AnsiballZ_apt_repository.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1591047642.9766803-91500709718613/ /root/.ansible/tmp/ansible-tmp-1591047642.9766803-91500709718613/AnsiballZ_apt_repository.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1591047642.9766803-91500709718613/AnsiballZ_apt_repository.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1591047642.9766803-91500709718613/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_apt_repository_payload_t5xskhrv/ansible_apt_repository_payload.zip/ansible/modules/packaging/os/apt_repository.py", line 548, in main
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 591, in update
    raise FetchFailedException(e)
fatal: [ansible-nas]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "codename": null,
            "filename": null,
            "install_python_apt": true,
            "mode": null,
            "repo": "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable",
            "state": "present",
            "update_cache": true,
            "validate_certs": true
        }
    },
    "msg": "apt cache update failed"
}
```

**Additional context**

**Comment by bcurran3** [comment]
"Me too."

> TASK [geerlingguy.docker : Add Docker repository.] *********************************************************************
> fatal: [ansible-nas]: FAILED! => {"changed": false, "msg": "apt cache update failed"}

**Comment by davestephens** [comment]
This isn't a bug, Ubuntu 20.04 isn't supported yet. A pull request is exactly that - a request to have code pulled into the main Ansible-NAS repo. Anything in a pull request is not Ansible-NAS code, guidance or supported until it is.

**Comment by jumarc** [comment]
All good, sorry I think I misinterpreted notes against another issue. I'll go back to 18.04 for now.

Just wanted to say thanks for this awesome build! I'm making the transition after xpenology broke one too many times.
