### ISSUE TITLE
Samba docker container

### ISSUE THREAD

**Issue by yonil7** [davestephens/ansible-nas#345]
**Application you'd like to add:**
Samba docker container: https://github.com/dperson/samba

**Link to Docker image:**
https://hub.docker.com/r/dperson/samba/

**Why you'd like this application added:**
ansible-nas already contains a Samba service configured by bertvv.samba ansible role to run on the host.
I was wondering whether its a better option to encapsulate this service in a docker container instead - not sure its a better solution, but I would like to hear your opinion on this matter

**Comment by bcurran3** [comment]
Personally I see file sharing as a core OS responsibility and feel that Samba in a docker is just for people who want to put everything and anything in a container they can. I'm not saying it's a bad idea, I'm just saying how often has Samba broke and let you down? Related, there's a container now for docker-compose. I laugh every time I see it and ask myself "Why?" Then I ask myself, "When is someone going to make a bash container?" (chuckle).

**Comment by StopMotionCuber** [comment]
Aren't most OS containers available by default bash containers (like the default Ubuntu container)? This is good to test functionality for different distributions quite fast.

Related to the samba container, I'm with @bcurran3 here, especially as I think Canonical will provide better support/packaging for samba than the container you provided (last update was 2 month ago).

**Comment by davestephens** [comment]
I agree with @bcurran3 on this - it makes sense to containerise applicationos where Docker brings something to the table. In the case of applications like Plex, it's easy install/upgrade/remove/start/stop. 

Samba is a core OS service that doesn't gain anything by being dockerised, therefore I have no desire to move a working samba setup out to docker.
