### ISSUE TITLE
DAVE - considering implementing automatically rebasing

### ISSUE THREAD

**Issue by bcurran3** [davestephens/ansible-nas#347]
Read this:
https://davidwalsh.name/automatically-rebase-github-pull-requests

Hope you're OK. You've been noticeably VERY absent for months.

**Comment by PurpleNinja225** [comment]
Seconded.

**Comment by ideologysec** [comment]
Autosquash appears to be the updated/newer version, integrates perfectly with GitHub Actions, and has a nicer merging model (imho)

**Comment by davestephens** [comment]
Interesting project!

I've actually been working on a restructure of the way applications are added to ansible-nas (from tasks to roles), which isolates applications away from each other. There'll be no enormous shared `all.yml` when I'm finished, which is where most of the merge and rebase pain is - so I'd like to see how that goes and can revisit this and other options if it doesn't help.
