### ISSUE TITLE
When github is down, unable to update ansible-nas

### ISSUE THREAD

**Issue by xerosanyam** [davestephens/ansible-nas#348]
If you're reporting an issue with execution of the Ansible-NAS playbook, please run the playbook with `-vvv`, and ideally isolate the problematic part with `--tags <ansible tag>` where possible.

**Describe the bug**

![image](https://user-images.githubusercontent.com/3167278/87279649-c1cef000-c50e-11ea-9a0b-6a3bad73b80d.png)

**Environment**
- Ansible-NAS revision (`git rev-parse --short HEAD`):
- Ansible version (paste the entire output of `ansible --version` on the machine you run the playbook from):
- Ansible-NAS operating system (`cat /etc/lsb-release` on the Ansible-NAS box) - _If this is anything other than Ubuntu 18.04 help will be limited_:
- Ansible-NAS kernel (`uname -a` on the Ansible-NAS box):
- Ansible-NAS Python version (`python --version` on the Ansible-NAS box):
- Ansible-NAS Docker version (`docker --version` on the Ansible-NAS box):
- Latest Docker logs (`journalctl -u docker.service` on the Ansible-NAS box):
- Are you running the playbook from a remote box or the Ansible-NAS box itself? 
- Vagrant version, if testing (`vagrant --version`):
- Ansible-NAS filesystems (`df -hT` on the Ansible-NAS box):
- Mounted filesystems (`mount` on the Ansible-NAS box)

**all.yml Variables**
- `docker_image_directory`:
- `docker_home`:
- `docker_storage_driver`:
- `samba_shares_root`:

**Expected behavior**
What should happen?

**Actual behavior**
What actually happens?

**Steps to reproduce**
What does someone need to do to reproduce this?

**Playbook Output**
Paste the output of the playbook at the problematic point. Surround it in triple backticks so that it's formatted correctly.

**Additional context**

**Comment by StopMotionCuber** [comment]
This is expected, you cannot download that role if the server you want to download from is down.
I'd say this should not be a big issue but with [stability of github](https://www.githubstatus.com/) lately this is rather annoying. Anyway, there is not much to do about this, other than waiting for GitHub to be up again

**Comment by xerosanyam** [comment]
yes, because of stability of GitHub these days it has become annoying.
cool, np thanks
