### ISSUE TITLE
Playbook run throws error for docker

### ISSUE THREAD

**Issue by Luckst4r** [davestephens/ansible-nas#349]
When I run
`ansible-playbook -i inventories/my-ansible-nas/inventory nas.yml -b -K`

Everything seemingly works out until I get a fail at the end. 

`TASK geerlingguy.docker : Add docker repository`

Says it failed due to apt cache update failure

I grepped around to find out more but couldn't

**Comment by bcurran3** [comment]
@Luckst4r - you need to "[grep](https://github.com/davestephens/ansible-nas/issues?q=is%3Aissue+is%3Aopen+20.04)" the open issues here. :)

REF: https://github.com/davestephens/ansible-nas/issues/200

**Comment by Luckst4r** [comment]
Why not state that 20.04 isn't supported in the docks?

**Comment by bcurran3** [comment]
@Luckst4r , I didn't write them but the docs state:

> Requirements
> Ansible NAS targets the latest Ubuntu LTS release, which is currently Ubuntu Server **18.04.3 LTS**.
> You can run Ansible-NAS on whatever you like, read the docs for more info. I use an HP Microserver.

Out of date since they say "currently."

But if you read the issue I pointed you to, and then the issue that it points to, you'll understand the current situation and when/how it will be resolved so that we can move on to using 20.04.

**Comment by Luckst4r** [comment]
Much appreciated!

I'll downgrade to 18.04

**Comment by bcurran3** [comment]
Sucks, I know!

I'll put in a PR to update the docs to help avoid the obvious confusion.

Let's hope @davestephens is OK and comes back from recess soon to play with Ansible-NAS some more soon.

**Comment by Luckst4r** [comment]
Much appreciated

**Comment by bcurran3** [comment]
Done!

https://github.com/davestephens/ansible-nas/pull/350

**Comment by davestephens** [comment]
Closing, this was prior to the Ubuntu 20.04 docker repos being available.
