### ISSUE TITLE
Update Traefik to using letsencrypt staging env by default

### ISSUE THREAD

**Issue by C-J1** [davestephens/ansible-nas#35]
When building and rebuilding containers that will reach out to letsencrypt for certs, we can very quickly hit the rate limit for production certs.

It is better to, by default, use the letsencrypt staging environment. This ensures that any testing and build processes being followed don't hit the prod rate limits. When you are ready to do a production run of your ansible playbook, you can just change the setting to use prod environment, delete your traefik container and let it run. This would assume that router port forwarding is setup and working (define test method in doco?)

Documentation and a "How To" for this would be required. Even if you run without firewall port forwarding, you can still consume rate limits if you aren't careful.

**Comment by davestephens** [comment]
I guess smashing the LetsEncrypt rate limit is techincally a bug as it's undesired...have tagged accordingly!

**Comment by C-J1** [comment]
I rebased this on to current master. @davestephens  Have a look when you can

**Comment by jesse-troy** [comment]
I'm very interested in this. Since it's been about a month, I figured I would bump to see if you guys have had any testing/success with this. I am unable to test this currently, but have been following this issue closely for a while.

**Comment by C-J1** [comment]
It works just fine. I finally migrated from FreeNAS over the weekend, and used this to ensure I was getting certs properly.

**Comment by davestephens** [comment]
On Kubernetes this is a pain in the bum - you have to manually delete the
staging certs before switching to the production ones.

Did you have to do this here it was it automatic?

**Comment by C-J1** [comment]
I manually deleted the acme.json file.

I can add some logic where we have a flag file for which mode it is in. Then if we see a switch between prod and staging, we can delete the acme file (backing up first of course).

**Comment by davestephens** [comment]
Ok cool.

It'd be nice if we could automate that, you know what the first issue will
be after flicking to staging certs by default :-)

**Comment by PurpleNinja225** [comment]
prolly can be closed as switching between staging and prod servers is as easy as editing ```traefik_acme_server:``` (Unless the manually deleting acme.json is still a requirement during the switch) I haven't tested this exactly yet, but I haven't encountered this issue yet in 2.X

**Comment by davestephens** [comment]
It can. I tested it a week or so ago and you still need to delete it, but it's documented here: https://github.com/davestephens/ansible-nas/blob/75103190ce4fb5c9187b8992ef41964e1a1729f3/roles/traefik/defaults/main.yml#L25
