### ISSUE TITLE
Typo in samba shares configuration

### ISSUE THREAD

**Issue by elliotpryde** [davestephens/ansible-nas#358]
**Describe the bug**
We're not setting `browseable: yes` in the samba shares config but instead `browsable: yes`. This results in no functional change since shares are browseable by default, but it's a typo nonetheless.

https://github.com/bertvv/ansible-role-samba

You can confirm this this is a typo by setting `browsable: no` and seeing that your share is still browsable, however setting `browseable: no` does what you'd expect.

**Comment by bcurran3** [comment]
@elliotpryde I tested browsable: no when I first setup ansible-nas and wondered why it didn't work as expected. Good find! Thanks.
