### ISSUE TITLE
Add YoutubeDL-Material for downloading youtube videos

### ISSUE THREAD

**Issue by elliotpryde** [davestephens/ansible-nas#366]
**Application you'd like to add:**
[YoutubeDL-Material](https://github.com/Tzahi12345/YoutubeDL-Material#Docker)

**Link to Docker image:**
https://hub.docker.com/r/tzahi12345/youtubedl-material

**Why you'd like this application added:**
Most people use youtube, and keeping backups of your favourite media is the reason a lot of people have a NAS server. Ultimately we all depend on youtube to serve any content we want, and sometimes that means videos are removed and never seen again.

**Comment by bcurran3** [comment]
It's been included in ansible-nas for about 7 months.

REF: https://github.com/davestephens/ansible-nas/commit/3bce0b7f5c7c515ba1b63b7d61bd3a04289a0e6f

**Comment by elliotpryde** [comment]
Ahh, I really should have revisited the docs before posting this 🤦‍♂️ 

Thanks for pointing that out!

**Comment by bcurran3** [comment]
![image](https://user-images.githubusercontent.com/14026600/100401736-2e0a4600-300f-11eb-8e9f-04aba929e3ec.png)
