### ISSUE TITLE
"An unexpected docker error occurred: \"host\" network_mode is incompatible with port_bindings"

### ISSUE THREAD

**Issue by gudrutis** [davestephens/ansible-nas#370]
# Issue
Following the documentation for [installation](https://davidstephens.uk/ansible-nas/installation/), after adding apps I wan to install into `inventories/my-ansible-nas/group_vars/nas.yml` and running `ansible-playbook -i inventories/my-ansible-nas/inventory nas.yml -b -K`, I  get task failed with a message "An unexpected docker error occurred: \"host\" network_mode is incompatible with port_bindings" with specific tasks.

# System
I experienced this error running it on `Ubuntu18.04` and `Ubuntu20.04` VMs on VirtualBox.

# Reason
Take a look at this [task](https://github.com/davestephens/ansible-nas/blob/85203e295f830d8f17bdd82927b96561145d7f5a/tasks/emby.yml) :
```yml
...
    ports:
      - "{{ emby_port_http }}:8096"
      - "{{ emby_port_https }}:8920"
    network_mode: host
...
```
Some of the app installation tasks have both `ports` and `network_mode`. I believe it is not allowed in the latest docker-compose syntax. Also, I don't know why, but [wallabag installation task](https://github.com/davestephens/ansible-nas/blob/master/tasks/wallabag.yml) does not have `network_mode: host`, thus it works without problems.

# Workaround
I deleted all `network_mode: host` line in `/tasks/*` by running this `grep -nr 'network_mode: .*host.*' tasks/` command. This allowed me to install the apps. However, I am still testing if the apps are working as they should.

**Comment by davestephens** [comment]
Deleting *all* `network_mode: host` definitions is perhaps a little heavy handed - there are definitely cases where it is required for applications to function correctly. 

What is an issue though (as you've highlighted) is where `network_mode: host` is defined **and** ports are defined too - this makes sense as using host network mode negates the need for ports being mapped via nat. 

Fixed in https://github.com/davestephens/ansible-nas/commit/3b5073f12f0e91c73d86d82f96e4847ba82e01f6

**Comment by Omar-Belghaouti** [comment]
@davestephens what to do when you have multiple container that talks to each other in localhost but with different ports?

**Comment by davestephens** [comment]
> @davestephens what to do when you have multiple container that talks to each other in localhost but with different ports?

Please raise a new issue with details and it'll get looked into

**Comment by Omar-Belghaouti** [comment]
> > @davestephens what to do when you have multiple container that talks to each other in localhost but with different ports?
> 
> Please raise a new issue with details and it'll get looked into

It's not Ansible issue, it's more about docker compose itself, in the earlier versions it was working just fine, but now you can't mix port bindings with `network_mode: host` anymore.

**Comment by davestephens** [comment]
Ansible NAS doesn't use docker compose. 

You can't have port bindings AND host mode networking. Previously ansible ignored the ports if you tried to specify it. I'm not sure how it behqves with the latest version. 

I'm not entirely sure what problem you're describing though, so a new issue with the actual issue would be helpful.
