### ISSUE TITLE
utorrent not downloading because `.incomplete` folder was not created during task

### ISSUE THREAD

**Issue by KenZhouGreat** [davestephens/ansible-nas#373]
By the ENV used by utorrent task for variable `dir_active: "/data/.incomplete"`, while the `./incomplete` folder was not created by the `utorrent` task.

**Environment**
- Ansible-NAS revision (`git rev-parse --short HEAD`): 85203e2
- Ansible version (paste the entire output of `ansible --version` on the machine you run the playbook from): 2.9.16
- Ansible-NAS operating system (`cat /etc/lsb-release` on the Ansible-NAS box) - _If this is anything other than Ubuntu 18.04 help will be limited_: Ubuntu 18.04
- Ansible-NAS kernel (`uname -a` on the Ansible-NAS box): Linux ansible-nas 5.4.0-60-generic
- Ansible-NAS Python version (`python --version` on the Ansible-NAS box): 2.7.17
- Ansible-NAS Docker version (`docker --version` on the Ansible-NAS box): Docker version 20.10.2, build 2291f61
- Are you running the playbook from a remote box or the Ansible-NAS box itself?  localhost
- Ansible-NAS filesystems (`df -hT` on the Ansible-NAS box):fuseblk
- Mounted filesystems (`mount` on the Ansible-NAS box)

**Expected behavior**
What should happen?
utorrent application should be downloading files

**Actual behavior**
What actually happens?
torrent file is successfully added but there is no downloaded block get written to the disk.

**Steps to reproduce**
What does someone need to do to reproduce this?
Using default utorrent build by ansible-nas

**Comment by bcurran3** [comment]
This is something for you to set in uTorrent Preferences/Directories/Put new downloads in:

**Comment by KenZhouGreat** [comment]
> This is something for you to set in uTorrent Preferences/Directories/Put new downloads in:

Yes, I know but the default ansible build doesn't cover it and leave the utorrent halt on download speed. So I created a PR to address this issue.
