### ISSUE TITLE
Ever thought about adding a nginx server serve as a `loadbalancer` for routing url to particular port?

### ISSUE THREAD

**Issue by KenZhouGreat** [davestephens/ansible-nas#375]
**Application you'd like to add:**
nginx for routing the URL. So instead of going `ansible-nas.local:9000`, we can do things like `ansible-nas.local/portainer`
**Link to Docker image:**
https://hub.docker.com/_/nginx
Above is the standard nginx, but I am making one for ansible-nas

**Why you'd like this application added:**
So instead of going `ansible-nas.local:9000`, we can do things like `ansible-nas.local/portainer`. I guess such change will be a good supplement to the home dashboard.

**Comment by PurpleNinja225** [comment]
ansible-nas uses traefik to handle load-balancing and routing urls. It's also built for handling network traffic for containerized environments. https://doc.traefik.io/traefik/v1.7/basics/ I don't think the default ansible-nas config for traefik goes over much of the features that are available for traefik, but the link above goes over the basics.

**Comment by davestephens** [comment]
Prior to using Traefik, I actually used nginx for a while. Using nginx (at
the time) was significantly more complicated and required multiple
containers to achieve the same functionality we get with Traefik now
(reverse proxy, automated LetsEncrypt certs, DNS updates etc).

One thing that may not be immediately apparent from your suggestion is that
a lot of apps don't like being run from a directory other than root, and/or
don't have the option to configure it automatically. This then results in
broken assets, or in some cases a complete failure to operate
correctly....which is obviously not ideal :-)

**Comment by Narcolapser** [comment]
Certainly, that is where having subdomains comes in handy. portainer.ansible-nas.com certainly is easier than ansible-nas:9000, but still operates on root so we avoid the issues mentioned. 

Here's an interesting thought though: which would be better for growing the ansible-nas community; more options or a single rally point? If we all are on traefik then we can all have the same bugs together, but we lose people who must have Nginx. Considering the idea here is simplicity I think sticking to just traefik is the better idea as those with cases technical enough to need Nginx are probably well equipped to handle it. 

@KenZhouGreat is there a particular case that Nginx handles that traefik doesn't that you need?

**Comment by KenZhouGreat** [comment]
Thanks for all the reply comments. I guess being a newbie to traefik make me wonder using nginx. My first thought was traefik was meant for external traffic (while I have not gone to that step yet) but surely I will try both nginx and traefik myself and come back with the detailed comparison. Thanks!

**Comment by davestephens** [comment]
Thanks - will close this in favour of traefik. Happy to revisit if there's something nginx can do that Traefik can't...
