### ISSUE TITLE
Default ansible task glances.yml has conflicting settings on network_mode/port over other missing volume env variable

### ISSUE THREAD

**Issue by KenZhouGreat** [davestephens/ansible-nas#376]
**Describe the bug**
Task glances.yml has settings of `network_mode: host` and docker port binding as 
      `ports:
      - "{{ glances_port_one }}:61208"
      - "{{ glances_port_two }}:61209"`
which results in:
`TASK [Glances Docker Container] ***********************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings
fatal: [ansible-nas]: FAILED! => {"changed": false, "msg": "An unexpected docker error occurred: \"host\" network_mode is incompatible with port_bindings"}`

**Environment**
- Ansible-NAS revision (`git rev-parse --short HEAD`): latest
- Ansible version (paste the entire output of `ansible --version` on the machine you run the playbook from): latest
- Ansible-NAS operating system (`cat /etc/lsb-release` on the Ansible-NAS box) - _If this is anything other than Ubuntu 18.04 help will be limited_: Ubuntu 18.04
- Ansible-NAS kernel (`uname -a` on the Ansible-NAS box): Linux ansible-nas 5.4.0-60-generic #67~18.04.1-Ubuntu SMP Tue Jan 5 22:01:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Ansible-NAS Python version (`python --version` on the Ansible-NAS box):
- Ansible-NAS Docker version (`docker --version` on the Ansible-NAS box):
- Latest Docker logs (`journalctl -u docker.service` on the Ansible-NAS box):
- Are you running the playbook from a remote box or the Ansible-NAS box itself? : local
- Vagrant version, if testing (`vagrant --version`):
- Ansible-NAS filesystems (`df -hT` on the Ansible-NAS box):
- Mounted filesystems (`mount` on the Ansible-NAS box)

**Expected behavior**
What should happen?
If mode `host` is used then no need to bind the port again in the task

**Actual behavior**
What actually happens?
Failure in build

**Steps to reproduce**
What does someone need to do to reproduce this?
enable glances and run playbook

**Playbook Output**
Paste the output of the playbook at the problematic point. Surround it in triple backticks so that it's formatted correctly.
```
TASK [Glances Docker Container] ***********************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings
fatal: [ansible-nas]: FAILED! => {"changed": false, "msg": "An unexpected docker error occurred: \"host\" network_mode is incompatible with port_bindings"}

PLAY RECAP ********************************************************************************************************************************
ansible-nas                : ok=51   changed=6    unreachable=0    failed=1    skipped=48   rescued=0    ignored=0   ```

**Comment by davestephens** [comment]
Fixed in https://github.com/davestephens/ansible-nas/commit/3b5073f12f0e91c73d86d82f96e4847ba82e01f6 👍
