### ISSUE TITLE
Enable discussions feature

### ISSUE THREAD

**Issue by PurpleNinja225** [davestephens/ansible-nas#384]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

In order to help keep a transient/shifting user-base updated and informed I think it would be beneficial to enable the discussions feature for the repo in the settings. It would make a great platform for a forumLite kinda thing, personally I'm not really ever on gitter, and scrolling/searching through the chat can be tedious. With discussions it would be a good place to get feedback or brainstorming on possible improvements without opening issues unnecessarily. Also would be a great way to fill out the documentation a bit more.

**Describe alternatives you've considered**
Gitter; I've used it before and seen it be used, but doesn't seem like a great way to interface with user-base (at least not without more active members)

**Additional context**

**Comment by davestephens** [comment]
Done! Happy to try it out and see how it goes. It looks very much like Discourse, which is no bad thing!

https://github.com/davestephens/ansible-nas/discussions
