### ISSUE TITLE
Requesting application user on merge requests

### ISSUE THREAD

**Issue by Vinibo** [davestephens/ansible-nas#391]
**Is your feature request related to a problem? Please describe.**
Running an application in a container (Docker) doesn't make it secure and most applications are running under the root user. 

**Describe the solution you'd like**
Require the creation of a system user for each new applications added going forward. User could be member of the ansible-nas group in order to read/write into samba folders. If someone wants to run a certain app as root, he could still use UID/GID 0 in its inventory. Since breaking current implementations is not possible, I would apply it to new merge requests.

**Describe alternatives you've considered**
Specifying UID for each applications in inventories. This solution doesn't scale well in my opinion as someone would have to modify the tasks to create users.

**Comment by davestephens** [comment]
I'm not entirely sold on this idea, being honest. It's a lot of extra admin for not a lot of gain, especially given that all users would be added to the same group, and therefore, have the same rights over your data.

I'd be interested to hear a little more about this, so I've created a discussion to track conversation: https://github.com/davestephens/ansible-nas/discussions/392
