### ISSUE TITLE
Transmission openvpn variables

### ISSUE THREAD

**Issue by georgejung** [davestephens/ansible-nas#431]
**Describe the bug**
Variable mis-match between defaults and tasks with transmission_with_openvpn_available_externally and in tasks the variable is transmission_open_available_externally.

I changed my defaults and took out the with. I should have edited the tasks to add the width in the traefik section at the bottom.

**Comment by eniad** [comment]
@georgejung Does #440 fix this?

**Comment by georgejung** [comment]
> @georgejung Does #440 fix this?

Yes it does. Thanks
