### ISSUE TITLE
With the fix for #253 watchtower_memory needs to be configured; default is broken

### ISSUE THREAD

**Issue by delgurth** [davestephens/ansible-nas#435]
While fixing https://github.com/davestephens/ansible-nas/issues/253, using the following commit the memory is configurable, but the default value for watchtower is not set:

https://github.com/davestephens/ansible-nas/commit/a645bd809feecb0bcada1c6344c5d964e0704759#diff-cbd16e0c3e395a05570307f304208e655255ee79bbe657241200e19e5d86defeR20

I'll make a pull request to fix this.

**Comment by davestephens** [comment]
Oops, good spot.
