### ISSUE TITLE
Grafana does not register in traefik correctly

### ISSUE THREAD

**Issue by delgurth** [davestephens/ansible-nas#437]
It seems that the grafana route in traefik has not been tested properly since the switch to traefik 2. At least  I assume this is the reason it no longer works for me. I'll make a pull request to fix it.

Current error message from traefik:

time="2021-03-02T20:18:39Z" level=error msg="field not found, node: grafana" providerName=docker container=grafana-9a84f86d61fc396680d15a2ff31b5e48901fc50e60487982251b2dd7230bfabb

**Comment by codebrewer** [comment]
You beat me to submitting a PR!

Did you also notice that the `stats.yml` config no longer works correctly with InfluxDB 2.x? There are a number of changes between InfluxDB 1.x and 2.x, the two most noticeable being that data is now stored by default at `/var/lib/influxdb2` rather than `/var/linux/influxdb` and that clients must now authenticate to post data (I see Traefik log 401 errors from Telegraf and get no data showing in Grafana).

InfluxDB has support for migrating data from 1.x to 2.x (see [here](https://hub.docker.com/_/influxdb?tab=description)) but I'm assuming that one reason this Grafana bug has been around for a while might be that Netdata is now favoured by Ansible NAS users? If that's the case then pinning the `influxdb` image at tag `1.8` might be the way to go (it would at least restore a working setup while updating the config to use the migration feature is considered/implemented).

**Comment by delgurth** [comment]
@codebrewer I just upgraded from a 1 year old git checkout and working from issue to issue. Got the traefik stuff working now (although there seems to be a concurrency issue there when getting a new certificate, yet another thing to debug but lower prio since it works now). Haven't looked at grafana, just got it working in traefik.

Also looking into a way to actually test the ansible-nas playbooks. Since the docker containers running does not say that it's actually working. I first experienced that last year when I added the gitlab container. It didn't function properly because the default 4Gb memory was only enough in case you also had 4Gb of swap space. My box didn't have any swap space, so gitlab didn't start.

**Comment by codebrewer** [comment]
@delgurth perhaps you'll be able to confirm the InfluxDB problem soon too then :smile:

@davestephens it would be a shame to leave Grafana broken so what's your opinion on how to fix the InfluxDB part of the problem? Pin at 1.8? Update the config to migrate existing users from 1.x to 2.x?

I think I'll use Netdata myself though (I'm mesmerised by all its pretty graphs...).

**Comment by davestephens** [comment]
@delgurth I'd be interested to know your thoughts. I have grand ideas of integration tests spinning up containers one by one and ensuring they work, but I've not got anywhere near typing any code yet. 

I have got an integration test GitHub action that runs the playbook in its entirety against a VM, that works but only tests the bare bones for the reasons above. 

@codebrewer does Influx update the data if it finds data from v1? If so it should just be a case of updating the mount path within the container...?

**Comment by iddinkwessel** [comment]
@codebrewer you are right, Grafana + InfluxDB does not work with the current setup. Haven't had time to look into the situation to see if I could fix it myself. 

@davestephens the validation the end result of the Ansible scripts seems to be out of scope for Ansible. For most roles within this repository a web-frontend is the end result. So I guess you can for example add [Cypress](https://www.cypress.io) scripts. But for non web-frontends I'm not sure how you should do that. And how to deal with roles that conflict with each other if you test them one by one? But testing them 1 by 1 is at least better than no testing at all.

Geerlingguy wrote some articles about this topic.
https://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github
https://www.jeffgeerling.com/blog/2018/testing-your-ansible-roles-molecule
https://www.jeffgeerling.com/blog/2019/how-add-integration-tests-ansible-collection-molecule

I'll have to read-up about the possibilities here. Molecule sounds like the way to go.

**Comment by codebrewer** [comment]
@delgurth pinning InfluxDB to tag `1.8` in `stats.yml` gets things working with the current setup _i.e._:

```yaml
    image: influxdb:1.8
```

@davestephens yes, data migration is apparently handled but think the new requirement for client authentication is probably the biggest challenge to getting things working with InfluxDB 2.x (although it probably needs no more than some additional env vars). I haven't had time to look into it so I don't know if - for example - the data migration is done in place or if it needs two volumes (source and destination) to me mounted. The page linked from my first comment seemed quite comprehensive on a quick skim.

**Comment by delgurth** [comment]
codebrewer: you are right, Grafana + InfluxDB does not work with the current setup. Haven't had time to look into the situation to see if I could fix it myself.

davestephens: the validation of the end result of the Ansible scripts seems to be out of scope for Ansible. For most roles within this repository a web-frontend is the end result. So I guess you can for example add Cypress scripts. But for non web-frontends I'm not sure how you should do that. And how to deal with roles that conflict with each other if you test them one by one? But testing them 1 by 1 is at least better than no testing at all.

Geerlingguy wrote some articles about this topic.
https://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github
https://www.jeffgeerling.com/blog/2018/testing-your-ansible-roles-molecule
https://www.jeffgeerling.com/blog/2019/how-add-integration-tests-ansible-collection-molecule

I'll have to read-up about the possibilities here. Molecule sounds like the way to go. 

-- replicated with correct account, sorry for the spam --
