### ISSUE TITLE
Mosquitto 2

### ISSUE THREAD

**Issue by georgejung** [davestephens/ansible-nas#448]
It looks like the eclipse mosquitto image has recently undergone a major version change to 2. Using the 'latest' tag gets v2.X which doesn't seem to play nicely with others, at least for me. I can't get my tasmota devices to communicate with the latest version (eclipse-mosquitto:latest) that is included in the task.yml.

I went in and changed it :1.6 and it seems to be working, at least my devices can connect now.

As I play more with it I'll update here.

**Comment by georgejung** [comment]
The solution was super easy! The mosquitto config file in the docker dir at least (and template config in the ansible-nas/files/mosquitto) needs to have the line 
listener 1883
added (or whatever port you want to use)
if you are using anonymous then you will also need to add: 
allow_anonymous true

After that it works the same as the older 1.X versions!

**Comment by davestephens** [comment]
Fixed, thanks!
