### ISSUE TITLE
motd.txt reverted to file from template with role migration

### ISSUE THREAD

**Issue by muonzoo** [davestephens/ansible-nas#450]
**Describe the bug**
Commit 46fe985d inadvertently changed the motd file from a template to a file. 

**Environment**
- Ansible-NAS revision (`git rev-parse --short HEAD`): 127d801
- Ansible version (paste the entire output of `ansible --version` on the machine you run the playbook from):
```bash
ansible 2.10.7
  config file = /Users/alan/Documents/scm/x/ansible-nas/ansible.cfg
  configured module search path = ['/Users/alan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/alan/.pyenv/versions/3.8.2/envs/ansible/lib/python3.8/site-packages/ansible
  executable location = /Users/alan/.pyenv/versions/ansible/bin/ansible
  python version = 3.8.2 (default, May  3 2020, 16:44:02) [Clang 11.0.0 (clang-1100.0.33.17)]
```
- Ansible-NAS operating system (`cat /etc/lsb-release` on the Ansible-NAS box) :
```bash
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
```
- Ansible-NAS kernel (`uname -a` on the Ansible-NAS box):
```bash
Linux _hostname_ 5.4.0-67-generic #75-Ubuntu SMP Fri Feb 19 18:03:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- Ansible-NAS Python version (`python --version` on the Ansible-NAS box): `Python 3.8.5`
- Ansible-NAS Docker version (`docker --version` on the Ansible-NAS box):  `Docker version 20.10.5, build 55c4c88`
- Latest Docker logs (`journalctl -u docker.service` on the Ansible-NAS box): N/A
- Are you running the playbook from a remote box or the Ansible-NAS box itself?  Remote
- Vagrant version, if testing (`vagrant --version`): N/A
- Ansible-NAS filesystems (`df -hT` on the Ansible-NAS box): N/A
- Mounted filesystems (`mount` on the Ansible-NAS box) : N/A

**all.yml Variables**
N/A
**Expected behavior**
Template fields in `motd.txt` should expand as expected.
**Actual behavior**
I see the ansible / template markup

**Steps to reproduce**
What does someone need to do to reproduce this?
Add the following line to motd and redeploy the motd.txt file:
`Deployed date: {{ ansible_date_time.iso8601 }}`

**Playbook Output**
Paste the output of the playbook at the problematic point. Surround it in triple backticks so that it's formatted correctly.
N/A it runs fine, the content isn't updated as expected.

**Additional context**
I have added two lines to `motd.txt` leveraging the fact that it is a template. The first line holds an env var expansion for a git tag showing me what version of ansible-nas is deployed to my NAS box. It is typically the output of `git describe --tags`. Deployments are handled by a shell script that always updates / redeploys the motd when other updates are deployed.

I have a PR to attach to this shortly (today) that should address this issue quickly. Opening for completeness.

**Comment by davestephens** [comment]
It was switched from `template` to `copy` because nothing is being templated. The fact `template` was used was a mistake. 

If you want to propose adjusting that behaviour as part of another PR then that's fine, but it's still not an issue with the project as it stands currently.

**Comment by muonzoo** [comment]
Is there a way to reopen this as an FR or should I just file an FR and PR? Sorry - first time contributing here.
