### ISSUE TITLE
Stats (Influx, Grafana, Telegraf)

### ISSUE THREAD

**Issue by georgejung** [davestephens/ansible-nas#454]
**Describe the bug**
A number of new releases re influxdb, telegraf, and grafana that are causing issues with the stats taks, specifically the ansible-nas dashboard.
The stats.yml file is using much new images than originally when the dashboard was made in April 2020.
The biggest issue seems to be influxdb v2 vs v1.x but there may be other compatibility issues.

**Expected behavior**
Expecting ansible-nas dashboard file to load and datasource connections to work.

**Actual behavior**
With influxdb v2 the connections are broken. Have not yet tested grafana and telegraf to determine issues.

**Steps to reproduce**
Run playbook as is.

**Additional context**
I modified the stats.yml using the following images: grafana/grafana:6.7.2, influxdb:1.6, and telegref:1.14  as my starting point as those images were all from early 2020 when the edits for the ansible-nas dashboard were added. These all seemed to work well off the bat. 
I am having an http timeout issue with HA and sometimes traefik, but I am not sure what's causing that, i think it may be the v1.6 of influx and the inmem index but I need to do more testing.

More to come as I play around with things.

P.S. I found my SMART logging already in the telegraf.conf I just needed to uncomment which was AWESOME!

**Comment by georgejung** [comment]
Turns out my timeout issues were caused by the version of influxdb. I am using 1.7.6 instead and it has been stable for 6 days now with no timeouts.

**Comment by davestephens** [comment]
Closing as Influxdb has been dropped in favour of Prometheus.
