### ISSUE TITLE
NextCloud Stability Problem: Help required on Upgrade and Backup

### ISSUE THREAD

**Issue by flammableliquids** [davestephens/ansible-nas#463]
NextCloud v15 Stability is problematic, and I want to find a recommended methodology on how to upgrade versions.
Can anyone help me?
(Preferrably portainer based instructions that work for ZFS)

Before even doing the ugprade, I thought it was a good idea to do a backup of NextCloud, but I cannot find the password for the mysql user, all I can find is a reference in the nextcloud.yml and nextcloud container config.php of "nextcloud-pass". I could really use some help here.

**Environment**
- Ansible-NAS revision 0f16c69
- Ansible version
ansible 2.5.1
  config file = [redacted]/ansible-nas/ansible.cfg
  configured module search path = [u'/home/[redacted]/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Feb 27 2021, 15:10:58) [GCC 7.5.0]
- Operating System Ubuntu 18.04.5 LTS
- kernel: 5.4.0-72-generic #80~18.04.1-Ubuntu SMP Mon Apr 12 23:26:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Docker version 20.10.6, build 370c289

**Comment by random-dwi** [comment]
If you want to upgrade nextcloud you have to update to next major version let the migration complete and then further to the next major version.

- change `nextcloud:14` to `nextcloud:15`
- run the container and check the logs: `docker logs -f nextcloud `
- after the migration completed, update image to `nextcloud:16` ...

For backup you can make a copy of `nextcloud_data_directory`

**Comment by tsjordan-eng** [comment]
Can we just update this repo to use the latest Nextcloud? Or make it a user variable?

**Comment by allthestairs** [comment]
> Can we just update this repo to use the latest Nextcloud? Or make it a user variable?

Defaulting to 'latest' can break the install if it skips a major version. It might be reasonable to include an ansible variant to change the tag to 'latest' with a warning that it can break things if you don't regularly pull updates for the container.

**Comment by flammableliquids** [comment]
I have upgrade my NextCloud installation to v21, and achieved much better application stability.
I was even thing about setting it to ":latest" and letting watchtower take over the regular updates of the application ongoing.

The only question I am now left with is MySQL.
Default anisble-nas install has it set to version 5.**7**, the nextcloud docs recommends v8 (I assume this means **5.8**, (but even if it doesn't the question still stands)).
The responsible thing in my mind is to repeat my method and update my MySQL installation until it is in-step with my NextCloud installation.

What would people recommend? Stay or upgrade? And what would be the recommended method of updating MySQL versions?

**Comment by flammableliquids** [comment]
For those in the future who hit this problem, my solution methodology was thus:

1) edit $ANSIBLE/roles/nextcloud/tasks/main.yml
1.1) changing line to - name: Nextcloud Docker Container
```
  docker_container:
    name: nextcloud
    image: nextcloud:<CurrentVersion++>
```
2) run the following command to do the update:
`sudo ansible-playbook -i inventories/my-ansible-nas/inventory nas.yml -b -K`
3) repeat 1 and 2 until I got to the version I wanted.

**Comment by PurpleNinja225** [comment]
>     1. Run the following command to do the update:
>        `sudo ansible-playbook -i inventories/my-ansible-nas/inventory nas.yml -b -K`
> 
>     2. Repeat until I got to the version I wanted.

Thanks for the workaround @flammableliquids ! Also remember for anyone who wants to use it that you can add the nextcloud tag (`-t nextcloud`) or any declared tag in nas.yml to the ansible-playbook command to have ansible only run the tagged tasks. 

As for upgrading nextcloud in some automated way with ansible is a (pretty complex, imo) task. I would recommend checking out Nextcloud's documentation on upgrading [here](https://docs.nextcloud.com/server/latest/admin_manual/maintenance/upgrade.html) But for me, 3 main highlights stick out that may potentially cause issues if not handled properly.

 
### *Nextcloud must be upgraded step by step:*
>        Before you can upgrade to the next major release, Nextcloud upgrades to the latest point release.
>        Then run the upgrade again to upgrade to the next major release’s latest point release.
>        You cannot skip major releases. Please re-run the upgrade until you have reached the highest available (or applicable)   >     release.
>       Example: 18.0.5 -> 18.0.11 -> 19.0.5 -> 20.0.2"

### *Not all enabled apps may be compatible*
>"...review third-party apps, if you have any, for compatibility with the new Nextcloud release. Any apps that are not developed by > Nextcloud show a 3rd party designation. Install unsupported apps at your own risk. Then, before the upgrade, all 3rd party apps > must be disabled. After the upgrade is complete you may re-enable them."

### *Manual steps during upgrade*
>Some operation can be quite time consuming. Therefore we decided not to add them to the normal upgrade process. We >recommend to run them manually after the upgrade was completed. Below you find a list of this commands.
