### ISSUE TITLE
ERROR! A playbook must be a list of plays

### ISSUE THREAD

**Issue by jmcsys** [davestephens/ansible-nas#486]
Hi David! Big fan been using this for a while.

Today I downloaded the most recent version

git clone https://github.com/davestephens/ansible-nas.git
cp -rfp ~/ansible-nas/inventories/sample ~/ansible-nas/inventories/my-ansible-nas
ansible-galaxy install -r ~/ansible-nas/requirements.yml

All good up until that point.

ansible-playbook -i ~/ansible-nas/inventories/my-ansible-nas/inventory ~/ansible-nas/inventories/my-ansible-nas/group_vars/nas.yml -b -K -vvvvvvvv

the above command errors out.

ERROR! A playbook must be a list of plays, got a <class 'ansible.parsing.yaml.objects.AnsibleMapping'> instead

The error appears to be in '/root/ansible-nas/inventories/my-ansible-nas/group_vars/nas.yml': line 13, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

# Example options
ansible_nas_hostname: ansible-nas
^ here

About 2 weeks ago I did the same steps and everything worked, but I didn't fully document everything I did, so I decided to redo it and take better notes. Is it possible the source has changed? Any help would be appreciated.

I am on a fresh linode server using Ubuntu 20 LTS, which again worked 2 weeks ago for me.

**Comment by davestephens** [comment]
Glad you're enjoying it!

Check your command to run the playbook - you need to pass in your variables nas.yml *and* the playbook nas.yml.

Step 8 here - https://github.com/davestephens/ansible-nas/blob/master/docs/installation.md

**Comment by jmcsys** [comment]
Man thanks for the super fast reply!

I thought I did it right
Step 8: ansible-playbook -i inventories/my-ansible-nas/inventory nas.yml -b -K

My command uses full paths and adds -vvv flags but otherwise looks the same
ansible-playbook -i ~/ansible-nas/inventories/my-ansible-nas/inventory ~/ansible-nas/inventories/my-ansible-nas/group_vars/nas.yml -b -K -vvvvvvvv

Just to be safe I also tried it just like your with the same result. Cd first to the directory ~/ansible-nas/inventories/my-ansible-nas/group_vars/

then run
ansible-playbook -i ~/ansible-nas/inventories/my-ansible-nas/inventory nas.yml -b -K -vvvvvvvv

Same Error

I don't understand when you said "you need to pass in your variables nas.yml and the playbook nas.yml. "

Are there two nas.yml files I need to reference?

**Comment by jmcsys** [comment]
A omg. So I made sure I was CDed into just ~/ansible-nas and then ran your command and it worked!
Could you explain why I needed to be in that directory?

**Comment by davestephens** [comment]
Your original command was this:

```
ansible-playbook -i ~/ansible-nas/inventories/my-ansible-nas/inventory ~/ansible-nas/inventories/my-ansible-nas/group_vars/nas.yml -b -K -vvvvvvvv
```

It should have been (step 8 in the docs):

```
ansible-playbook -i ~/ansible-nas/inventories/my-ansible-nas/inventory ~/ansible-nas/inventories/my-ansible-nas/group_vars/nas.yml nas.yml -b -K 
```
...from the playbook directory. 

Note the extra nas.yml. Ansible thought you were passing your variables file as the playbook.
