### ISSUE TITLE
log4j traefik

### ISSUE THREAD

**Issue by georgejung** [davestephens/ansible-nas#500]
I am only running a handful of apps externally via traefik and none seem to be impacted by log4j. However i do see that traefik has issued a patch.

I followed this, using the toml version (with square brackets) modifying my traefik.toml and i have a dynamic_conf.toml . I had to register with the traeifk pilot to get a token. 

I was getting an odd error with v2.4, something along these lines:
https://github.com/darkweak/souin/issues/144

as a result I upgraded to the latest 2.5.5 and it worked no problem.

Does any one know by quickly looking at the list of apps that we could have to know if they use java? Home Assisstant seems safe, though some custom integrations could possibly be vulnerable? Bitwarden is safe and Airsonic 10.6.2 is good.

**Comment by darkweak** [comment]
Does everything is good with Souin now ?

**Comment by georgejung** [comment]
> Does everything is good with Souin now ?

I was just using that issue as an example of the error I was getting with a different plugin. I can’t say as I’m not using that plugin. But I would assume so and I’ll definitely check out Souin:)

**Comment by davestephens** [comment]
Closing as not an issue
