### ISSUE TITLE
Firefly III image update

### ISSUE THREAD

**Issue by slowesc** [davestephens/ansible-nas#512]
After installation, Firefly page states:
The Firefly III image has moved
For the latest version of Firefly III, use fireflyiii/core:latest
For the develop (unstable) version of Firefly III, use fireflyiii/core:develop

My apologies for the inconvenience.
All the best,
James

**Comment by davestephens** [comment]
Thanks for the heads up - if you want to have a go at updating I'll accept
a PR to fix this. 👍
