### ISSUE TITLE
Nextcloud updating shenanigans

### ISSUE THREAD

**Issue by bibberp** [davestephens/ansible-nas#515]
Hello! This project has been amazing! It’s helped me to expand my knowledge base as well as provide some fun and rewarding tools  for my home server! Thank you Dave and all those that have    contributed.

Recently I upgraded my home server, actually I haven’t even moved anything yet, so it’s a fresh install of Ubuntu and a fresh install of Ansible-NAS. I have a few Nextcloud questions which seems to be a theme here.

1. How do I get rid of Nextcloud so that I can run the playbook to install anew with the “latest” tag rather than the “14” tag? I tried deleting the image and volumes and then updating to latest but I think it broke my installation. Now when I try to install with “latest” I get the error “It looks like you are trying to reinstall your Nextcloud. However the file CAN_INSTALL is missing from your config directory. Please create the file CAN_INSTALL in your config folder to continue.”
- I’m thinking that I’m getting this error because I tried to go from 14 to latest without removing everything. I don’t have any files or anything on this server so no risk of messing anything up.

2. Do I need to add the “latest” tag to the mysql container or can it stay on its default?

3. Will I have issues moving my pictures from Nextcloud 14 to 22? (Maybe 23 —not sure what the latest is) and are there any good guides that the community recommends to move things over?

Thanks again!

**Comment by flammableliquids** [comment]
[I think this link will help](https://github.com/davestephens/ansible-nas/issues/463)

**Comment by bibberp** [comment]
Thank you for that! I did end up finding that link and it was really useful. I wasn’t very confident in my ability to upgrade and then move all of my photos to the new machine. What I ended up doing was kind of convoluted but I did get my photos moved. Now I just have it set to latest and let watchtower update it for me

**Comment by davestephens** [comment]
Nextcloud is (was?) a giant pain in the ass if you fall more than one version behind. As such, I've updated Ansible-NAS to use the stable container, rather than a specific version (it was pinned to v14). Combined with watchtower, this should keep users from falling behind, and into upgrade hell!
