### ISSUE TITLE
support for ubuntu 22.04 unable to import zfs pool as rw. Will only import as read-only due to unsupported features

### ISSUE THREAD

**Issue by dkuchay** [davestephens/ansible-nas#524]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by davestephens** [comment]
Can you provide more information? Filling out the correct issue template would be a useful start.

**Comment by dkuchay** [comment]
Please disregard and close. I didnt see mentions of jammy in the docs so I made a bad assumption. Just installed the PPA and see that it resolved well after upgrading.
