### ISSUE TITLE
Documentation Request: mount and config storage devices

### ISSUE THREAD

**Issue by TimJ0212** [davestephens/ansible-nas#533]
**Is your feature request related to a problem? Please describe.**
I'm unsure how to mount drives.

**Describe the solution you'd like**
A short documentation of how to mount your storage devices.

**Additional context**
I'm looking for best practices on how to mount your storage and what to configure about that.
I would love to see something in the documentation about that.

**Comment by davestephens** [comment]
There are lots of docs already on ZFS - https://davidstephens.uk/ansible-nas/zfs/zfs_overview, but automating it is outside of the scope of Ansible-NAS.
