### ISSUE TITLE
Dashy configuration lost on container restart

### ISSUE THREAD

**Issue by pypeaday** [davestephens/ansible-nas#540]
**Describe the bug**
If the Dashy container is rebuilt then the configuration is lost since there's no docker volume specified

**Environment**
- Are you running the playbook from a remote box or the Ansible-NAS box itself?  Remote (comments below on why this is critical to the issue)

**Expected behavior**
The Dashy config should ideally persist beyond the life of the container

**Actual behavior**
The config is lost with the container

**Steps to reproduce**
Spin up Dashy, make a home page, restart Dashy container, voila... config gone

**Additional context**
I think part of this issue stems from the following:
1. The Dashy docs do not super clearly specify even using a volume in the docker-compose example... it's there but commented out
2. I think there's going to be an issue with remote deployment as I'm not sure how changes made to the config on a remote server can be synced back with the repo because if that can't happen then even with a volume we're right back where we started since the default config would override the one configured with the Dashy live editor.

**Comment by nicpayne713** [comment]
I believe these are relevant from the docker logs (extracted from portainer)

```
 ERROR  Failed to compile with 2 errors11:54:00 AM

These relative modules were not found:

* ../../public/conf.yml in ./src/utils/ConfigAccumalator.js

* ../public/conf.yml in ./src/router.js

 ERROR  Build failed with errors.

error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

ERROR: "build-watch" exited with 1.

error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

yarn run v1.22.15

$ npm-run-all --parallel build-watch start

$ vue-cli-service build --watch --mode production

$ node server

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

 Error, unable to validate 'conf.yml' 

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

⚠️ Config file could not be found at ./public/conf.yml
```

right so part of the issue as well is that dashy won't create a default config if there's a volume mount **For just a directory** specified - which was my ideal solution
