### ISSUE TITLE
Switch from booleans enclosed in strings to standard booleans

### ISSUE THREAD

**Issue by HitLuca** [davestephens/ansible-nas#547]
There is some inconsistency when looking at the variables used in this project:
- on one hand you have `*_enabled: bool` variables for enabling applications
- on the other hand you have `*_available_externally: "bool"` for allowing applications to be routed through traefik

From my testing switching from `"bool"` to `bool` shouldn't be an issue, as the only change needed is in the traefik label: going from `: {{ *_available_externally }}` to `: {{ *_available_externally | string }}`

**Comment by HitLuca** [comment]
I can make a PR for it and I made sure it's not a breaking change:

having `{{ variable | string }}` for traefik would result in `true` if `variable: "true"` and `True` if `variable: true`, both accepted

**Comment by davestephens** [comment]
Agree that this is a weird one - I'm scraping the memory banks a bit but I think at the time (a couple of years ago) I didn't know about the `| string` thing. Happy to accept a PR replacing it with best practice!
