### ISSUE TITLE
Discussions page missing for project, although mentioned on the main readme

### ISSUE THREAD

**Issue by HitLuca** [davestephens/ansible-nas#553]
Looks like we are missing a discussions section on the project, which imo would be nice if a user has a small issue that doesn't require a full issue being created. If a discussions page is off the table then the project readme should be fixed

**Comment by davestephens** [comment]
I disabled it as it wasn't particularly helpful, and people used it to complain about their PRs not being approved, lack of updates on the project etc.  I don't have enough time as it is, let alone wasting brain power on reading peoples' complaints about free software :-)
