### ISSUE TITLE
NextCloud non core apt packages

### ISSUE THREAD

**Issue by flammableliquids** [davestephens/ansible-nas#560]
Every time I run the playbook and nextcloud is processed, a problem crops up:
I need to re-install the following packages: smbclient libsmbclient libmagickcore-6.q16-6-extra, and then change the config file for magik to allow processing of PDF's. 
One solution I was able to find was to use something like a [docker file](https://stackoverflow.com/questions/47903079/how-to-install-packages-from-docker-compose), but the whole point of ansible is to automate things like this, but I can't seem to figure out how.
This is very frustrating.

**Environment**
- Ansible-NAS revision (`3352773`):
- operating system Ubuntu 20.04.4 LTS
- Docker version 20.10.17, build 100c701
- Running the playbook on the box itself. 
- Vagrant not installed
running on ZFS

**Comment by davestephens** [comment]
What version of Ubuntu are you using?

**Comment by flammableliquids** [comment]
Updated ticket with OS Version (Copy and paste mistake)

**Comment by flammableliquids** [comment]
NextCloud does not install these packages by default, it considers them an optional security risk and recommends you install them yourself.

I guess this is less of a bug, and more of a help / feature request...

**Comment by davestephens** [comment]
You're right, but it's a bug with the nextcloud docker image, not ansible-nas. Installing those packages onto your Ansible-nas will have no effect on what goes on in the nextcloud docker image. 

I'm going to close and recommend re-raising it on the nextcloud repo. It looks like a similar issue [here](https://github.com/nextcloud/docker/issues/633) has been closed with no fix, I have no idea why!

Perhaps there's an alternative nextcloud image we could use, I'd happily accept a PR if a better one can be found. I don't use it myself though so will need to rely on others for testing.

**Comment by flammableliquids** [comment]
The nextcloud core image is "paired down" to not include anything that is of even middling security risk.

**Comment by davestephens** [comment]
It looks like nextcloud provide an all in one image ("aio") - do you want to give that a go and raise a PR if it looks suitable? Alternatively there's a Linuxserver flavour too, their images are usually pretty good.

**Comment by bcurran3** [comment]
> NextCloud does not install these packages by default, it considers them an optional security risk and recommends you install them yourself.
> 
> I guess this is less of a bug, and more of a help / feature request...

This could be done by adding a variable to run a command in the container. The nextcloud setup task could then run the command (i.e. apt install smbclient). The variable could default to "" so that nothing actually runs.

I'll look into doing this in the future.

**Comment by jackgray** [comment]
As this issue has been open for a year, what is the current recommended way to offer SMB mounting for a Nextcloud instance on docker?

I built my company's entire storage solution on the premise that SMB mounting was an included feature in Nextcloud... It seems from this thread I may need to install a user-modded container, which could make me lose my entire configuration (I just had to migrate servers and Nextcloud security features did not allow migrating the database and auth configs).

I don't understand, though, every other feature can be installed from within Nextcloud frontend in the Apps section. Why not SMB/CIFS? If Nextcloud says that SMB mounting is an offered feature, you should not need to hack anything to use that feature....

**Comment by davestephens** [comment]
The issue isn't open :) It was closed as the issue first mentioned above is with Nextcloud (and the bad images they provide) not Ansible-NAS itself. There is a link to Nextcloud's issue too, where you can maybe fathom out why they haven't solved this problem themselves. 

I haven't used Nextcloud myself in a long time (for reasons above) but my guess is that the SMB mounting requires additional packages that aren't in the image, whereas other apps do not. As above, happy to accept non-hacky PRs to fix this, but I won't doing any work on this myself.
