### ISSUE TITLE
Dockerfile functionality

### ISSUE THREAD

**Issue by flammableliquids** [davestephens/ansible-nas#563]
I don't truly understand how Ansible takes the YML files in roles/{appName}/tasks/main.yml, so I can't really figure out how to do handle the following problem myself:

I would like to use DockerFiles.
Specifically for things like installing packages repeatedly needed for an application 

- [for example in nextcloud](https://hub.docker.com/r/indiehosters/nextcloud/dockerfile/) 
- or installation of[ NextCloud Facial recognition](https://github.com/matiasdelellis/facerecognition/wiki/Docker) 
- or getting glances to show docker container statuss, (https://glances.readthedocs.io/en/latest/aoa/docker.html?highlight=docker)

without understanding how to get main.yml configured to work with a dockerfile, the image will be rolled backed to baseline and my changes lost. (Sometimes even when watchtower does an update)

**Comment by davestephens** [comment]
Dockerfiles are a manifest file used to build the Docker images that Ansible-NAS uses to spin up running applications (containers). Ansible-NAS doesn't directly use the Dockerfiles. 

Docker 101 is an awesome place to learn the basics of Docker: https://www.docker.com/101-tutorial/
