### ISSUE TITLE
Add support for NFS shares

### ISSUE THREAD

**Issue by scotws** [davestephens/ansible-nas#57]
Ansible-NAS currently exports Samba shares, but some people live in a world of Linux machines and would rather work with NFS instead. An ansible thingie for that would make life easier. See https://advishnuprasad.com/blog/2016/03/29/setup-nfs-server-and-client-using-ansible/ for an example and https://help.ubuntu.com/community/SettingUpNFSHowTo for the background information.

(I dimly remember reading a recommendation that you shouldn't use the same directory/share for NFS and Samba because, uh, it was very bad and mice will eat your brain or something. Not sure if we should check for that?)

**Comment by davestephens** [comment]
I've actually got a branch with this done on my desktop at home...Have deployed to my own Ansible-NAS and it seems to be working nicely. Just need to test a little more and will push soon 👍

**Comment by davestephens** [comment]
I've just pushed #36268743776dbcdef02510f2994921402392fbf7 which includes NFS support. I've been using it myself for a bit and it seems OK - would appreciate some testing!
