### ISSUE TITLE
Enable Universe repository task not working on ubuntu server 22.04

### ISSUE THREAD

**Issue by HitLuca** [davestephens/ansible-nas#585]
Looks like the `Enable Universe Repository` task in the `ansible-nas-general` role isn't working on Ubuntu Server 22.04. When running the ansible playbook it just hangs at that step indefinitely. Removing the step and enabling the universe repository manually fixes the issue

**Comment by davestephens** [comment]
I can't remember for the life of me why the universe repo was added :-/

**Comment by codemeister64** [comment]
same for me
Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-48-generic x86_64)

**Comment by davestephens** [comment]
Give it a bash now. Had this locally and forgot to commit....
