### ISSUE TITLE
https://davestephens.github.io/ansible-nas documentation page is broken

### ISSUE THREAD

**Issue by AlanAndre** [davestephens/ansible-nas#605]
**Describe the bug**
https://davestephens.github.io/ansible-nas documentation page is broken

![Screenshot_1](https://user-images.githubusercontent.com/64380900/189134608-f4d4fd05-2417-4f0d-ba6b-e0a7e53865d6.png)

**Comment by AlanAndre** [comment]
fixed

**Comment by davestephens** [comment]
Thanks for closing - you beat me to it! (it was fixed today after I updated the new domain's DNS)
