### ISSUE TITLE
Playbook run fails attempting to stop nomad

### ISSUE THREAD

**Issue by fetherolfjd** [davestephens/ansible-nas#621]
**Describe the bug**
The playbook run ends with a failure attempting to stop nomad.

```
TASK [nomad : Start Nomad] **************************************************************************************************************************
skipping: [ansible-nas]

TASK [nomad : Stop Nomad] ***************************************************************************************************************************
fatal: [ansible-nas]: FAILED! => {"changed": false, "msg": "Could not find the requested service nomad: host"}

PLAY RECAP ******************************************************************************************************************************************
ansible-nas                : ok=78   changed=5    unreachable=0    failed=1    skipped=122  rescued=0    ignored=0 
```

**Expected behavior**
It should not error.

**Actual behavior**
What actually happens?

**Steps to reproduce**
Don't have nomad enabled and run `nsible-playbook -i inventories/<your-nas>/inventory nas.yml -b -K`

**Comment by davestephens** [comment]
The conditionals for this are in the task file:

https://github.com/davestephens/ansible-nas/blob/master/roles/nomad/tasks/main.yml

...the idea being it'll stop and start nomad based on the variable setting. 

There are other roles that have been updated to this new format, but I've not finished them all yet...

**Comment by fetherolfjd** [comment]
Yes, there are conditionals in the task file, but it still attempts to stop the container when not enabled. Is PR #622 not the way to fix this?

**Comment by davestephens** [comment]
That's by design - if you look at the hello_world role you can see how I'd like them structured going forward.

`thing_enabled == true` - starts the thing. `thing_enabled == false` - stops the thing. A common complaint historically has been that thing_enabled starts the thing, but would then need stopping manually from the Ansible-NAS box if it was no longer wanted. With the "new" way, this is no longer required.

**Comment by fetherolfjd** [comment]
Makes sense. Though it's still unclear to me why I'm getting the failure for the nomad service. Is it just Ansible trying to stop a service that's not running or doesn't exist?

**Comment by fetherolfjd** [comment]
Would something like this be appropriate?
```
- name: Get the list of services
  service_facts:

- name: Stop service
  systemd:
    name: <service_name_here>
    state: stopped
  when: "'<service_name_here>.service' in services"
```
Source: https://stackoverflow.com/a/65748512

**Comment by davestephens** [comment]
This should now be fixed properly, sorry for the delay.
