### ISSUE TITLE
Unable to start service docker

### ISSUE THREAD

**Issue by manderso7** [davestephens/ansible-nas#63]
**Short problem description**

Docker daemon is unable to start on Ubuntu 18.10.

**Environment**
- Ansible-NAS revision (`git rev-parse --short HEAD`): `183fee3`
- Ansible version (paste the entire output of `ansible --version` on the machine you run the playbook from):
```
ansible 2.6.5
  config file = /home/manderso/ansible-nas/ansible.cfg
  configured module search path = [u'/home/manderso/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
```
  python version = `2.7.15+ (default, Oct  2 2018, 22:12:08) [GCC 8.2.0]`

- Ansible-NAS operating system (`uname -a` on the Ansible-NAS box):
`Linux anderson_nas 4.18.0-16-generic #17-Ubuntu SMP Fri Feb 8 00:06:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

- Ansible-NAS Python version (`python --version` on the Ansible-NAS box):`Python 2.7.15+`

- Vagrant version, if testing (`vagrant --version`)

**Expected behavior**

Docker should start. Also, expecting a service file in /etc/systemd/system/, but no docker* exists in that location.

**Actual behavior**

Docker does not start, also no docker* exists in etc/systemd/system/.

**Steps to reproduce**

Run playbook on Ubuntu 18.10?

**Playbook Output**

```
TASK [geerlingguy.docker : Ensure Docker is started and enabled at boot.] *****************************************************************************************************
task path: /home/manderso/.ansible/roles/geerlingguy.docker/tasks/main.yml:18
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: manderso
<localhost> EXEC /bin/sh -c 'echo ~manderso && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/manderso/.ansible/tmp/ansible-tmp-1552048474.75-45135276588821 `" && echo ansible-tmp-1552048474.75-45135276588821="` echo /home/manderso/.ansible/tmp/ansible-tmp-1552048474.75-45135276588821 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/system/systemd.py
<localhost> PUT /home/manderso/.ansible/tmp/ansible-local-29160_HKPmy/tmp9JoKVl TO /home/manderso/.ansible/tmp/ansible-tmp-1552048474.75-45135276588821/systemd.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/manderso/.ansible/tmp/ansible-tmp-1552048474.75-45135276588821/ /home/manderso/.ansible/tmp/ansible-tmp-1552048474.75-45135276588821/systemd.py && sleep 0'
<localhost> EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=jmjugdguhbelnzhmmojntibzfwohebda] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-jmjugdguhbelnzhmmojntibzfwohebda; /usr/bin/python3 /home/manderso/.ansible/tmp/ansible-tmp-1552048474.75-45135276588821/systemd.py'"'"' && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/manderso/.ansible/tmp/ansible-tmp-1552048474.75-45135276588821/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "daemon_reload": false, 
            "enabled": true, 
            "force": null, 
            "masked": null, 
            "name": "docker", 
            "no_block": false, 
            "state": "started", 
            "user": false
        }
    }, 
    "msg": "Unable to start service docker: Job for docker.service failed because the control process exited with error code.\nSee \"systemctl status docker.service\" and \"journalctl -xe\" for details.\n"
}

PLAY RECAP ********************************************************************************************************************************************************************
localhost                  : ok=18   changed=0    unreachable=0    failed=1 
```
```
systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2019-03-08 07:34:41 EST; 7min ago
     Docs: https://docs.docker.com
  Process: 31129 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
 Main PID: 31129 (code=exited, status=1/FAILURE)

Mar 08 07:34:41 anderson_nas systemd[1]: docker.service: Service RestartSec=2s expired, scheduling restart.
Mar 08 07:34:41 anderson_nas systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
Mar 08 07:34:41 anderson_nas systemd[1]: Stopped Docker Application Container Engine.
Mar 08 07:34:41 anderson_nas systemd[1]: docker.service: Start request repeated too quickly.
Mar 08 07:34:41 anderson_nas systemd[1]: docker.service: Failed with result 'exit-code'.
Mar 08 07:34:41 anderson_nas systemd[1]: Failed to start Docker Application Container Engine.
```
```
journalctl -xe
Mar 08 07:34:41 anderson_nas systemd[1]: Listening on Docker Socket for the API.
-- Subject: Unit docker.socket has finished start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit docker.socket has finished starting up.
-- 
-- The start-up result is RESULT.
Mar 08 07:34:41 anderson_nas systemd[1]: docker.service: Start request repeated too quickly.
Mar 08 07:34:41 anderson_nas systemd[1]: docker.service: Failed with result 'exit-code'.
Mar 08 07:34:41 anderson_nas systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit docker.service has failed.
-- 
-- The result is RESULT.
Mar 08 07:34:41 anderson_nas systemd[1]: docker.socket: Failed with result 'service-start-limit-hit'.
```

**Comment by davestephens** [comment]
18.10 isn't supported because it's not an LTS release, I'd happily accept a PR adding support for it if you're willing to work on it. 

As for the actual issue, what is your `docker_home` and `docker_storage_driver` set to? The latter will need to be set accordingly for the former. Without seeing the actual Docker logs I'd guess it's that...

**Comment by manderso7** [comment]
Thanks for the reply. The docker_home var is set to /mnt/sea4pool/docker, which exists and has a data dir, but my normal account doesn't have rights to view it. The docker_storage_driver is set to zfs, which is what the mount is.
`manderso@anderson_nas:~/ansible-nas$ ls -al /mnt/sea4pool/docker
total 12
drwxr-xr-x 3 root     root     4096 Mar  8 07:06 .
drwxr-xr-x 4 manderso manderso 4096 Mar  8 07:06 ..
drwx--x--x 7 root     root     4096 Mar  8 07:34 data
manderso@anderson_nas:~/ansible-nas$ ls -al /mnt/sea4pool/docker/data
ls: cannot open directory '/mnt/sea4pool/docker/data': Permission denied
manderso@anderson_nas:~/ansible-nas$ vim group_vars/all.yml
manderso@anderson_nas:~/ansible-nas$ sudo ls -al /mnt/sea4pool/docker/data
[sudo] password for manderso:
total 28
drwx--x--x 7 root root 4096 Mar  8 07:34 .
drwxr-xr-x 3 root root 4096 Mar  8 07:06 ..
drwx------ 2 root root 4096 Mar  8 07:06 containers
drwx------ 4 root root 4096 Mar  8 07:06 plugins
drwx------ 2 root root 4096 Mar  8 07:34 runtimes
drwx------ 2 root root 4096 Mar  8 07:34 tmp
drwx------ 2 root root 4096 Mar  8 07:13 tmp-old
`
I'm running the ansible command w/ my normal account, could that be why it's not allowing the docker daemon to start? I thought the script asked for my password to run sudo.
Also, I'd love to help w/ a pull request, but I'm not sure how to start that. Sorry, quite a noob.

**Comment by manderso7** [comment]
This is weird because you're pulling the same version of geerlingguy's docker that he posted to get past this exact error. Frustrating. #[https://github.com/geerlingguy/ansible-role-docker/issues/97](https://github.com/geerlingguy/ansible-role-docker/issues/97)

**Comment by manderso7** [comment]
So I was wrong, the docker_home variable was set for /mnt/sea4pool/docker, and that's on the local drive, not the zfs mount. I moved the docker_home variable to /mnt/sea4pool/media/docker, kept the zfs docker_storage_driver, but running the ansible playbook again gives me the same error. What should I do?

**Comment by manderso7** [comment]
And I'm good. I needed to change the data-root directory in /etc/docker/daemon.json to the correct location, and the daemon was able to start afterwards.
Thanks for your help. And I'll be happy to work w/ you getting 18.10 certified.

**Comment by davestephens** [comment]
This is reasonably difficult to debug without the actual error that Docker is throwing. The error you're seeing is systemd telling you that Docker won't start - ie it's a result of another issue, not THE issue. 

What does `sudo journalctl -fu docker.service` output? 

And in answer to your other question, yes you need to run the playbook as a root user, or a user that can elevate to root and supply the relevant ansible-playbook switches.

**Comment by davestephens** [comment]
Doh, just hit f5.  Glad you got it sorted, completely forget about `data-root`, sorry!
