### ISSUE TITLE
Ansible script fails while creating container

### ISSUE THREAD

**Issue by manderso7** [davestephens/ansible-nas#64]
Running script gets to creating * container, then waits for a bit, then fails. If the script is run again, that container is created and the next container fails.

**Environment**
- Ansible-NAS revision (`git rev-parse --short HEAD`): `183fee3`
- Ansible version (paste the entire output of `ansible --version` on the machine you run the playbook from): 
```
ansible 2.6.5
  config file = /home/manderso/ansible-nas/ansible.cfg
  configured module search path = [u'/home/manderso/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15+ (default, Oct  2 2018, 22:12:08) [GCC 8.2.0]
```

- Ansible-NAS operating system (`uname -a` on the Ansible-NAS box): `Linux anderson_nas 4.18.0-16-generic #17-Ubuntu SMP Fri Feb 8 00:06:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

- Ansible-NAS Python version (`python --version` on the Ansible-NAS box): `Python 2.7.15+`

- Vagrant version, if testing (`vagrant --version`)

**Expected behavior**

Ansible script should complete and containers be created on first try.
**Actual behavior**

Container fails to create on first try. 
**Steps to reproduce**

Run the ansible playbook.

```
TASK [Watchtower Docker Container] *****************************************************************************************************************************************************************
task path: /home/manderso/ansible-nas/tasks/watchtower.yml:2
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: manderso
<localhost> EXEC /bin/sh -c 'echo ~manderso && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/manderso/.ansible/tmp/ansible-tmp-1552064809.88-273857946939080 `" && echo ansible-tmp-1552064809.88-273857946939080="` echo /home/manderso/.ansible/tmp/ansible-tmp-1552064809.88-273857946939080 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/cloud/docker/docker_container.py
<localhost> PUT /home/manderso/.ansible/tmp/ansible-local-7452RnWvzH/tmp4Yu2Ay TO /home/manderso/.ansible/tmp/ansible-tmp-1552064809.88-273857946939080/docker_container.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/manderso/.ansible/tmp/ansible-tmp-1552064809.88-273857946939080/ /home/manderso/.ansible/tmp/ansible-tmp-1552064809.88-273857946939080/docker_container.py && sleep 0'
<localhost> EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=oqitjckthtyotebiaxnjjxdvlxvdphtb] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-oqitjckthtyotebiaxnjjxdvlxvdphtb; /usr/bin/python3 /home/manderso/.ansible/tmp/ansible-tmp-1552064809.88-273857946939080/docker_container.py'"'"' && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/manderso/.ansible/tmp/ansible-tmp-1552064809.88-273857946939080/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_b9ewlwjq/ansible_module_docker_container.py", line 1986, in container_create
    new_container = self.client.create_container(image, **create_parameters)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/container.py", line 135, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python3.6/dist-packages/docker/api/container.py", line 145, in create_container_from_config
    res = self._post_json(u, data=config, params=params)
  File "/usr/local/lib/python3.6/dist-packages/docker/client.py", line 198, in _post_json
    return self._post(url, data=json.dumps(data2), **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docker/client.py", line 135, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 567, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_version": "auto",
            "auto_remove": false,
            "blkio_weight": null,
            "cacert_path": null,
            "capabilities": null,
            "cert_path": null,
            "cleanup": false,
            "command": "--schedule '0 0 5 * * *' --debug",
            "cpu_period": null,
            "cpu_quota": null,
            "cpu_shares": null,
            "cpuset_cpus": null,
            "cpuset_mems": null,
            "debug": false,
            "detach": true,
            "devices": null,
            "dns_opts": null,
            "dns_search_domains": null,
            "dns_servers": null,
            "docker_host": "unix://var/run/docker.sock",
            "domainname": null,
            "entrypoint": null,
            "env": {
                "TZ": "America/New_York"
            },
            "env_file": null,
            "etc_hosts": null,
            "exposed_ports": null,
            "force_kill": false,
            "groups": null,
            "hostname": null,
            "ignore_image": false,
            "image": "v2tec/watchtower",
            "init": false,
            "interactive": false,
            "ipc_mode": null,
            "keep_volumes": true,
            "kernel_memory": null,
            "key_path": null,
            "kill_signal": null,
            "labels": null,
            "links": null,
            "log_driver": null,
            "log_options": null,
            "mac_address": null,
            "memory": "1g",
            "memory_reservation": null,
            "memory_swap": null,
            "memory_swappiness": null,
            "name": "watchtower",
            "network_mode": null,
            "networks": null,
            "oom_killer": null,
            "oom_score_adj": null,
            "paused": false,
            "pid_mode": null,
            "privileged": false,
            "published_ports": null,
            "pull": true,
            "purge_networks": false,
            "read_only": false,
            "recreate": false,
            "restart": false,
            "restart_policy": "unless-stopped",
            "restart_retries": null,
            "security_opts": null,
            "shm_size": null,
            "ssl_version": null,
            "state": "started",
            "stop_signal": null,
            "stop_timeout": null,
            "sysctls": null,
            "timeout": 60,
            "tls": false,
            "tls_hostname": "localhost",
            "tls_verify": false,
            "tmpfs": null,
            "trust_image_content": false,
            "tty": false,
            "ulimits": null,
            "user": null,
            "userns_mode": null,
            "uts": null,
            "volume_driver": null,
            "volumes": [
                "/var/run/docker.sock:/var/run/docker.sock"
            ],
            "volumes_from": null,
            "working_dir": null
        }
    },
    "msg": "Error creating container: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)"
}

PLAY RECAP *****************************************************************************************************************************************************************************************
localhost                  : ok=46   changed=3    unreachable=0    failed=1
```

**Comment by davestephens** [comment]
What Docker version is this on? And I'm assuming Ubuntu 18.10 given the kernel version? 
Do containers start reliably when not through Ansible?
Does it work if you use 18.04 LTS? Is there a reason you can't use 18.04 LTS?

**Comment by manderso7** [comment]
docker --version
Docker version 18.09.3, build 774a1f4
Containers do start reliably, though tautulli, plex and watchtower don't get an IP.

```
docker ps
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS                                                              NAMES
74f5f202b0b7        haugene/transmission-openvpn:latest   "dumb-init /etc/open…"   3 hours ago         Up 3 hours          0.0.0.0:9091->9091/tcp, 8888/tcp, 0.0.0.0:51413->51413/tcp         transmission-openvpn
e171c2a8c00c        linuxserver/heimdall:latest           "/init"                  26 hours ago        Up 26 hours         0.0.0.0:10080->80/tcp, 0.0.0.0:10443->443/tcp                      heimdall
33c998231ca4        linuxserver/transmission              "/init"                  42 hours ago        Up 22 hours         0.0.0.0:9092->9091/tcp, 0.0.0.0:51414->51413/tcp                   transmission
b60fd6b187d9        linuxserver/tautulli                  "/init"                  42 hours ago        Up 42 hours                                                                            tautulli
fd95470fb081        linuxserver/plex                      "/init"                  42 hours ago        Up 42 hours                                                                            plex
a463eb05ad5e        v2tec/watchtower                      "/watchtower --sched…"   43 hours ago        Up 42 hours                                                                            watchtower
e741e33123a4        traefik:1.7                           "/traefik"               43 hours ago        Up 42 hours         0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:8083->8083/tcp   traefik
b7254668795a        portainer/portainer                   "/portainer"             43 hours ago        Up 4 minutes        0.0.0.0:9000->9000/tcp                                             portainer
```

Yeah, I'm going to try 18.04 sometime today and report back.

**Comment by manderso7** [comment]
As expected, 18.04 setup successfully. I had to edit the cloudflare-ddns task from 512mb to 512MB to get past a failure during setup: 
`TASK [Cloudflare Dynamic DNS Container] *****************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to convert memory to bytes: human_to_bytes() failed to convert 512mb. Value is not a valid string (expect MB or M)"}

`
Looks like the script has completed successfully afterwards. However, going to IP:80 or https://ip:443 brings up a 404 page not found in text in the browser window. I can browse to ip:10080 and view heimdall, but none of the services are setup, is that expected behavior?
Glances doesn't have an IP, nor does plex, watchtower, or tautulli. And the cloudflare-ddns keeps saying restarting (1) x seconds ago in status for a docker ps command.
`manderso@poweredge:~/ansible-nas$ sudo docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS                          PORTS                                                              NAMES
3f0ddb654db3        joshava/cloudflare-ddns:latest   "/bin/sh -c '/cloudf…"   4 minutes ago       Restarting (1) 21 seconds ago                                                                      cloudflare-ddns
9d930b374e91        haugene/transmission-openvpn     "dumb-init /etc/open…"   5 minutes ago       Up 5 minutes                    0.0.0.0:9091->9091/tcp, 8888/tcp, 0.0.0.0:51413->51413/tcp         transmission-openvpn
87e882a582ac        airsonic/airsonic:latest         "tini -- run.sh"         About an hour ago   Up About an hour (healthy)      0.0.0.0:4040->4040/tcp                                             airsonic
0f8e7ea57767        guacamole/guacamole:0.9.14       "/opt/guacamole/bin/…"   About an hour ago   Up About an hour                0.0.0.0:8090->8080/tcp                                             guacamole
ff4e38667056        guacamole/guacd:0.9.14           "/usr/local/sbin/gua…"   About an hour ago   Up About an hour                4822/tcp                                                           guacamole-guacd
b46610d19cc2        mysql:5.7                        "docker-entrypoint.s…"   About an hour ago   Up About an hour                3306/tcp, 33060/tcp                                                guacamole-mysql
528b9d080e7c        grafana/grafana                  "/run.sh"                About an hour ago   Up About an hour                0.0.0.0:3000->3000/tcp                                             grafana
e6e9dd718f85        telegraf                         "/entrypoint.sh tele…"   About an hour ago   Up About an hour                8092/udp, 8125/udp, 8094/tcp                                       telegraf
fa9f5c491541        influxdb                         "/entrypoint.sh infl…"   About an hour ago   Up About an hour                0.0.0.0:8086->8086/tcp                                             influxdb
cb27e0bdc3c9        gitea/gitea:1.6                  "/usr/bin/entrypoint…"   About an hour ago   Up About an hour                0.0.0.0:222->22/tcp, 0.0.0.0:3001->3000/tcp                        gitea
19e573a829ae        mysql:5.7                        "docker-entrypoint.s…"   About an hour ago   Up About an hour                3306/tcp, 33060/tcp                                                gitea-mysql
83726d095440        netdata/netdata                  "/usr/sbin/run.sh"       About an hour ago   Up About an hour                0.0.0.0:19999->19999/tcp                                           netdata
a13666cebf18        linuxserver/radarr               "/init"                  About an hour ago   Up About an hour                0.0.0.0:7878->7878/tcp                                             radarr
256344d1b7f1        linuxserver/sonarr               "/init"                  About an hour ago   Up About an hour                0.0.0.0:8989->8989/tcp                                             sonarr
29984de6b37c        linuxserver/tautulli             "/init"                  2 hours ago         Up 2 hours                                                                                         tautulli
2fc735f8cf38        nicolargo/glances                "/bin/sh -c 'python …"   47 hours ago        Up About an hour                                                                                   glances
e171c2a8c00c        linuxserver/heimdall:latest      "/init"                  2 days ago          Up 2 hours                      0.0.0.0:10080->80/tcp, 0.0.0.0:10443->443/tcp                      heimdall
33c998231ca4        linuxserver/transmission         "/init"                  2 days ago          Up 2 hours                      0.0.0.0:9092->9091/tcp, 0.0.0.0:51414->51413/tcp                   transmission
fd95470fb081        linuxserver/plex                 "/init"                  2 days ago          Up 2 hours                                                                                         plex
a463eb05ad5e        v2tec/watchtower                 "/watchtower --sched…"   2 days ago          Up 2 hours                                                                                         watchtower
e741e33123a4        traefik:1.7                      "/traefik"               2 days ago          Up 2 hours                      0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:8083->8083/tcp   traefik
b7254668795a        portainer/portainer              "/portainer"             2 days ago          Up 2 minutes                    0.0.0.0:9000->9000/tcp                                             portainer
`

**Comment by manderso7** [comment]
So I'm dumb and finally realized that the services that don't have IPs are actually started on the machine and using the local machines IP.
Thanks for your patience and assistance!

**Comment by davestephens** [comment]
Didn't get time to reply to you yesterday, but yeah, that's what I was going to say. 

Tautulli and Plex use "host mode" networking, where the containers bind to your main system NIC so no requirement to map any ports. Watchtower has no ports/network requirements as it's simply a watcher for updating images, and the others you can see - Docker NAT's the ports from the main interface to the Docker NIC through iptables, hence you see an "IP" of 0.0.0.0 (a.k.a. all interfaces) as they are accessible externally to the Ansible-NAS box.

Glad you got it sorted! :+1:
