### ISSUE TITLE
conditional check 'airsonic_enabled is true' failed

### ISSUE THREAD

**Issue by lexxish** [davestephens/ansible-nas#640]
**Describe the bug**
I'm getting the following error when running `ansible-playbook -i inventories/my-ansible-nas/inventory nas.yml -b -K`

**Environment**
- Ansible-NAS revision (`git rev-parse --short HEAD`):
- Ansible version (paste the entire output of `ansible --version` on the machine you run the playbook from):
- Ansible-NAS operating system (`cat /etc/lsb-release` on the Ansible-NAS box) - _Support won't be provided for non-LTS releases of Ubuntu_: `Ubuntu 18.04.6 LTS`
- Ansible-NAS kernel (`uname -a` on the Ansible-NAS box): `Linux ansible-nas 4.15.0-201-generic #212-Ubuntu SMP Mon Nov 28 11:29:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Ansible-NAS Python version (`python --version` on the Ansible-NAS box): `2.7.17`
- Ansible-NAS Docker version (`docker --version` on the Ansible-NAS box): `Docker version 20.10.22, build 3a2c30b`
- Are you running the playbook from a remote box or the Ansible-NAS box itself? `local`
- Vagrant version, if testing (`vagrant --version`): `not installed`

**Expected behavior**
Ansible should start the hello world application

**Actual behavior**
Ansible throws an error

**Steps to reproduce**
Follow the install instructions and enable the hello world application

**Playbook Output**
```
TASK [airsonic : Create Airsonic Directories] **************************************************************************
fatal: [ansible-nas]: FAILED! => {"msg": "The conditional check 'airsonic_enabled is true' failed. The error was: template error while templating string: no test named 'true'. String: {% if airsonic_enabled is true %} True {% else %} False {% endif %}\n\nThe error appears to be in '/home/user/ansible-nas/roles/airsonic/tasks/main.yml': line 4, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  block:\n    - name: Create Airsonic Directories\n      ^ here\n"}
```

**Additional context**
I'm not sure if this is a versioning or a configuration issue.

**Comment by davestephens** [comment]
What ansible version are you using? (The first two questions that aren't
filled in)

**Comment by lexxish** [comment]
> What ansible version are you using? (The first two questions that aren't filled in)

Here is the output of `ansible-playbook --version`:

```
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current
version: 3.6.9 (default, Nov 25 2022, 14:10:45) [GCC 8.4.0]. This feature will be removed from ansible-core in version
2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ansible-playbook [core 2.11.12]
  config file = /home/user/ansible-nas/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.9 (default, Nov 25 2022, 14:10:45) [GCC 8.4.0]
  jinja version = 2.10
  libyaml = True
```

**Comment by lexxish** [comment]
@davestephens any thoughts on what the error might be? Or is there any more information I should post?

**Comment by badcrc** [comment]
This happened to me this week after upgrading ansible-nas, you need to upgrade the ansible version and the jinja2 package as well.

**Comment by lexxish** [comment]
> This happened to me this week after upgrading ansible-nas, you need to upgrade the ansible version and the jinja2 package as well.

Thanks, you're correct updating to Ubuntu 20.04 and installing ansible from PPA worked. I had accidentally installed Ubuntu 18.04 previously. 

However, then I got this error: #621 and had to enable nomad to get around it, which doesn't seem like a good long term solution.
