### ISSUE TITLE
Transmission 4.3 curl fatal error pthread_create

### ISSUE THREAD

**Issue by georgejung** [davestephens/ansible-nas#642]
Transmission with openvpn in Nov 2022 updated to an image that seems to require a newer docker version than what is packaged in ansible-nas. As a result we get this error, or similar.

Running with VPN_CONFIG_SOURCE auto
Provider NORDVPN has a bundled setup script. Defaulting to internal config
Executing setup script for NORDVPN
INFO: OVPN: Checking curl installation
thread.c:84: fatal error: pthread_create() failed: Operation not permitted

https://github.com/haugene/docker-transmission-openvpn/issues/2410

**Environment**
- Ansible-NAS revision (`git rev-parse --short HEAD`):
- Ansible version (paste the entire output of `ansible --version` on the machine you run the playbook from):
- Ansible-NAS operating system (`cat /etc/lsb-release` on the Ansible-NAS box) - 20.04.2 LTS
- Ansible-NAS kernel (`uname -a` on the Ansible-NAS box): 5.4.0-135-generic #152
- Ansible-NAS Python version (`python --version` on the Ansible-NAS box): 
- Ansible-NAS Docker version (`docker --version` on the Ansible-NAS box): 20.10.3
- Latest Docker logs (`journalctl -u docker.service` on the Ansible-NAS box):
- Are you running the playbook from a remote box or the Ansible-NAS box itself?  From NAS box itself
- Vagrant version, if testing (`vagrant --version`):
- Ansible-NAS filesystems (`df -hT` on the Ansible-NAS box):
- Mounted filesystems (`mount` on the Ansible-NAS box)

**Expected behavior**
What should happen? - Transmission should load, connect to VPN and load GUI.

**Actual behavior**
What actually happens? OpenVPN can't connect

**Steps to reproduce**
What does someone need to do to reproduce this? Upgrade latest version of transmission on older version of docker.

**Playbook Output**
Paste the output of the playbook at the problematic point. Surround it in triple backticks so that it's formatted correctly.

**Additional context**
Downgrading to v 4.1 of the transmission_openvpn image will fix it. 

Alternatively in the tasks/main.yml you can add two lines to get it to work and use the latest version. I added them after capabilities, before restart_policy. (No space after seccomp:
security_opts
  - seccomp:unconfined

Lastly, if you upgrade docker version it should work, but I didn't try as I didn't want to break other things.

**Comment by davestephens** [comment]
Ansible-NAS doesn't pin your version of docker, or any other system
package, it just installs them. From memory the docker role I use behaves
the same way.

Please can you try upgrading docker through apt and see how it goes?

**Comment by davestephens** [comment]
Closing as received no further info.
