### ISSUE TITLE
wrong version of vaultwarden

### ISSUE THREAD

**Issue by choskeli** [davestephens/ansible-nas#643]
ansible-nas is using the "bitwardenrs/server" image for vaultwarden. This image is deprecated in favor of "vaultwarden/server". Further, "bitwardenrs/server" doesn't appear to be compatible with many of the upstream bitwarden clients such as the Chrome extension or Firefox extension since it throws an "unable to fetch" error when attempting to login. 

The docs also still refer to bitwarden-rs. To ease transition and solve the incorrect naming, perhaps we could consider adding vaultwarden.ansible-nas-domain.com as a new route with the new container.

**Comment by st0nedB** [comment]
I do encounter the same issue (can't login via bitwarden apps/browser addons) and tracked it down to this:
- newer bitwarden clients refuse to login with the self-hosted server, see [this issue](https://github.com/dani-garcia/vaultwarden/issues/3082)
> Bitwarden has released new client versions which are not compatible with Vaultwarden version bellow 1.27.0.
> Since version 1.27.0 Vaultwarden supports these new clients and has many bugs fixed and features added.

- the `bitwardenrs/server ` image is [depcrecated](https://hub.docker.com/r/bitwardenrs/server) (as mentioned by @choskeli)

As the used image is deprecated and is no longer updated, anyone using a newer client will be unable to login anywhere but in the browser. 
A reasonable course of action would be to replace the `bitwarden_rs/server` image with the maintained [`vaultwarden/server`](https://hub.docker.com/r/vaultwarden/server). This ensures our Homelabs run up-to-date software and can use a up-to-date version of the bitwarden client software.

**Comment by choskeli** [comment]
I tried updating the image to bitwardenrs/server but surprisingly I'm still seeing the fetch error on most clients. What is strange is that the android client actually works fine.

I also checked the logs to verify I'm on Vaultwarden 1.27.0 which is latest. I'd expect to see an issue already on Vaultwarden's GitHub if this is an issue with Vaultwarden itself so this requires more investigation

**Comment by st0nedB** [comment]
From what I see, [`bitwardenrs/server`](https://hub.docker.com/r/bitwardenrs/server) is just as outdated as `bitwarden/server` (both roughly 9 months since the last update. So I think that solution won't work.

**Comment by choskeli** [comment]
> From what I see, [`bitwardenrs/server`](https://hub.docker.com/r/bitwardenrs/server) is just as outdated as `bitwarden/server` (both roughly 9 months since the last update. So I think that solution won't work.

I was using vaultwarden/server I just had a typo in my URL. Everything is working now and it's just a 1 line change to the code. I made a pull request

**Comment by st0nedB** [comment]
Can confirm the proposed solution worked for me. I just switched the image from `bitwardenrs/server` to `vaultwarden/server` and re-ran the playbook (with `--tag bitwarden`). Afterwards the logins work again as expected; my existing vaults are still there and working.
