### ISSUE TITLE
Is there any AutoBackup Roles?

### ISSUE THREAD

**Issue by cyrsis** [davestephens/ansible-nas#649]
**Is your feature request related to a problem? Please describe.**
Everything actually runs very well over a year for me, is there a solution for auto-backup for the Synology?

**Describe the solution you'd like**
Is there a Role to auto backup to ZFS? Just for the storage share

**Describe alternatives you've considered**
I did manual copy , end up with lot of permission error here and there

**Additional context**
I scew up my NAS with ran out the space error

**Comment by davestephens** [comment]
I'm not clear what you're looking to back up to where - feel free to reopen with more info.
