### ISSUE TITLE
Gotify self-hosted push notifications

### ISSUE THREAD

**Issue by davestephens** [davestephens/ansible-nas#65]
Could be used for notifications generated by Ansible-NAS, check out https://github.com/gotify/server.

**Comment by bcurran3** [comment]
REF: https://hub.docker.com/r/gotify/server

I'm looking into this.

**Comment by bcurran3** [comment]
I've done this one. I'll get the PR in later tonight or tomorrow.

**Comment by bcurran3** [comment]
Done.

https://github.com/davestephens/ansible-nas/pull/194
https://github.com/davestephens/ansible-nas/pull/195
https://github.com/davestephens/ansible-nas/pull/196
https://github.com/davestephens/ansible-nas/pull/197
https://github.com/davestephens/ansible-nas/pull/198
https://github.com/davestephens/ansible-nas/pull/199

**Comment by bcurran3** [comment]
New ORGANIZED PR done:
https://github.com/davestephens/ansible-nas/pull/264
