### ISSUE TITLE
Nextcloud Optimization 

### ISSUE THREAD

**Issue by bibberp** [davestephens/ansible-nas#653]
Nextcloud seems like it could run faster, I see there is a page 
https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html 
with different optimizations to make it run better, as well as a nextcloud all in one container which purports to have all the the optimizations ready made for you. 

Is there any interest or plans to incorporate some of the optimizations or am I on my own? I’ve managed so far to stay pretty stock ansible-nas and I’m hesitant to move away from that

**Comment by viktor-c** [comment]
For my install I added a redis container
I can imagine enabling PHP OPcache
and maybe use php-fpm image instead of apache, but here I have some problem configuring traefik. I thought I can use nextcloud-fpm only with traefik as reverse proxy... I'm still testing there

**Comment by eugeis** [comment]
I see tow warnings in nextcloud admin overview about reverse proxy:

The reverse proxy header configuration is incorrect, or you are accessing Nextcloud from a trusted proxy. If not, this is a security issue and can allow an attacker to spoof their IP address as visible to the Nextcloud. Further information can be found in the [documentation ↗](https://docs.nextcloud.com/server/25/go.php?to=admin-reverse-proxy).

I solution is described here:
https://github.com/nextcloud/docker/issues/1384

Would it be possible to integrate the solution to ansible-nas nextcloud deployment?
Thanks

**Comment by khartahk** [comment]
> For my install I added a redis container I can imagine enabling PHP OPcache and maybe use php-fpm image instead of apache, but here I have some problem configuring traefik. I thought I can use nextcloud-fpm only with traefik as reverse proxy... I'm still testing there

@viktor-c Here's my WIP solution: https://github.com/khartahk/ansible-nas/pull/9/files

@eugeis About the trusted_proxies - I've added this to my config.php
```
'trusted_domains' => 
  array (
    0 => 'xxx.yyy.0.z:8080', //server IP on LAN
    1 => 'nextcloud.domain.tld',
),
'trusted_proxies' => 
  array (
    0 => '172.17.0.0/16', //this is the docker network
    1 => 'xxx.yyy.0.0/24', //my LAN
  ),
  'forwarded_for_headers' => 
  array (
    0 => 'X-Forwarded-For',
    1 => 'HTTP_X_FORWARDED_FOR',
  ),
```

**Comment by davestephens** [comment]
I (personally) have no plans to do any work on Nextcloud. I don't use it and have previously wasted a lot of time trying to fix their crappy containers. That said - if someone wants to do some work to make it better (in a non-hacky way) I'm more than happy to accept PRs.
