### ISSUE TITLE
Make Ansible-NAS more appliance like

### ISSUE THREAD

**Issue by khartahk** [davestephens/ansible-nas#659]
**Is your feature request related to a problem? Please describe.**
I would like to start developing some additional functionality that would make Ansile-NAS more appliance like. Is this something you are considering? I would be willing to lend a hand or two.

**Describe the solution you'd like**
For example I have already created a separate Ansible playbook that includes ansible-nas later on but pre-configures some stuff automatically and installs Cockpit as a WEB GUI for users less knowledgeable to allow them to at least update the system and set shared samba or NFS folders.

**Describe alternatives you've considered**
Create my own project and re-use ansible-nas using include.

**Comment by davestephens** [comment]
Thanks for your thoughts - I don't want to move configuration away from Ansible - the point of Ansible-NAS is that your NAS setup is in code. If config is moved out to web guis, then the next time you run the playbook, it'll be trying to reset the changes the gui has made. 


Happy to discuss further if you have more ideas, but not really keen on changing the direction of the project at this point.

**Comment by khartahk** [comment]
Hey, not really changing, more like adding options. I would not change anything but the ability to disable samba / nfs setup and installation and add cockpit to allow to manage them and run updates of packages. I can prepare an MR (as I'm already doing so with --skip-tags). I would just move my changes directly into ansible-nas and you can then review them.

All I need is to add the base config for samba (a few lines of config only) so that cockpit can start using samba properly immediatly.
