### ISSUE TITLE
Docker error

### ISSUE THREAD

**Issue by DraconPern** [davestephens/ansible-nas#66]
Docker error

error with docker when running ansible

**Environment**
- Ansible-NAS revision (`git rev-parse --short HEAD`): d7f97ae
- Ansible version (paste the entire output of `ansible --version` on the machine you run the playbook from): ansible 2.5.1
- Ansible-NAS operating system (`cat /etc/lsb-release` on the Ansible-NAS box) - _If this is anything other than Ubuntu 18.04 help will be limited_: Ubuntu 18.04.2 LTS
- Ansible-NAS kernel (`cat /etc/lsb-release` on the Ansible-NAS box): 
- Ansible-NAS Python version (`python --version` on the Ansible-NAS box): 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
- Ansible-NAS Docker version (`docker --version` on the Ansible-NAS box): Docker version 18.09.3, build 774a1f4
- Vagrant version, if testing (`vagrant --version`)
- Are you running the playbook from a remote box or the Ansible-NAS box itself? box itself
What should happen?

Unknown, first time

What actually happens?

What does someone need to do to reproduce this?
ansible-playbook -i inventory nas.yml -b -K -vvv

**Playbook Output**

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "daemon_reload": false,
            "enabled": true,
            "masked": null,
            "name": "docker",
            "no_block": false,
            "state": "started",
            "user": false
        }
    },
    "msg": "Unable to start service docker: Job for docker.service failed because the control process exited with error code.\nSee \"systemctl status docker.service\" and \"journalctl -xe\" for details.\n"
}

**Comment by davestephens** [comment]
Hi,

Please can you check out #63 and see if that helps you?

Cheers
David

**Comment by DraconPern** [comment]
Unfortunately the info in #63 isn't so great.  I fixed it by deleting the docker (are you assuming people who use this knows docker?) config, changing all.yml and rerunning ansible.  Ansible doesn't seem to fix a broken docker config?  I haven't used ansible.  The default value of all.yml isn't too sensible in that regards if the system is ru

**Comment by davestephens** [comment]
Seems pretty clear to me, check the last comment regarding `data-root`.

I think you sent your message before you meant to so not entirely sure what you're referring to - but if there's something you think that isn't sensible then I'll gladly accept a PR to fix it.
