### ISSUE TITLE
Add Photoprism

### ISSUE THREAD

**Issue by guipguia** [davestephens/ansible-nas#665]
**Is your feature request related to a problem? Please describe.**
No, just adding new application

**Describe the solution you'd like**
Implement role for Photoprism, following project guidelines.

**Describe alternatives you've considered**
None

**Additional context**
I added it to my own project, and seems to be a good idea to share it with everyone else 😄 

I already have everything in my own branch, but I can't push it to your repo. Can I have permissions so I can create a PR ?

**Comment by davestephens** [comment]
Thanks for your contribution - you don't need any additional permissions to raise a PR against Ansible-NAS - that's the point of PRs, so you can propose a change without having direct access.
