### ISSUE TITLE
Wrong loadbalancer port in `hello_world` example?

### ISSUE THREAD

**Issue by she11sh0cked** [davestephens/ansible-nas#671]
Correct me if I'm wrong, but shouldn't the loadbalancer be on port 8000?

https://github.com/davestephens/ansible-nas/blob/91725cb524cc4ee87c290fd6a86951f5ca9b495e/roles/hello_world/tasks/main.yml#L28C76-L28C76

**Comment by davestephens** [comment]
Doh, good spot.
