### ISSUE TITLE
Again Docker Error

### ISSUE THREAD

**Issue by thebadgateway** [davestephens/ansible-nas#68]
Please, I need help. I'm new to Linux. Please step explain how to fix the error. I didn't know how to solve it.
https://github.com/davestephens/ansible-nas/issues/66
https://github.com/davestephens/ansible-nas/issues/63

Docker error

error with docker when running ansible

**Environment**
- Ansible-NAS revision (`git rev-parse --short HEAD`):
- Ansible version (paste the entire output of `ansible --version` on the machine you run the playbook from): ansible 2.5.1
- Ansible-NAS operating system (`cat /etc/lsb-release` on the Ansible-NAS box) - _If this is anything other than Ubuntu 18.04 help will be limited_: Ubuntu 18.04.2 LTS
- Ansible-NAS kernel (`cat /etc/lsb-release` on the Ansible-NAS box): Ubuntu 18.04.2 LTS
- Ansible-NAS Python version (`python --version` on the Ansible-NAS box): Python 2.7.15rc1
- Ansible-NAS Docker version (`docker --version` on the Ansible-NAS box): Docker version 18.09.3, build 774a1f4 
- Vagrant version, if testing (`vagrant --version`)
- Are you running the playbook from a remote box or the Ansible-NAS box itself? 

Unknown, first time

What actually happens?

What does someone need to do to reproduce this?
ansible-playbook -i inventory nas.yml -b -K -vvv

Playbook Output

fatal: [localhost]: FAILED! => {
"changed": false,
"invocation": {
"module_args": {
"daemon_reload": false,
"enabled": true,
"masked": null,
"name": "docker",
"no_block": false,
"state": "started",
"user": false
}
},
"msg": "Unable to start service docker: Job for docker.service failed because the control process exited with error code.\nSee "systemctl status docker.service" and "journalctl -xe" for details.\n"
}

**Comment by davestephens** [comment]
Per the error message, what does `journalctl -xe` output?

What filesystem are you using on your Ansible-NAS box? If it's not ZFS then you need to update `docker_storage_driver` per the instructions in all.yml (and issue #63 that you linked). You probably want `overlay2`.

**Comment by thebadgateway** [comment]
```
-- Результат: RESULT.
мар 23 11:03:26 ansible-nas anacron[25242]: Anacron 2.3 started on 2019-03-23
мар 23 11:03:26 ansible-nas anacron[25242]: Normal exit (0 jobs run)
мар 23 11:10:29 ansible-nas dhclient[1738]: DHCPREQUEST of 172.16.213.128 on ens33 to 172.16.213.254 port 67 (xid=0x73a94604)
мар 23 11:10:29 ansible-nas dhclient[1738]: DHCPACK of 172.16.213.128 from 172.16.213.254
мар 23 11:10:29 ansible-nas NetworkManager[1259]: <info>  [1553339429.1767] dhcp4 (ens33):   address 172.16.213.128
мар 23 11:10:29 ansible-nas NetworkManager[1259]: <info>  [1553339429.1768] dhcp4 (ens33):   plen 24 (255.255.255.0)
мар 23 11:10:29 ansible-nas NetworkManager[1259]: <info>  [1553339429.1768] dhcp4 (ens33):   gateway 172.16.213.2
мар 23 11:10:29 ansible-nas NetworkManager[1259]: <info>  [1553339429.1769] dhcp4 (ens33):   lease time 1800
мар 23 11:10:29 ansible-nas NetworkManager[1259]: <info>  [1553339429.1769] dhcp4 (ens33):   nameserver '172.16.213.2'
мар 23 11:10:29 ansible-nas NetworkManager[1259]: <info>  [1553339429.1769] dhcp4 (ens33):   domain name 'localdomain'
мар 23 11:10:29 ansible-nas NetworkManager[1259]: <info>  [1553339429.1769] dhcp4 (ens33):   wins '172.16.213.2'
мар 23 11:10:29 ansible-nas NetworkManager[1259]: <info>  [1553339429.1769] dhcp4 (ens33): state changed bound -> bound
мар 23 11:10:29 ansible-nas dbus-daemon[1124]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='db
мар 23 11:10:29 ansible-nas dhclient[1738]: bound to 172.16.213.128 -- renewal in 844 seconds.
мар 23 11:10:29 ansible-nas systemd[1]: Starting Network Manager Script Dispatcher Service...
-- Subject: Начинается запуск юнита NetworkManager-dispatcher.service
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Начат процесс запуска юнита NetworkManager-dispatcher.service.
мар 23 11:10:29 ansible-nas dbus-daemon[1124]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
мар 23 11:10:29 ansible-nas systemd[1]: Started Network Manager Script Dispatcher Service.
-- Subject: Запуск юнита NetworkManager-dispatcher.service завершен
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Процесс запуска юнита NetworkManager-dispatcher.service был завершен.
-- 
-- Результат: RESULT.
мар 23 11:10:29 ansible-nas nm-dispatcher[25286]: req:1 'dhcp4-change' [ens33]: new request (1 scripts)
мар 23 11:10:29 ansible-nas nm-dispatcher[25286]: req:1 'dhcp4-change' [ens33]: start running ordered scripts...
мар 23 11:17:01 ansible-nas CRON[25335]: pam_unix(cron:session): session opened for user root by (uid=0)
мар 23 11:17:01 ansible-nas CRON[25336]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
мар 23 11:17:01 ansible-nas CRON[25335]: pam_unix(cron:session): session closed for user root
мар 23 11:21:17 ansible-nas systemd-resolved[890]: Using degraded feature set (UDP) for DNS server 172.16.213.2.
мар 23 11:21:23 ansible-nas sudo[25384]: pam_unix(sudo:auth): authentication failure; logname=sony uid=1000 euid=0 tty=/dev/pts/2 rus
мар 23 11:21:25 ansible-nas sudo[25384]: pam_unix(sudo:auth): conversation failed
мар 23 11:21:25 ansible-nas sudo[25384]: pam_unix(sudo:auth): auth could not identify password for [sony]
мар 23 11:21:25 ansible-nas sudo[25384]:     sony : 1 incorrect password attempt ; TTY=pts/2 ; PWD=/home/sony/ansible-nas ; USER=root
мар 23 11:21:25 ansible-nas postfix/pickup[24985]: ADBFD812BF: uid=1000 from=<sony>
мар 23 11:21:25 ansible-nas postfix/cleanup[25397]: ADBFD812BF: message-id=<20190323112125.ADBFD812BF@sony-virtual-machine.localdomai
мар 23 11:21:25 ansible-nas postfix/qmgr[2517]: ADBFD812BF: from=<sony@sony-virtual-machine.localdomain>, size=726, nrcpt=1 (queue ac
мар 23 11:21:25 ansible-nas postfix/local[25401]: ADBFD812BF: to=<root@sony-virtual-machine.localdomain>, orig_to=<root>, relay=local
мар 23 11:21:25 ansible-nas postfix/qmgr[2517]: ADBFD812BF: removed
lines 1658-1711/1711 (END)

```

> What filesystem are you using on your Ansible-NAS box?

 I did not change the settings. I do not care what the file system will be. 
_docker_storage_driver: zfs_

**Comment by davestephens** [comment]
What is your storage driver set to?

And what does `systemctl status docker.service` output?

**Comment by thebadgateway** [comment]
> What is your storage driver set to?

 I do not know how to install it

```
$ systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2019-03-23 05:29:21 UTC; 8h ago
     Docs: https://docs.docker.com
  Process: 23034 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
 Main PID: 23034 (code=exited, status=1/FAILURE)

мар 23 05:29:21 ansible-nas systemd[1]: docker.service: Service hold-off time over, scheduling restart.
мар 23 05:29:21 ansible-nas systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
мар 23 05:29:21 ansible-nas systemd[1]: Stopped Docker Application Container Engine.
мар 23 05:29:21 ansible-nas systemd[1]: docker.service: Start request repeated too quickly.
мар 23 05:29:21 ansible-nas systemd[1]: docker.service: Failed with result 'exit-code'.
мар 23 05:29:21 ansible-nas systemd[1]: Failed to start Docker Application Container Engine.

```

**Comment by davestephens** [comment]
Please re-read my comments above, it is set in all.yml.dist. You likely
have it set to the wrong thing - you should try overlay2 rather than ZFS.

I suggest you have a read through all.yml.dist, everything is documented in
there, including the thing I think is causing you issues (the docker
storage driver).

**Comment by thebadgateway** [comment]
I need an instruction.
I tried to change all.yml _docker_storage_driver: overlay_ or _docker_storage_driver: overlay2_
The error did not go away
![Screenshot_20190323_220607](https://user-images.githubusercontent.com/45717841/54867153-fc5fc700-4db7-11e9-8c7c-395bed0e4373.png)

**Comment by thebadgateway** [comment]
Please help me...

**Comment by davestephens** [comment]
After you changed to overlay2 I assume you re-ran the Ansible-NAS playbook?

`journalctl -u docker.service' might give you some more Docker specific info. 

Sadly there are literally 1001 reasons Docker may start, we've covered the most common one above - aside from that you'll need to do some digging yourself.

However, if you're unfamiliar with Linux, Docker, and Ansible, I'd question if Ansible-NAS is the project for you until you pick some of it up. More than happy to help where possible, but I can't teach you all of it through GitHub issues in afraid. Perhaps jump into the Gitter chat room and see if anyone there can help you?

**Comment by davestephens** [comment]
Closing due to no response
