### ISSUE TITLE
Error on "Create Gitlab user account" within GitLab tasks when building the playbook - User UID already exists

### ISSUE THREAD

**Issue by TngBlt** [davestephens/ansible-nas#685]
**Describe the bug**
Not sure if it is a bug or me not understanding the concept but got a fatal error when building the playbook adding gitLab container with 
```
gitlab_enabled: true
gitlab_available_externally: true
```
Got this error on task `Create GitLab user account`:
```
"msg": "usermod: UID '998' already exists\n",
```

**Environment**
- Ansible-NAS revision (`git rev-parse --short HEAD`): **248f418a**
- Ansible version (paste the entire output of `ansible --version` on the machine you run the playbook from): 
```
ansible 2.10.8
  config file = $home/ansible-nas/ansible.cfg
  configured module search path = ['$home/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
```
- Ansible-NAS operating system: `22.04 Jammy LTS`
- Ansible-NAS kernel: **Linux ansible-nas 5.15.0-88-generic** 
- Ansible-NAS Python version: **3.10.12**
- Ansible-NAS Docker version: **24.0.7**
- Are you running the playbook from a remote box or the Ansible-NAS box itself?  both
- Ansible-NAS filesystems:  **`/` on ext4** 

**Expected behavior**

The container should user the user already created right ? 

**Actual behavior**

The GitLab container can't build itself, the UID or GUID already exists.

**Playbook Output**
```
fatal: [ansible-nas]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "append": false,
            "authorization": null,
            "comment": null,
            "create_home": false,
            "expires": null,
            "force": false,
            "generate_ssh_key": null,
            "group": "gitlab",
            "groups": null,
            "hidden": null,
            "home": null,
            "local": null,
            "login_class": null,
            "move_home": false,
            "name": "gitlab",
            "non_unique": false,
            "password": null,
            "password_lock": null,
            "profile": null,
            "remove": false,
            "role": null,
            "seuser": null,
            "shell": null,
            "skeleton": null,
            "ssh_key_bits": 0,
            "ssh_key_comment": "ansible-generated on ansible-nas",
            "ssh_key_file": null,
            "ssh_key_passphrase": null,
            "ssh_key_type": "rsa",
            "state": "present",
            "system": true,
            "uid": 998,
            "update_password": "on_create"
        }
    },
    "msg": "usermod: UID '998' already exists\n",
    "name": "gitlab",
    "rc": 4
}
```

Thanks for the help  👍

**Comment by anarion80** [comment]
Yes, it seems this is an issue on hosts that already have UID 998. In my case it is user `systemd-coredump:x:998:998:systemd Core Dumper:/:/usr/sbin/nologin` and group `systemd-coredump:x:998:`

In my view both tasks to create the user and group are not really necessary. The directories can be created with user ID even if such username does not exist:

```
- name: Create Gitlab Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: 991
        group: 991
      with_items:
        - "{{ gitlab_data_directory }}/config"
        - "{{ gitlab_data_directory }}/log"
        - "{{ gitlab_data_directory }}/data"
```

And everything works then.

And I can see the gitlab will anyway change the ownership to `root` within the container...

**Comment by TngBlt** [comment]
Thanks @anarion80 ! When I comment the user and group tasks, the container starts ! But is **not** asking for a new password for connexion at first. Is there a variable I should define in my configuration ?

**Comment by anarion80** [comment]
According to [Gitlab Docs](https://docs.gitlab.com/ee/install/docker.html#installation) to set the initial root password you need to execute:
`sudo docker exec -it gitlab grep 'Password:' /etc/gitlab/initial_root_password`

or use GITLAB_ROOT_PASSWORD env variable in the task: https://docs.gitlab.com/ee/administration/environment_variables.html
