### ISSUE TITLE
Volumes documentation 

### ISSUE THREAD

**Issue by Bendolfc1** [davestephens/ansible-nas#686]
Just getting round to updating my install which is about 2 years old. Happily chugging away working nicely, although I've never taken to nzbget and saw more recent updates have Sab.

One thing I did notice is the there used to be some docs on the website for volumes, this all seems to have vanished now though.  Some of it was probably useful,  e.g. /mnt/Volume2 still looks to be hardcoded within the playback but doesn't seem to be mentioned anywhere in the docs.

There also used to be a handy guide to ZFS setup but that looks to have gone as well.

There might be a good reason for it going but it was deff handy.

**Comment by davestephens** [comment]
The docs were a bit stale, and I didn't want to be too opinionated about how someone should setup storage or ZFS, so removed them - they certainly weren't a one-size-fits-all approach, but are there in the git history if you want to dig them out.
