### ISSUE TITLE
Netdata not starting - netdata version compatability issue not ansible nas

### ISSUE THREAD

**Issue by georgejung** [davestephens/ansible-nas#694]
If you're reporting an issue with execution of the Ansible-NAS playbook, please run the playbook with `-vvv`, and ideally isolate the problematic part with `--tags <ansible tag>` where possible.

**Describe the bug**
Netdata hasn't been starting for sometime but I am not sure how long. It may be due to netdata not supporting older versions of OS / docker, I saw some issues on this but didn't get too much into it yet.

**Environment**
- Ansible-NAS revision (`git rev-parse --short HEAD`): 6bf518c
- Ansible version (paste the entire output of `ansible --version` on the machine you run the playbook from): 2.9.6
- Ansible-NAS operating system (`cat /etc/lsb-release` on the Ansible-NAS box) - _Support won't be provided for non-LTS releases of Ubuntu_: Ubuntu Server 20.04.2 LTS
- Ansible-NAS kernel (`uname -a` on the Ansible-NAS box):  Linux ansible-nas 5.15.0-89-generic #99~20.04.1-Ubuntu SMP Thu Nov 2 15:16:47 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Ansible-NAS Python version (`python --version` on the Ansible-NAS box): Python 3.8.10
- Ansible-NAS Docker version (`docker --version` on the Ansible-NAS box): Docker version 20.10.3, build 48d30b5
- Latest Docker logs (`journalctl -u docker.service` on the Ansible-NAS box):
- Are you running the playbook from a remote box or the Ansible-NAS box itself? Ansible-NAS box itself
- Vagrant version, if testing (`vagrant --version`):
- Ansible-NAS filesystems (`df -hT` on the Ansible-NAS box):
- Mounted filesystems (`mount` on the Ansible-NAS box)

**all.yml Variables**
- `docker_image_directory`:
- `docker_home`:
- `docker_storage_driver`:
- `samba_shares_root`:

**Expected behavior**
Container should start and web gui should be accessible.

**Actual behavior**
Container doesn't start but portainer status is running which is maybe why I didn't notice until 2 weeks ago and just got around to troubleshooting.

**Steps to reproduce**
Nothing, I just noticed this and it had been running fine for sometime.

**Playbook Output**
Didn't re-run I manually updated container image via portainer.

**Additional context**
I reverted back from latest to v1.36.0 from Aug 10, 2022 and it started again as normal. Not sure what the most recent version of netdata is that will work with my system but will try some more and report back. Just wanted to share with others as I didn't see it mentioned.

**Comment by davestephens** [comment]
Closing this - I don't use netdata so feel free to reopen if it's actually an Ansible-NAS issue. Sounds like it's not from what you've written above...
