### ISSUE TITLE
Add valheim-docker

### ISSUE THREAD

**Issue by elliotpryde** [davestephens/ansible-nas#696]
**Application you'd like to add:**

[Valheim-docker](https://github.com/mbround18/valheim-docker), which is a self-hosted multiplayer server for the popular video game [Valheim](https://store.steampowered.com/app/892970/Valheim/). This is similar to the Minecraft server that's already available.

**Link to Docker image:**

https://hub.docker.com/r/mbround18/valheim

**Why you'd like this application added:**

I'll be setting up another server using this Docker image soon and figured that it'd make sense to have the config in this project if others would like it. This was fairly easy to get running when I last used it ~1 year or so ago, it only required a few directories to exist to place game save files and backups + a docker-compose file to keep things tidy.

**Comment by davestephens** [comment]
Looks pretty cool, would be happy to accept a PR!
