### ISSUE TITLE
Add Jellyfin support (fully open-source Emby fork)

### ISSUE THREAD

**Issue by scotws** [davestephens/ansible-nas#70]
We've already included two media servers, Plex and Emby, so this is probably a "nice to have". However, since it is a fork of Emby, it should be trivial to add (I know, I know, famous last words). 

https://github.com/jellyfin/jellyfin
https://hub.docker.com/r/jellyfin/jellyfin/

_Jellyfin is a Free Software Media System that puts you in control of managing and streaming your media. It is an alternative to the proprietary Emby and Plex, to provide media from a dedicated server to end-user devices via multiple apps. Jellyfin is descended from Emby's 3.5.2 release and ported to the .NET Core framework to enable full cross-platform support. There are no strings attached, no premium licenses or features, and no hidden agendas (...)_

**Comment by jesse-troy** [comment]
I was actually looking into this last weekend. I plan to test it out and if it works well then I will add this in a PR.

**Comment by bcurran3** [comment]
Jellyfin was added, I think this can be closed now.
