### ISSUE TITLE
Traefik IPWhiteList deprecated - IPAllowList

### ISSUE THREAD

**Issue by georgejung** [davestephens/ansible-nas#703]
If you're reporting an issue with execution of the Ansible-NAS playbook, please run the playbook with `-vvv`, and ideally isolate the problematic part with `--tags <ansible tag>` where possible.

**Describe the bug**
Traefik has deprecated the IPwhitelist in favour of IPAllowList. I noticed it with Portainer and it also applies to Bitwarden.

**Steps to reproduce**

Use traefik and make portainer or bitwarden available externally.

**Playbook Output**
From traefik logs

```time="2024-03-30T15:03:51Z" level=warning msg="IPWhiteList is deprecated, please use IPAllowList instead." entryPointName=websecure routerName=websecure-portainer@docker```

**Additional context**
I made the following changes, which seemed to resolve the warning I was getting in traefik logs. Not sure if I did it correctly but here it is for what its worth.
For tasks/main.yml - middleware needs to be updated from IPWhiteList to IPAllowList or ip_whitelist to ip_allowlist. Also the label for middleware source range needs to be changed in 2 spots, ipwhitelist to ipallowlist. And lastly the defualts/main.yml, ip_whitelist needs to change to ip_allowlist.

**Comment by nickjones33** [comment]
created PR #719
