### ISSUE TITLE
ansible-nas on different VM's with one traefik instance

### ISSUE THREAD

**Issue by tobiasstraub** [davestephens/ansible-nas#715]
Hi everyone,

great project! Unfortunately, the discussion button is disabled here, so I’m asking for help here instead. I hope that's okay.

I have a server with three VMs and would like to run ansible-nas with different applications enabled on each of the three VMs. So far, no problem. However, I want to run traefik only on one VM with one domain <application>.domain.com. How should I adjust ansible-nas for this, so that I can activate/deactivate external_access via "<application_name>_available_externally" in one of the three ansible-nas configurations to route incoming traffic to the correct docker container?

Thank you for help.

**Comment by davestephens** [comment]
With the way Traefik is set up, Ansible-NAS is designed to be run on a single box. I use docker annotations which Traefik reads to generate its config. This obviously doesn't work across different hosts. 

What you're after is out of scope of Ansible-NAS - the setup you describe is typically done by something like Kubernetes or Nomad, which I have no interest in attempting to replicate with manually generated config :-)

That said, if you're running multiple VMs on a single proxmox box I'd question the point of having multiple VMs at all - simply run everything as Docker containers on the bare metal and don't worry about unnecessary complexity.
