### ISSUE TITLE
Vagrant test script fails due to version mismatch

### ISSUE THREAD

**Issue by scotws** [davestephens/ansible-nas#74]
**Short problem description**

After changes to config files, attempt to run test version with `tests/test-vagrant.sh` as specified in README.md produces the following error message in a slightly scary red font:

> This Vagrant environment has specified that it requires the Vagrant
> version to satisfy the following version requirements:
> 
>   >= 2.2.2
> 
> You are running Vagrant 2.0.2, which does not satisfy
> these requirements. (...)

Then the Vagrant VM cannot be accessed. This is on stock Ubuntu 18.04.02 LTS with Vagrant as installed with `sudo apt install vagrant`.

**Environment**
- Ansible-NAS revision (`git rev-parse --short HEAD`): 417f997
- Ansible version (paste the entire output of `ansible --version` on the machine you run the playbook from):

```
ansible 2.5.1
  config file = /home/scot/Programming/ansible-nas/ansible.cfg
  configured module search path = [u'/home/scot/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```
- Ansible-NAS operating system (`cat /etc/lsb-release` on the Ansible-NAS box) - _If this is anything other than Ubuntu 18.04 help will be limited_:

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
```
- Ansible-NAS kernel (`cat /etc/lsb-release` on the Ansible-NAS box): (as above)
- Ansible-NAS Python version (`python --version` on the Ansible-NAS box): (as above)
- Ansible-NAS Docker version (`docker --version` on the Ansible-NAS box): Docker version 18.09.2, build 6247962
- Latest Docker logs (`journalctl -u docker.service` on the Ansible-NAS box): n/a and too long
- Are you running the playbook from a remote box or the Ansible-NAS box itself?  Box itself
- Vagrant version, if testing (`vagrant --version`): Vagrant 2.0.2

**Expected behavior**

Create virtual machine for testing.

**Actual behavior**

Error message as above, VM won't run.

**Steps to reproduce**

Attempt to run `tests/test-vagrant.sh` as specified in the docs.

**Playbook Output**

n/a

**Comment by davestephens** [comment]
Does it work if you install Vagrant from https://www.vagrantup.com/downloads.html instead of using the system installed one? There was a reason I targeted 2.2.2, I just can't remember that reason right now ;-)

**Comment by scotws** [comment]
(Brief rant: Things like this really, really annoy me about Ubuntu to the point where I've considered switching to Arch Linux (but the ZFS support sucks) or even FreeBSD (but no Docker support). Too much stuff is just too old. -- Thanks, I feel better now)

Downloading 2.2.4 from the website works. That should probably go in the docs? I'll add a PR.

**Comment by davestephens** [comment]
:D Totally agree, Ubuntu is great but the a lot of the packages are ancient!
