### ISSUE TITLE
please consider to add onlyoffice with nextcloud

### ISSUE THREAD

**Issue by changchichung** [davestephens/ansible-nas#75]
thanks for the great playbook.

onlyoffice is a system can be integrated with nextcloud to open office documents online like G suite or Office 365 online, and it also have docker version.

Can you please consider to add the task to install onlyoffice integrated with nextcloud ?

**Comment by davestephens** [comment]
This is not something that I want personally, but would be more than happy to accept a PR. Perhaps if you can provide some more info about how you would expect this to integrate then someone (or you) could pick it up?

**Comment by davestephens** [comment]
Closing (stale)
