### ISSUE TITLE
netdata instead of Grafana?

### ISSUE THREAD

**Issue by ipepe** [davestephens/ansible-nas#8]
how about [netdata](https://github.com/firehol/netdata) instead of Grafana? It supports multiple monitoring parameters out of box. It even supports zfs parameters

**Comment by davestephens** [comment]
I'd never seen that until you mentioned it to me - it looks very cool! I'd definitely accept a PR if you're willing to have a go at one.

I also don't think we'd need to replace Grafana entirely, it looks like it could sit alongside telegraf, influxdb and grafana, or be feature toggled like all of the other containers.

**Comment by ipepe** [comment]
I'm worried that if we put it into container. We will loose some information - like ZFS.

**Comment by davestephens** [comment]
It looks like it reads `/proc/spl/kstat/zfs/arcstats` - I wonder if it could be worked around by mounting this into the container?

**Comment by ipepe** [comment]
Yeah, I wonder the same. I'm currently in process of rebuilding my NAS and will try to test it as soon as I will find some spare time.

**Comment by davestephens** [comment]
Great, keep me posted! 👍

**Comment by C-J1** [comment]
netdata looks bloody awesome.

How would you feel installing it on the host instead of in a container? Most of the doco, blogs, and forum posts I've read recommend doing that.

**Comment by davestephens** [comment]
It looks like it installs with Docker too, I think it'd be worth trying that to see what you do/don't get?

My aim with Ansible-NAS is to keep things as light as possible on the host os where possible!

**Comment by C-J1** [comment]
Added PR #21 for this.

**Comment by davestephens** [comment]
Merged #29 (thanks @C-J1) which adds netdata support. IMO it's good to have as an option instead of influx/telegraf/grafana rather than a complete replacement. Works nicely in Docker too!
