### ISSUE TITLE
Switch to using updated sickchill container

### ISSUE THREAD

**Issue by l3rady** [davestephens/ansible-nas#81]
The Sickrage container used is no longer supported and have moved over to a new container called sickchill: https://github.com/linuxserver/docker-sickrage/pull/45

Would be nice to see ansible nas move over to this container instead: https://github.com/linuxserver/docker-sickchill

**Comment by davestephens** [comment]
More than happy to switch and/or accept a PR if you want to contribute 👍

**Comment by l3rady** [comment]
Sure thing: https://github.com/davestephens/ansible-nas/pull/82
