### ISSUE TITLE
Write a short guide to testing Ansible-NAS on VirtualBox

### ISSUE THREAD

**Issue by scotws** [davestephens/ansible-nas#84]
We currently suggest that people test Ansible-NAS in VirtualBox (https://github.com/davestephens/ansible-nas/blob/master/docs/overview.md) without giving much detail how. It might be worth adding a few more lines including the required steps like creating two extra virtual drives to test ZFS installation etc.

**Comment by davestephens** [comment]
Yeah, this is a good idea. There's already some docs I wrote for testing,
but it could all do with fleshing out - especially if we're telling people
to test ZFS virtually before deciding to go with Ansible-NAS.
