### ISSUE TITLE
Is ansible-nas compatible with Ubuntu MATE?

### ISSUE THREAD

**Issue by tmx-dxiao** [davestephens/ansible-nas#88]
As title.

**Comment by davestephens** [comment]
Probably. As long as it's version 18.04. Ansible NAS is developed on Ubuntu Server, which has no window manager installed out of the box.

That said, a NAS / homeserver is not typically a box you'd log into when sat it front of it, so using Ubuntu MATE is completely pointless as the "MATE" derivative refers to the window manager, nothing more.
