### ISSUE TITLE
Reorganize all.yml

### ISSUE THREAD

**Issue by scotws** [davestephens/ansible-nas#89]
The number of entries in the lower parts of all.yml is getting large enough that finding things is becoming hard. Starting about line 243 - the part the user shouldn't touch anyway - we should sort them by name to make everybody's life easier. (I should be able to do a PR later today)

**Comment by caillou** [comment]
Wouldn't it make sense to have a way to `include` the configs for the different services? That way, we'd have just a single include per service, with the configs in the files.

**Comment by koenvervloesem** [comment]
@caillou I agree. With every new service added, I have to merge my `all.yml` with the default `all.yml.dist` to make sure I didn't forget any new services I don't need now but might need in the future. If it's just one `include` for each new service, merging the configuration of new services is much more manageable.

**Comment by scotws** [comment]
That makes more sense. If @davestephens agrees, I'd withdraw this issue and the PR?

**Comment by caillou** [comment]
@scotws taken that you opened both the issue and the PR, I think you can close then again, can't you?

**Comment by davestephens** [comment]
Hi,

Bit late to the party here, apologies, wanted to give this some thought before adding by £0.02. Few thoughts;

- I do agree that the rejig will cause a lot of headache for people checking if they're up to that, that said, given the change is to the .dist file (and not something checked in to the repo) the conflicts won't be git merge conflicts.

- I don't like the thought of a bajillion .dist files in the `./group_vars` directory, I think it's moving the problem of merging files to diffing directory structures instead. I think it'd get messy quickly. And how would distribution be handled? Would you expect as many dist files that there are apps, and the user has to copy each one from a `.yml.dist` to a `.yml`?

I've had another idea which may work nicely, which is based on the model https://github.com/kubernetes-sigs/kubespray uses, and would change the way new users use Ansible-NAS a bit. 

How it would be different; 

- A new `inventories/sample` directory created.
- No dist config in `./group_vars` as it is now, it would be moved to `inventories/sample/group_vars`.
- Config in all.yml.dist split into separate files for clarity.
- All `*.yml.dist` files renamed to `*.yml.dist`.
- For a new Ansible-NAS install, the user would copy the `inventories/sample` directory to `inventories/awesome_nas`, and tweak as appropriate
- For an existing Ansible-NAS install, getting the latest config updates would involve running a simple diff of two directories and copying in the missing files/config keys from `inventories/sample` directory to `inventories/awesome_nas`. Scripts could be provided to make this easy for users. 

Thoughts?

**Comment by koenvervloesem** [comment]
The Kubespray approach sounds like a good solution.

There's just one thing I don't understand:

>     All `*.yml.dist` files renamed to `*.yml.dist`.

Typo?

**Comment by davestephens** [comment]
Good spot, I've updated it.

**Comment by caillou** [comment]
@davestephens another option came to my mind:

1. We move `all.dist.yml` to `defaults.yml`
2. In `all.yml` the users simply overwrite the defaults they want changed. `defaults.yml` and `all.yml` get merged, with priority on `all.yml`.

This would ensure backwards-compatibility. But for new users, it would mean a much smaller file, with only relevant entries.

We could then split the `defaults.yml` into `defaults/*.yml` for clarity. And `all.yml` into `all/*.yml`. Some users might prefer a single file, others might like their files split up.

This ensures that new variables in `defaults.yml` are automatically included, without the need to copy/paste anything.

**Comment by davestephens** [comment]
That's actually not a bad idea. The merge could be done natively with Ansible. 

Only thing to consider is ensuring backwards compatibility with the current way of doing things, which I think would be do-able.

**Comment by scotws** [comment]
I've closed the original PR, but will leave this thread open until somebody adds a different PR; now different subject line.

**Comment by davestephens** [comment]
I've just pushed https://github.com/davestephens/ansible-nas/commit/60094d192b0b8c781878655e4a9fa348a67ae26e onto the branch `config-rejig` with my ideas based on the discussion above.

Thoughts appreciated!

**Comment by caillou** [comment]
@davestephens Brilliant!

Just a thought: `group_vars/all.yml` should not be edited by the users, right? Would it make sense to commit a hash of the file and check, that the users did not edit the file when running the playbook?

**Comment by animeai** [comment]
I've actually got a bunch of fixes and formatting to submit as a PR (once I validate they all work as expected and I didn't make any silly mistakes!) https://github.com/animeai/ansible-nas/tree/Fixes-and-new-containers (currently only fixes - I'm going to create a separate branch for each new container to make it easy to accept/reject them here at the master).

Currently it passes linting and builds without error but I've not tried connecting to anything yet or looking at the container statuses as I ran out of time last night. Once I'm finished, I'll clean up all the silly pushes into a fresh branch and submit. Have you been doing any behind the scenes work on this rejig, if so I need to hold off on any major surgery and/or new additions (I have quite a few containers I want to add and test lol) until I completely understand how the new all.yml and individual ymls will work for configuration etc as I don't want to add a bunch more work! If you've not done anything other than what's pushed to the config_rejig branch I can probably safely work for now as merging the PRs should be trivial at this point, it just gets more complex later.

**Comment by animeai** [comment]
@davestephens 
For this to work properly, we need to make sure that tasks/appname.yml should never need to be edited unless a container is broken. To this end I'm making an [horrendously messed up branch](https://github.com/animeai/ansible-nas/tree/config-rejig-proposal) to ensure I capture all the variables from the tasks folders that might need editing and make sure everything has an appropriate and obvious variable name. Once I'm done I can merge this all back together so don't panic too much if you look into this branch on my fork! This messed up fork is of course also an alternative way we could approach this as merge headaches would still be much reduced.

Regardless of the finally selected method, I'd personally suggest moving the enable/disable lines to their own file away from settings variables (potentially still as a .dist?) and having the separate secure credentials.yml which can be chowned/moded to root and 600 for security.

**Comment by davestephens** [comment]
OK, this is now in #193. 

I'd like to get it merged ASAP, then merge @animeai's awesome #188 in too. 

Would appreciate any comments/thoughts/abuse/love offered...

**Comment by davestephens** [comment]
#193 now merged :+1:
