### ISSUE TITLE
Add a default Sanoid ZFS snapshot configuration

### ISSUE THREAD

**Issue by scotws** [davestephens/ansible-nas#97]
It is pretty likely that users will have one or more ZFS datasets ("shares") for Plex/Emby/Jellyfish, so it might be worth provided an example Sanoid configuration for snapshots of these filesystems. This could possibly be made into an Ansible thingie to automate?

**Comment by animeai** [comment]
`sudo apt install zfs-auto-snapshot`

Then edit the crons it generates in /etc/cron.d/ :
zfs-auto-snapshot.cron.daily
zfs-auto-snapshot.cron.frequent
zfs-auto-snapshot.cron.hourly
zfs-auto-snapshot.cron.monthly
zfs-auto-snapshot.cron.weekly

This is the most simple way to manage your snapshots, no playbook necessary :)

**Comment by wolffstarr** [comment]
Sanoid plays nice with Syncoid, which can be more than occasionally useful, and has simpler bulk-configuration than zfs-auto-snapshot does.

Though, not sure why you're editing your cron files for it - the defaults are sane. All you need to do is add `com.sun:auto-snapshot=true` and same for whatever schedule you want to set: `com.sun:auto-snapshot:frequent=true`, continue on for hourly daily weekly and monthly.

**Comment by bcurran3** [comment]
If added, please don't make it default. Make it an enable/disable option. I don't use ZFS. :)

**Comment by davestephens** [comment]
No action on this one. Happy to accept PRs if people think it's useful.
